// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: alerts.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"popplio/types"
)

const ackAlert = `-- name: AckAlert :exec
UPDATE alerts SET acked = true WHERE user_id = $1 AND itag = $2
`

type AckAlertParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Itag   pgtype.UUID `db:"itag" json:"itag"`
}

func (q *Queries) AckAlert(ctx context.Context, arg AckAlertParams) error {
	_, err := q.db.Exec(ctx, ackAlert, arg.UserID, arg.Itag)
	return err
}

const countUnackedUserAlerts = `-- name: CountUnackedUserAlerts :one
SELECT COUNT(*) FROM alerts WHERE user_id = $1 AND acked = false
`

func (q *Queries) CountUnackedUserAlerts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUnackedUserAlerts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUserAlerts = `-- name: CountUserAlerts :one
SELECT COUNT(*) FROM alerts WHERE user_id = $1
`

func (q *Queries) CountUserAlerts(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countUserAlerts, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteAllUserAlerts = `-- name: DeleteAllUserAlerts :exec
DELETE FROM alerts WHERE user_id = $1
`

func (q *Queries) DeleteAllUserAlerts(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAllUserAlerts, userID)
	return err
}

const deleteUserAlert = `-- name: DeleteUserAlert :exec
DELETE FROM alerts WHERE user_id = $1 AND itag = $2
`

type DeleteUserAlertParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Itag   pgtype.UUID `db:"itag" json:"itag"`
}

func (q *Queries) DeleteUserAlert(ctx context.Context, arg DeleteUserAlertParams) error {
	_, err := q.db.Exec(ctx, deleteUserAlert, arg.UserID, arg.Itag)
	return err
}

const getUserAlertByItag = `-- name: GetUserAlertByItag :one
SELECT itag, url, message, type, title, created_at, acked, alert_data, icon, priority, category
FROM alerts
WHERE user_id = $1 AND itag = $2
`

type GetUserAlertByItagParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Itag   pgtype.UUID `db:"itag" json:"itag"`
}

type GetUserAlertByItagRow struct {
	Itag      pgtype.UUID         `db:"itag" json:"itag"`
	Url       pgtype.Text         `db:"url" json:"url"`
	Message   string              `db:"message" json:"message"`
	Type      types.AlertType     `db:"type" json:"type"`
	Title     string              `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	Acked     bool                `db:"acked" json:"acked"`
	AlertData map[string]any      `db:"alert_data" json:"alert_data"`
	Icon      pgtype.Text         `db:"icon" json:"icon"`
	Priority  types.AlertPriority `db:"priority" json:"priority"`
	Category  types.AlertCategory `db:"category" json:"category"`
}

func (q *Queries) GetUserAlertByItag(ctx context.Context, arg GetUserAlertByItagParams) (GetUserAlertByItagRow, error) {
	row := q.db.QueryRow(ctx, getUserAlertByItag, arg.UserID, arg.Itag)
	var i GetUserAlertByItagRow
	err := row.Scan(
		&i.Itag,
		&i.Url,
		&i.Message,
		&i.Type,
		&i.Title,
		&i.CreatedAt,
		&i.Acked,
		&i.AlertData,
		&i.Icon,
		&i.Priority,
		&i.Category,
	)
	return i, err
}

const getUserAlertsByAcked = `-- name: GetUserAlertsByAcked :many
SELECT itag, url, message, type, title, created_at, acked, alert_data, icon, priority, category
FROM alerts
WHERE user_id = $1 AND acked = $2
ORDER BY created_at DESC, priority ASC
LIMIT $3
`

type GetUserAlertsByAckedParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Acked  bool   `db:"acked" json:"acked"`
	Limit  int32  `db:"limit" json:"limit"`
}

type GetUserAlertsByAckedRow struct {
	Itag      pgtype.UUID         `db:"itag" json:"itag"`
	Url       pgtype.Text         `db:"url" json:"url"`
	Message   string              `db:"message" json:"message"`
	Type      types.AlertType     `db:"type" json:"type"`
	Title     string              `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	Acked     bool                `db:"acked" json:"acked"`
	AlertData map[string]any      `db:"alert_data" json:"alert_data"`
	Icon      pgtype.Text         `db:"icon" json:"icon"`
	Priority  types.AlertPriority `db:"priority" json:"priority"`
	Category  types.AlertCategory `db:"category" json:"category"`
}

func (q *Queries) GetUserAlertsByAcked(ctx context.Context, arg GetUserAlertsByAckedParams) ([]GetUserAlertsByAckedRow, error) {
	rows, err := q.db.Query(ctx, getUserAlertsByAcked, arg.UserID, arg.Acked, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAlertsByAckedRow
	for rows.Next() {
		var i GetUserAlertsByAckedRow
		if err := rows.Scan(
			&i.Itag,
			&i.Url,
			&i.Message,
			&i.Type,
			&i.Title,
			&i.CreatedAt,
			&i.Acked,
			&i.AlertData,
			&i.Icon,
			&i.Priority,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAlertsPage = `-- name: GetUserAlertsPage :many
SELECT itag, url, message, type, title, created_at, acked, alert_data, icon, priority, category
FROM alerts
WHERE user_id = $1
ORDER BY created_at DESC, priority ASC
LIMIT $2 OFFSET $3
`

type GetUserAlertsPageParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
}

type GetUserAlertsPageRow struct {
	Itag      pgtype.UUID         `db:"itag" json:"itag"`
	Url       pgtype.Text         `db:"url" json:"url"`
	Message   string              `db:"message" json:"message"`
	Type      types.AlertType     `db:"type" json:"type"`
	Title     string              `db:"title" json:"title"`
	CreatedAt pgtype.Timestamptz  `db:"created_at" json:"created_at"`
	Acked     bool                `db:"acked" json:"acked"`
	AlertData map[string]any      `db:"alert_data" json:"alert_data"`
	Icon      pgtype.Text         `db:"icon" json:"icon"`
	Priority  types.AlertPriority `db:"priority" json:"priority"`
	Category  types.AlertCategory `db:"category" json:"category"`
}

func (q *Queries) GetUserAlertsPage(ctx context.Context, arg GetUserAlertsPageParams) ([]GetUserAlertsPageRow, error) {
	rows, err := q.db.Query(ctx, getUserAlertsPage, arg.UserID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAlertsPageRow
	for rows.Next() {
		var i GetUserAlertsPageRow
		if err := rows.Scan(
			&i.Itag,
			&i.Url,
			&i.Message,
			&i.Type,
			&i.Title,
			&i.CreatedAt,
			&i.Acked,
			&i.AlertData,
			&i.Icon,
			&i.Priority,
			&i.Category,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAlert = `-- name: InsertAlert :exec
INSERT INTO alerts (user_id, type, url, message, title, icon, alert_data, priority, category)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
`

type InsertAlertParams struct {
	UserID    string              `db:"user_id" json:"user_id"`
	Type      types.AlertType     `db:"type" json:"type"`
	Url       pgtype.Text         `db:"url" json:"url"`
	Message   string              `db:"message" json:"message"`
	Title     string              `db:"title" json:"title"`
	Icon      pgtype.Text         `db:"icon" json:"icon"`
	AlertData map[string]any      `db:"alert_data" json:"alert_data"`
	Priority  types.AlertPriority `db:"priority" json:"priority"`
	Category  types.AlertCategory `db:"category" json:"category"`
}

func (q *Queries) InsertAlert(ctx context.Context, arg InsertAlertParams) error {
	_, err := q.db.Exec(ctx, insertAlert,
		arg.UserID,
		arg.Type,
		arg.Url,
		arg.Message,
		arg.Title,
		arg.Icon,
		arg.AlertData,
		arg.Priority,
		arg.Category,
	)
	return err
}

const unackAlert = `-- name: UnackAlert :exec
UPDATE alerts SET acked = false WHERE user_id = $1 AND itag = $2
`

type UnackAlertParams struct {
	UserID string      `db:"user_id" json:"user_id"`
	Itag   pgtype.UUID `db:"itag" json:"itag"`
}

func (q *Queries) UnackAlert(ctx context.Context, arg UnackAlertParams) error {
	_, err := q.db.Exec(ctx, unackAlert, arg.UserID, arg.Itag)
	return err
}
