// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: apps.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPendingUserApps = `-- name: CountPendingUserApps :one
SELECT COUNT(*) FROM apps WHERE user_id = $1 AND position = $2 AND state = 'pending'
`

type CountPendingUserAppsParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Position string `db:"position" json:"position"`
}

func (q *Queries) CountPendingUserApps(ctx context.Context, arg CountPendingUserAppsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPendingUserApps, arg.UserID, arg.Position)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLastAppCreatedAt = `-- name: GetLastAppCreatedAt :one
SELECT created_at FROM apps WHERE user_id = $1 AND position = $2 ORDER BY created_at DESC LIMIT 1
`

type GetLastAppCreatedAtParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Position string `db:"position" json:"position"`
}

func (q *Queries) GetLastAppCreatedAt(ctx context.Context, arg GetLastAppCreatedAtParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastAppCreatedAt, arg.UserID, arg.Position)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getUserAppBanned = `-- name: GetUserAppBanned :one
SELECT app_banned FROM users WHERE user_id = $1
`

func (q *Queries) GetUserAppBanned(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, getUserAppBanned, userID)
	var app_banned bool
	err := row.Scan(&app_banned)
	return app_banned, err
}

const getUserApps = `-- name: GetUserApps :many
SELECT app_id, user_id, questions, answers, state, created_at, position, review_feedback
FROM apps
WHERE user_id = $1
`

type GetUserAppsRow struct {
	AppID          string             `db:"app_id" json:"app_id"`
	UserID         string             `db:"user_id" json:"user_id"`
	Questions      []byte             `db:"questions" json:"questions"`
	Answers        map[string]string  `db:"answers" json:"answers"`
	State          string             `db:"state" json:"state"`
	CreatedAt      pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Position       string             `db:"position" json:"position"`
	ReviewFeedback pgtype.Text        `db:"review_feedback" json:"review_feedback"`
}

func (q *Queries) GetUserApps(ctx context.Context, userID string) ([]GetUserAppsRow, error) {
	rows, err := q.db.Query(ctx, getUserApps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserAppsRow
	for rows.Next() {
		var i GetUserAppsRow
		if err := rows.Scan(
			&i.AppID,
			&i.UserID,
			&i.Questions,
			&i.Answers,
			&i.State,
			&i.CreatedAt,
			&i.Position,
			&i.ReviewFeedback,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertApp = `-- name: InsertApp :exec
INSERT INTO apps (app_id, user_id, position, questions, answers) VALUES ($1, $2, $3, $4, $5)
`

type InsertAppParams struct {
	AppID     string            `db:"app_id" json:"app_id"`
	UserID    string            `db:"user_id" json:"user_id"`
	Position  string            `db:"position" json:"position"`
	Questions []byte            `db:"questions" json:"questions"`
	Answers   map[string]string `db:"answers" json:"answers"`
}

func (q *Queries) InsertApp(ctx context.Context, arg InsertAppParams) error {
	_, err := q.db.Exec(ctx, insertApp,
		arg.AppID,
		arg.UserID,
		arg.Position,
		arg.Questions,
		arg.Answers,
	)
	return err
}
