// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: arcadia.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const activateAuthChain = `-- name: ActivateAuthChain :exec
UPDATE staffpanel__authchain SET state = 'active' WHERE token = $1
`

func (q *Queries) ActivateAuthChain(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, activateAuthChain, token)
	return err
}

const countAuthChainByToken = `-- name: CountAuthChainByToken :one
SELECT COUNT(*) FROM staffpanel__authchain WHERE token = $1
`

func (q *Queries) CountAuthChainByToken(ctx context.Context, token string) (int64, error) {
	row := q.db.QueryRow(ctx, countAuthChainByToken, token)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countBotsByType = `-- name: CountBotsByType :many
SELECT type AS method, COUNT(*) FROM bots GROUP BY type
`

type CountBotsByTypeRow struct {
	Method string `db:"method" json:"method"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) CountBotsByType(ctx context.Context) ([]CountBotsByTypeRow, error) {
	rows, err := q.db.Query(ctx, countBotsByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountBotsByTypeRow
	for rows.Next() {
		var i CountBotsByTypeRow
		if err := rows.Scan(&i.Method, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countRecentRPCLogs = `-- name: CountRecentRPCLogs :one
SELECT COUNT(*) FROM rpc_logs WHERE user_id = $1 AND NOW() - created_at < INTERVAL '7 minutes'
`

func (q *Queries) CountRecentRPCLogs(ctx context.Context, userID string) (int64, error) {
	row := q.db.QueryRow(ctx, countRecentRPCLogs, userID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countStaffPositionByNameOrRoleID = `-- name: CountStaffPositionByNameOrRoleID :one
SELECT EXISTS(SELECT 1 FROM staff_positions WHERE name = $1 OR role_id = $2)
`

type CountStaffPositionByNameOrRoleIDParams struct {
	Name   string `db:"name" json:"name"`
	RoleID string `db:"role_id" json:"role_id"`
}

func (q *Queries) CountStaffPositionByNameOrRoleID(ctx context.Context, arg CountStaffPositionByNameOrRoleIDParams) (bool, error) {
	row := q.db.QueryRow(ctx, countStaffPositionByNameOrRoleID, arg.Name, arg.RoleID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteAuthChainByToken = `-- name: DeleteAuthChainByToken :execrows
DELETE FROM staffpanel__authchain WHERE token = $1
`

func (q *Queries) DeleteAuthChainByToken(ctx context.Context, token string) (int64, error) {
	result, err := q.db.Exec(ctx, deleteAuthChainByToken, token)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteAuthChainByUserID = `-- name: DeleteAuthChainByUserID :exec
DELETE FROM staffpanel__authchain WHERE user_id = $1
`

func (q *Queries) DeleteAuthChainByUserID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteAuthChainByUserID, userID)
	return err
}

const deleteEntityBadge = `-- name: DeleteEntityBadge :exec
DELETE FROM entity_badges WHERE target_type = $1 AND target_id = $2 AND badge_id = $3
`

type DeleteEntityBadgeParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
	BadgeID    string `db:"badge_id" json:"badge_id"`
}

func (q *Queries) DeleteEntityBadge(ctx context.Context, arg DeleteEntityBadgeParams) error {
	_, err := q.db.Exec(ctx, deleteEntityBadge, arg.TargetType, arg.TargetID, arg.BadgeID)
	return err
}

const deleteExpiredPendingAuthChainEntries = `-- name: DeleteExpiredPendingAuthChainEntries :exec
DELETE FROM staffpanel__authchain WHERE state = 'pending' AND created_at < NOW() - INTERVAL '5 minutes'
`

func (q *Queries) DeleteExpiredPendingAuthChainEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredPendingAuthChainEntries)
	return err
}

const deleteStaffMember = `-- name: DeleteStaffMember :exec
DELETE FROM staff_members WHERE user_id = $1
`

func (q *Queries) DeleteStaffMember(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteStaffMember, userID)
	return err
}

const deleteStaffPosition = `-- name: DeleteStaffPosition :exec
DELETE FROM staff_positions WHERE id = $1
`

func (q *Queries) DeleteStaffPosition(ctx context.Context, id pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteStaffPosition, id)
	return err
}

const deleteStaleAuthChainEntries = `-- name: DeleteStaleAuthChainEntries :exec
DELETE FROM staffpanel__authchain WHERE last_seen_at < NOW() - INTERVAL '1 hour'
`

func (q *Queries) DeleteStaleAuthChainEntries(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteStaleAuthChainEntries)
	return err
}

const getActiveStaffDisciplinaries = `-- name: GetActiveStaffDisciplinaries :many
SELECT d.id, d.created_at, EXTRACT(epoch FROM d.expiry) AS expiry, d.title, d.description, d.type,
	t.name AS type_name, t.description AS type_description, t.self_assignable, t.perm_limits, t.additory, t.needs_approval,
	EXTRACT(epoch FROM t.max_expiry) AS max_expiry, t.created_at AS type_created_at
FROM staff_disciplinary d LEFT JOIN staff_disciplinary_types t ON t.id = d.type
WHERE d.user_id = $1 AND NOW() - d.created_at < d.expiry
`

type GetActiveStaffDisciplinariesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Expiry          pgtype.Numeric     `db:"expiry" json:"expiry"`
	Title           string             `db:"title" json:"title"`
	Description     string             `db:"description" json:"description"`
	Type            string             `db:"type" json:"type"`
	TypeName        pgtype.Text        `db:"type_name" json:"type_name"`
	TypeDescription pgtype.Text        `db:"type_description" json:"type_description"`
	SelfAssignable  pgtype.Bool        `db:"self_assignable" json:"self_assignable"`
	PermLimits      []string           `db:"perm_limits" json:"perm_limits"`
	Additory        pgtype.Bool        `db:"additory" json:"additory"`
	NeedsApproval   pgtype.Bool        `db:"needs_approval" json:"needs_approval"`
	MaxExpiry       pgtype.Numeric     `db:"max_expiry" json:"max_expiry"`
	TypeCreatedAt   pgtype.Timestamptz `db:"type_created_at" json:"type_created_at"`
}

func (q *Queries) GetActiveStaffDisciplinaries(ctx context.Context, userID string) ([]GetActiveStaffDisciplinariesRow, error) {
	rows, err := q.db.Query(ctx, getActiveStaffDisciplinaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetActiveStaffDisciplinariesRow
	for rows.Next() {
		var i GetActiveStaffDisciplinariesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Expiry,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.TypeName,
			&i.TypeDescription,
			&i.SelfAssignable,
			&i.PermLimits,
			&i.Additory,
			&i.NeedsApproval,
			&i.MaxExpiry,
			&i.TypeCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStaffMembersForUpdate = `-- name: GetAllStaffMembersForUpdate :many
SELECT user_id, positions, perm_overrides, no_autosync, unaccounted FROM staff_members FOR UPDATE
`

type GetAllStaffMembersForUpdateRow struct {
	UserID        string        `db:"user_id" json:"user_id"`
	Positions     []pgtype.UUID `db:"positions" json:"positions"`
	PermOverrides []string      `db:"perm_overrides" json:"perm_overrides"`
	NoAutosync    bool          `db:"no_autosync" json:"no_autosync"`
	Unaccounted   bool          `db:"unaccounted" json:"unaccounted"`
}

func (q *Queries) GetAllStaffMembersForUpdate(ctx context.Context) ([]GetAllStaffMembersForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getAllStaffMembersForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStaffMembersForUpdateRow
	for rows.Next() {
		var i GetAllStaffMembersForUpdateRow
		if err := rows.Scan(
			&i.UserID,
			&i.Positions,
			&i.PermOverrides,
			&i.NoAutosync,
			&i.Unaccounted,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllStaffPositions = `-- name: GetAllStaffPositions :many
SELECT id, name, role_id, index, perms, corresponding_roles FROM staff_positions
`

type GetAllStaffPositionsRow struct {
	ID                 pgtype.UUID `db:"id" json:"id"`
	Name               string      `db:"name" json:"name"`
	RoleID             string      `db:"role_id" json:"role_id"`
	Index              int32       `db:"index" json:"index"`
	Perms              []string    `db:"perms" json:"perms"`
	CorrespondingRoles []byte      `db:"corresponding_roles" json:"corresponding_roles"`
}

func (q *Queries) GetAllStaffPositions(ctx context.Context) ([]GetAllStaffPositionsRow, error) {
	rows, err := q.db.Query(ctx, getAllStaffPositions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllStaffPositionsRow
	for rows.Next() {
		var i GetAllStaffPositionsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleID,
			&i.Index,
			&i.Perms,
			&i.CorrespondingRoles,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAnalyticsCounts = `-- name: GetAnalyticsCounts :one
SELECT
	(SELECT COUNT(*) FROM bots) AS bots,
	(SELECT COUNT(*) FROM teams) AS teams,
	(SELECT COUNT(*) FROM users) AS users,
	(SELECT COUNT(*) FROM servers) AS servers,
	(SELECT COUNT(*) FROM packs) AS packs
`

type GetAnalyticsCountsRow struct {
	Bots    int64 `db:"bots" json:"bots"`
	Teams   int64 `db:"teams" json:"teams"`
	Users   int64 `db:"users" json:"users"`
	Servers int64 `db:"servers" json:"servers"`
	Packs   int64 `db:"packs" json:"packs"`
}

func (q *Queries) GetAnalyticsCounts(ctx context.Context) (GetAnalyticsCountsRow, error) {
	row := q.db.QueryRow(ctx, getAnalyticsCounts)
	var i GetAnalyticsCountsRow
	err := row.Scan(
		&i.Bots,
		&i.Teams,
		&i.Users,
		&i.Servers,
		&i.Packs,
	)
	return i, err
}

const getAuthChainByToken = `-- name: GetAuthChainByToken :one
SELECT user_id, created_at, state FROM staffpanel__authchain WHERE token = $1
`

type GetAuthChainByTokenRow struct {
	UserID    string             `db:"user_id" json:"user_id"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	State     string             `db:"state" json:"state"`
}

func (q *Queries) GetAuthChainByToken(ctx context.Context, token string) (GetAuthChainByTokenRow, error) {
	row := q.db.QueryRow(ctx, getAuthChainByToken, token)
	var i GetAuthChainByTokenRow
	err := row.Scan(&i.UserID, &i.CreatedAt, &i.State)
	return i, err
}

const getBotsOwnersByIDs = `-- name: GetBotsOwnersByIDs :many
SELECT bot_id, owner, team_owner FROM bots WHERE bot_id = ANY($1::text[])
`

type GetBotsOwnersByIDsRow struct {
	BotID     string      `db:"bot_id" json:"bot_id"`
	Owner     pgtype.Text `db:"owner" json:"owner"`
	TeamOwner pgtype.UUID `db:"team_owner" json:"team_owner"`
}

func (q *Queries) GetBotsOwnersByIDs(ctx context.Context, botIds []string) ([]GetBotsOwnersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getBotsOwnersByIDs, botIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBotsOwnersByIDsRow
	for rows.Next() {
		var i GetBotsOwnersByIDsRow
		if err := rows.Scan(&i.BotID, &i.Owner, &i.TeamOwner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCachedDiscordUsername = `-- name: GetCachedDiscordUsername :one
SELECT username FROM internal_user_cache__discord WHERE id = $1
`

func (q *Queries) GetCachedDiscordUsername(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getCachedDiscordUsername, id)
	var username string
	err := row.Scan(&username)
	return username, err
}

const getModCasesForUser = `-- name: GetModCasesForUser :many
SELECT action, moderator_id, reason, created_at FROM mod_cases
WHERE guild_id = $1 AND user_id = $2
ORDER BY created_at DESC LIMIT 10
`

type GetModCasesForUserParams struct {
	GuildID string `db:"guild_id" json:"guild_id"`
	UserID  string `db:"user_id" json:"user_id"`
}

type GetModCasesForUserRow struct {
	Action      string             `db:"action" json:"action"`
	ModeratorID string             `db:"moderator_id" json:"moderator_id"`
	Reason      string             `db:"reason" json:"reason"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetModCasesForUser(ctx context.Context, arg GetModCasesForUserParams) ([]GetModCasesForUserRow, error) {
	rows, err := q.db.Query(ctx, getModCasesForUser, arg.GuildID, arg.UserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetModCasesForUserRow
	for rows.Next() {
		var i GetModCasesForUserRow
		if err := rows.Scan(
			&i.Action,
			&i.ModeratorID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getNextStaffPositionIndex = `-- name: GetNextStaffPositionIndex :one
SELECT COALESCE(MAX(index), 0) + 1 FROM staff_positions
`

func (q *Queries) GetNextStaffPositionIndex(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getNextStaffPositionIndex)
	var column_1 int32
	err := row.Scan(&column_1)
	return column_1, err
}

const getPendingBotsQueue = `-- name: GetPendingBotsQueue :many
SELECT claimed_by, bot_id, approval_note, short, invite, client_id
FROM bots WHERE type = 'pending' ORDER BY created_at ASC
`

type GetPendingBotsQueueRow struct {
	ClaimedBy    pgtype.Text `db:"claimed_by" json:"claimed_by"`
	BotID        string      `db:"bot_id" json:"bot_id"`
	ApprovalNote string      `db:"approval_note" json:"approval_note"`
	Short        string      `db:"short" json:"short"`
	Invite       string      `db:"invite" json:"invite"`
	ClientID     string      `db:"client_id" json:"client_id"`
}

func (q *Queries) GetPendingBotsQueue(ctx context.Context) ([]GetPendingBotsQueueRow, error) {
	rows, err := q.db.Query(ctx, getPendingBotsQueue)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPendingBotsQueueRow
	for rows.Next() {
		var i GetPendingBotsQueueRow
		if err := rows.Scan(
			&i.ClaimedBy,
			&i.BotID,
			&i.ApprovalNote,
			&i.Short,
			&i.Invite,
			&i.ClientID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPopplioTokenByToken = `-- name: GetPopplioTokenByToken :one
SELECT popplio_token FROM staffpanel__authchain WHERE token = $1
`

func (q *Queries) GetPopplioTokenByToken(ctx context.Context, token string) (string, error) {
	row := q.db.QueryRow(ctx, getPopplioTokenByToken, token)
	var popplio_token string
	err := row.Scan(&popplio_token)
	return popplio_token, err
}

const getRPCMethodCountsForUser = `-- name: GetRPCMethodCountsForUser :many
SELECT method, COUNT(*) FROM rpc_logs WHERE user_id = $1 GROUP BY method
`

type GetRPCMethodCountsForUserRow struct {
	Method string `db:"method" json:"method"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) GetRPCMethodCountsForUser(ctx context.Context, userID string) ([]GetRPCMethodCountsForUserRow, error) {
	rows, err := q.db.Query(ctx, getRPCMethodCountsForUser, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRPCMethodCountsForUserRow
	for rows.Next() {
		var i GetRPCMethodCountsForUserRow
		if err := rows.Scan(&i.Method, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServersTeamOwnersByIDs = `-- name: GetServersTeamOwnersByIDs :many
SELECT server_id, team_owner FROM servers WHERE server_id = ANY($1::text[])
`

type GetServersTeamOwnersByIDsRow struct {
	ServerID  string      `db:"server_id" json:"server_id"`
	TeamOwner pgtype.UUID `db:"team_owner" json:"team_owner"`
}

func (q *Queries) GetServersTeamOwnersByIDs(ctx context.Context, serverIds []string) ([]GetServersTeamOwnersByIDsRow, error) {
	rows, err := q.db.Query(ctx, getServersTeamOwnersByIDs, serverIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServersTeamOwnersByIDsRow
	for rows.Next() {
		var i GetServersTeamOwnersByIDsRow
		if err := rows.Scan(&i.ServerID, &i.TeamOwner); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffDisciplinaries = `-- name: GetStaffDisciplinaries :many
SELECT d.id, d.created_at, EXTRACT(epoch FROM d.expiry) AS expiry, d.title, d.description, d.type,
	t.name AS type_name, t.description AS type_description, t.self_assignable, t.perm_limits, t.additory, t.needs_approval,
	EXTRACT(epoch FROM t.max_expiry) AS max_expiry, t.created_at AS type_created_at
FROM staff_disciplinary d LEFT JOIN staff_disciplinary_types t ON t.id = d.type
WHERE d.user_id = $1
`

type GetStaffDisciplinariesRow struct {
	ID              pgtype.UUID        `db:"id" json:"id"`
	CreatedAt       pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Expiry          pgtype.Numeric     `db:"expiry" json:"expiry"`
	Title           string             `db:"title" json:"title"`
	Description     string             `db:"description" json:"description"`
	Type            string             `db:"type" json:"type"`
	TypeName        pgtype.Text        `db:"type_name" json:"type_name"`
	TypeDescription pgtype.Text        `db:"type_description" json:"type_description"`
	SelfAssignable  pgtype.Bool        `db:"self_assignable" json:"self_assignable"`
	PermLimits      []string           `db:"perm_limits" json:"perm_limits"`
	Additory        pgtype.Bool        `db:"additory" json:"additory"`
	NeedsApproval   pgtype.Bool        `db:"needs_approval" json:"needs_approval"`
	MaxExpiry       pgtype.Numeric     `db:"max_expiry" json:"max_expiry"`
	TypeCreatedAt   pgtype.Timestamptz `db:"type_created_at" json:"type_created_at"`
}

func (q *Queries) GetStaffDisciplinaries(ctx context.Context, userID string) ([]GetStaffDisciplinariesRow, error) {
	rows, err := q.db.Query(ctx, getStaffDisciplinaries, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffDisciplinariesRow
	for rows.Next() {
		var i GetStaffDisciplinariesRow
		if err := rows.Scan(
			&i.ID,
			&i.CreatedAt,
			&i.Expiry,
			&i.Title,
			&i.Description,
			&i.Type,
			&i.TypeName,
			&i.TypeDescription,
			&i.SelfAssignable,
			&i.PermLimits,
			&i.Additory,
			&i.NeedsApproval,
			&i.MaxExpiry,
			&i.TypeCreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffMemberRaw = `-- name: GetStaffMemberRaw :one
SELECT positions, perm_overrides, no_autosync, unaccounted, mfa_verified, created_at FROM staff_members WHERE user_id = $1
`

type GetStaffMemberRawRow struct {
	Positions     []pgtype.UUID      `db:"positions" json:"positions"`
	PermOverrides []string           `db:"perm_overrides" json:"perm_overrides"`
	NoAutosync    bool               `db:"no_autosync" json:"no_autosync"`
	Unaccounted   bool               `db:"unaccounted" json:"unaccounted"`
	MfaVerified   bool               `db:"mfa_verified" json:"mfa_verified"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStaffMemberRaw(ctx context.Context, userID string) (GetStaffMemberRawRow, error) {
	row := q.db.QueryRow(ctx, getStaffMemberRaw, userID)
	var i GetStaffMemberRawRow
	err := row.Scan(
		&i.Positions,
		&i.PermOverrides,
		&i.NoAutosync,
		&i.Unaccounted,
		&i.MfaVerified,
		&i.CreatedAt,
	)
	return i, err
}

const getStaffPositionsAndBotFlag = `-- name: GetStaffPositionsAndBotFlag :one
SELECT sm.positions, COALESCE(iuc.bot, false) AS bot
FROM staff_members sm
LEFT JOIN internal_user_cache__discord iuc ON iuc.id = sm.user_id
WHERE sm.user_id = $1
`

type GetStaffPositionsAndBotFlagRow struct {
	Positions []pgtype.UUID `db:"positions" json:"positions"`
	Bot       bool          `db:"bot" json:"bot"`
}

func (q *Queries) GetStaffPositionsAndBotFlag(ctx context.Context, userID string) (GetStaffPositionsAndBotFlagRow, error) {
	row := q.db.QueryRow(ctx, getStaffPositionsAndBotFlag, userID)
	var i GetStaffPositionsAndBotFlagRow
	err := row.Scan(&i.Positions, &i.Bot)
	return i, err
}

const getStaffPositionsByIDs = `-- name: GetStaffPositionsByIDs :many
SELECT id, name, role_id, perms, corresponding_roles, icon, index, created_at FROM staff_positions WHERE id = ANY($1::uuid[])
`

type GetStaffPositionsByIDsRow struct {
	ID                 pgtype.UUID        `db:"id" json:"id"`
	Name               string             `db:"name" json:"name"`
	RoleID             string             `db:"role_id" json:"role_id"`
	Perms              []string           `db:"perms" json:"perms"`
	CorrespondingRoles []byte             `db:"corresponding_roles" json:"corresponding_roles"`
	Icon               string             `db:"icon" json:"icon"`
	Index              int32              `db:"index" json:"index"`
	CreatedAt          pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStaffPositionsByIDs(ctx context.Context, ids []pgtype.UUID) ([]GetStaffPositionsByIDsRow, error) {
	rows, err := q.db.Query(ctx, getStaffPositionsByIDs, ids)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffPositionsByIDsRow
	for rows.Next() {
		var i GetStaffPositionsByIDsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleID,
			&i.Perms,
			&i.CorrespondingRoles,
			&i.Icon,
			&i.Index,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffRoleHolderCounts = `-- name: GetStaffRoleHolderCounts :many
SELECT sp.id::text, count(sm.user_id)
FROM staff_positions sp
LEFT JOIN staff_members sm ON sp.id = ANY(sm.positions)
GROUP BY sp.id
`

type GetStaffRoleHolderCountsRow struct {
	SpID  string `db:"sp_id" json:"sp_id"`
	Count int64  `db:"count" json:"count"`
}

func (q *Queries) GetStaffRoleHolderCounts(ctx context.Context) ([]GetStaffRoleHolderCountsRow, error) {
	rows, err := q.db.Query(ctx, getStaffRoleHolderCounts)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffRoleHolderCountsRow
	for rows.Next() {
		var i GetStaffRoleHolderCountsRow
		if err := rows.Scan(&i.SpID, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembersByTeamIDs = `-- name: GetTeamMembersByTeamIDs :many
SELECT team_id, user_id, mentionable FROM team_members WHERE team_id = ANY($1::uuid[])
`

type GetTeamMembersByTeamIDsRow struct {
	TeamID      pgtype.UUID `db:"team_id" json:"team_id"`
	UserID      string      `db:"user_id" json:"user_id"`
	Mentionable bool        `db:"mentionable" json:"mentionable"`
}

func (q *Queries) GetTeamMembersByTeamIDs(ctx context.Context, teamIds []pgtype.UUID) ([]GetTeamMembersByTeamIDsRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembersByTeamIDs, teamIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersByTeamIDsRow
	for rows.Next() {
		var i GetTeamMembersByTeamIDsRow
		if err := rows.Scan(&i.TeamID, &i.UserID, &i.Mentionable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembersMentionable = `-- name: GetTeamMembersMentionable :many
SELECT user_id, mentionable FROM team_members WHERE team_id = $1
`

type GetTeamMembersMentionableRow struct {
	UserID      string `db:"user_id" json:"user_id"`
	Mentionable bool   `db:"mentionable" json:"mentionable"`
}

func (q *Queries) GetTeamMembersMentionable(ctx context.Context, teamID pgtype.UUID) ([]GetTeamMembersMentionableRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembersMentionable, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersMentionableRow
	for rows.Next() {
		var i GetTeamMembersMentionableRow
		if err := rows.Scan(&i.UserID, &i.Mentionable); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopReviewers = `-- name: GetTopReviewers :many
SELECT user_id, approved_count, denied_count, total_count FROM (
	SELECT rpc.user_id,
		SUM(CASE WHEN rpc.method = 'Approve' THEN 1 ELSE 0 END) AS approved_count,
		SUM(CASE WHEN rpc.method = 'Deny' THEN 1 ELSE 0 END) AS denied_count,
		SUM(CASE WHEN rpc.method IN ('Approve', 'Deny') THEN 1 ELSE 0 END) AS total_count
	FROM rpc_logs rpc
	LEFT JOIN staff_members sm ON rpc.user_id = sm.user_id
	WHERE rpc.method IN ('Approve', 'Deny') AND sm.user_id IS NOT NULL
	GROUP BY rpc.user_id
) AS subquery
WHERE total_count > 0
ORDER BY total_count DESC
LIMIT $1
`

type GetTopReviewersRow struct {
	UserID        string `db:"user_id" json:"user_id"`
	ApprovedCount int64  `db:"approved_count" json:"approved_count"`
	DeniedCount   int64  `db:"denied_count" json:"denied_count"`
	TotalCount    int64  `db:"total_count" json:"total_count"`
}

func (q *Queries) GetTopReviewers(ctx context.Context, limit int32) ([]GetTopReviewersRow, error) {
	rows, err := q.db.Query(ctx, getTopReviewers, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopReviewersRow
	for rows.Next() {
		var i GetTopReviewersRow
		if err := rows.Scan(
			&i.UserID,
			&i.ApprovedCount,
			&i.DeniedCount,
			&i.TotalCount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserOwnedEntities = `-- name: GetUserOwnedEntities :many
SELECT b.bot_id as id, b.type, 'bot' as entity
FROM bots b
WHERE b.team_owner IN (SELECT tm.team_id FROM team_members tm WHERE tm.user_id = $1::text)
   OR b.owner = $1::text

UNION

SELECT s.server_id as id, s.type, 'server' as entity
FROM servers s
WHERE s.team_owner IN (SELECT tm.team_id FROM team_members tm WHERE tm.user_id = $1::text)

UNION

SELECT p.url as id, 'pack' as type, 'pack' as entity
FROM packs p
WHERE p.owner = $1::text
`

type GetUserOwnedEntitiesRow struct {
	ID     string `db:"id" json:"id"`
	Type   string `db:"type" json:"type"`
	Entity string `db:"entity" json:"entity"`
}

func (q *Queries) GetUserOwnedEntities(ctx context.Context, userID string) ([]GetUserOwnedEntitiesRow, error) {
	rows, err := q.db.Query(ctx, getUserOwnedEntities, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserOwnedEntitiesRow
	for rows.Next() {
		var i GetUserOwnedEntitiesRow
		if err := rows.Scan(&i.ID, &i.Type, &i.Entity); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAuthChain = `-- name: InsertAuthChain :exec
INSERT INTO staffpanel__authchain (user_id, token, popplio_token, state) VALUES ($1, $2, $3, $4)
`

type InsertAuthChainParams struct {
	UserID       string `db:"user_id" json:"user_id"`
	Token        string `db:"token" json:"token"`
	PopplioToken string `db:"popplio_token" json:"popplio_token"`
	State        string `db:"state" json:"state"`
}

func (q *Queries) InsertAuthChain(ctx context.Context, arg InsertAuthChainParams) error {
	_, err := q.db.Exec(ctx, insertAuthChain,
		arg.UserID,
		arg.Token,
		arg.PopplioToken,
		arg.State,
	)
	return err
}

const insertModCase = `-- name: InsertModCase :exec
INSERT INTO mod_cases (guild_id, user_id, moderator_id, action, reason) VALUES ($1, $2, $3, $4, $5)
`

type InsertModCaseParams struct {
	GuildID     string `db:"guild_id" json:"guild_id"`
	UserID      string `db:"user_id" json:"user_id"`
	ModeratorID string `db:"moderator_id" json:"moderator_id"`
	Action      string `db:"action" json:"action"`
	Reason      string `db:"reason" json:"reason"`
}

func (q *Queries) InsertModCase(ctx context.Context, arg InsertModCaseParams) error {
	_, err := q.db.Exec(ctx, insertModCase,
		arg.GuildID,
		arg.UserID,
		arg.ModeratorID,
		arg.Action,
		arg.Reason,
	)
	return err
}

const insertRPCLog = `-- name: InsertRPCLog :one
INSERT INTO rpc_logs (method, user_id, data) VALUES ($1, $2, $3) RETURNING id
`

type InsertRPCLogParams struct {
	Method string         `db:"method" json:"method"`
	UserID string         `db:"user_id" json:"user_id"`
	Data   map[string]any `db:"data" json:"data"`
}

func (q *Queries) InsertRPCLog(ctx context.Context, arg InsertRPCLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertRPCLog, arg.Method, arg.UserID, arg.Data)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const insertStaffGeneralLog = `-- name: InsertStaffGeneralLog :exec
INSERT INTO staff_general_logs (user_id, action, data) VALUES ($1, $2, $3)
`

type InsertStaffGeneralLogParams struct {
	UserID string         `db:"user_id" json:"user_id"`
	Action string         `db:"action" json:"action"`
	Data   map[string]any `db:"data" json:"data"`
}

func (q *Queries) InsertStaffGeneralLog(ctx context.Context, arg InsertStaffGeneralLogParams) error {
	_, err := q.db.Exec(ctx, insertStaffGeneralLog, arg.UserID, arg.Action, arg.Data)
	return err
}

const insertStaffMemberPositions = `-- name: InsertStaffMemberPositions :exec
INSERT INTO staff_members (user_id, positions) VALUES ($1, $2)
`

type InsertStaffMemberPositionsParams struct {
	UserID    string        `db:"user_id" json:"user_id"`
	Positions []pgtype.UUID `db:"positions" json:"positions"`
}

func (q *Queries) InsertStaffMemberPositions(ctx context.Context, arg InsertStaffMemberPositionsParams) error {
	_, err := q.db.Exec(ctx, insertStaffMemberPositions, arg.UserID, arg.Positions)
	return err
}

const insertStaffPosition = `-- name: InsertStaffPosition :exec
INSERT INTO staff_positions (name, role_id, perms, index) VALUES ($1, $2, '{}', $3)
`

type InsertStaffPositionParams struct {
	Name   string `db:"name" json:"name"`
	RoleID string `db:"role_id" json:"role_id"`
	Index  int32  `db:"index" json:"index"`
}

func (q *Queries) InsertStaffPosition(ctx context.Context, arg InsertStaffPositionParams) error {
	_, err := q.db.Exec(ctx, insertStaffPosition, arg.Name, arg.RoleID, arg.Index)
	return err
}

const insertUserWithToken = `-- name: InsertUserWithToken :exec
INSERT INTO users (user_id, api_token) VALUES ($1, $2)
`

type InsertUserWithTokenParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	ApiToken string `db:"api_token" json:"api_token"`
}

func (q *Queries) InsertUserWithToken(ctx context.Context, arg InsertUserWithTokenParams) error {
	_, err := q.db.Exec(ctx, insertUserWithToken, arg.UserID, arg.ApiToken)
	return err
}

const listRPCLogs = `-- name: ListRPCLogs :many
SELECT id, user_id, method, data, state, created_at FROM rpc_logs ORDER BY created_at DESC
`

func (q *Queries) ListRPCLogs(ctx context.Context) ([]RpcLog, error) {
	rows, err := q.db.Query(ctx, listRPCLogs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RpcLog
	for rows.Next() {
		var i RpcLog
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Method,
			&i.Data,
			&i.State,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listStaffRolesOrdered = `-- name: ListStaffRolesOrdered :many
SELECT id::text, name, role_id, index, perms FROM staff_positions ORDER BY index
`

type ListStaffRolesOrderedRow struct {
	ID     string   `db:"id" json:"id"`
	Name   string   `db:"name" json:"name"`
	RoleID string   `db:"role_id" json:"role_id"`
	Index  int32    `db:"index" json:"index"`
	Perms  []string `db:"perms" json:"perms"`
}

func (q *Queries) ListStaffRolesOrdered(ctx context.Context) ([]ListStaffRolesOrderedRow, error) {
	rows, err := q.db.Query(ctx, listStaffRolesOrdered)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListStaffRolesOrderedRow
	for rows.Next() {
		var i ListStaffRolesOrderedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.RoleID,
			&i.Index,
			&i.Perms,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const lookupStaffRole = `-- name: LookupStaffRole :one
SELECT id::text, name, role_id, index, perms
FROM staff_positions
WHERE lower(name) = lower($1) OR role_id = $2 OR id::text = $2
LIMIT 1
`

type LookupStaffRoleParams struct {
	Input  string `db:"input" json:"input"`
	RoleID string `db:"role_id" json:"role_id"`
}

type LookupStaffRoleRow struct {
	ID     string   `db:"id" json:"id"`
	Name   string   `db:"name" json:"name"`
	RoleID string   `db:"role_id" json:"role_id"`
	Index  int32    `db:"index" json:"index"`
	Perms  []string `db:"perms" json:"perms"`
}

func (q *Queries) LookupStaffRole(ctx context.Context, arg LookupStaffRoleParams) (LookupStaffRoleRow, error) {
	row := q.db.QueryRow(ctx, lookupStaffRole, arg.Input, arg.RoleID)
	var i LookupStaffRoleRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.RoleID,
		&i.Index,
		&i.Perms,
	)
	return i, err
}

const markStaffMemberUnaccounted = `-- name: MarkStaffMemberUnaccounted :exec
UPDATE staff_members SET positions = '{}', unaccounted = true WHERE user_id = $1
`

func (q *Queries) MarkStaffMemberUnaccounted(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, markStaffMemberUnaccounted, userID)
	return err
}

const removeStaffMemberPosition = `-- name: RemoveStaffMemberPosition :exec
UPDATE staff_members SET positions = array_remove(positions, $1) WHERE user_id = $2
`

type RemoveStaffMemberPositionParams struct {
	ArrayRemove interface{} `db:"array_remove" json:"array_remove"`
	UserID      string      `db:"user_id" json:"user_id"`
}

func (q *Queries) RemoveStaffMemberPosition(ctx context.Context, arg RemoveStaffMemberPositionParams) error {
	_, err := q.db.Exec(ctx, removeStaffMemberPosition, arg.ArrayRemove, arg.UserID)
	return err
}

const renameStaffPosition = `-- name: RenameStaffPosition :exec
UPDATE staff_positions SET name = $1 WHERE id = $2
`

type RenameStaffPositionParams struct {
	Name string      `db:"name" json:"name"`
	ID   pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) RenameStaffPosition(ctx context.Context, arg RenameStaffPositionParams) error {
	_, err := q.db.Exec(ctx, renameStaffPosition, arg.Name, arg.ID)
	return err
}

const touchAuthChainSeen = `-- name: TouchAuthChainSeen :exec
UPDATE staffpanel__authchain SET last_seen_at = NOW() WHERE token = $1
`

func (q *Queries) TouchAuthChainSeen(ctx context.Context, token string) error {
	_, err := q.db.Exec(ctx, touchAuthChainSeen, token)
	return err
}

const updateRPCLogState = `-- name: UpdateRPCLogState :exec
UPDATE rpc_logs SET state = $1 WHERE id = $2
`

type UpdateRPCLogStateParams struct {
	State string      `db:"state" json:"state"`
	ID    pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateRPCLogState(ctx context.Context, arg UpdateRPCLogStateParams) error {
	_, err := q.db.Exec(ctx, updateRPCLogState, arg.State, arg.ID)
	return err
}

const updateStaffMemberPermOverrides = `-- name: UpdateStaffMemberPermOverrides :execrows
UPDATE staff_members SET perm_overrides = $1 WHERE user_id = $2
`

type UpdateStaffMemberPermOverridesParams struct {
	PermOverrides []string `db:"perm_overrides" json:"perm_overrides"`
	UserID        string   `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateStaffMemberPermOverrides(ctx context.Context, arg UpdateStaffMemberPermOverridesParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStaffMemberPermOverrides, arg.PermOverrides, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateStaffMemberPositions = `-- name: UpdateStaffMemberPositions :exec
UPDATE staff_members SET positions = $1, unaccounted = false WHERE user_id = $2
`

type UpdateStaffMemberPositionsParams struct {
	Positions []pgtype.UUID `db:"positions" json:"positions"`
	UserID    string        `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateStaffMemberPositions(ctx context.Context, arg UpdateStaffMemberPositionsParams) error {
	_, err := q.db.Exec(ctx, updateStaffMemberPositions, arg.Positions, arg.UserID)
	return err
}

const updateStaffPositionPerms = `-- name: UpdateStaffPositionPerms :execrows
UPDATE staff_positions SET perms = $1 WHERE id = $2
`

type UpdateStaffPositionPermsParams struct {
	Perms []string    `db:"perms" json:"perms"`
	ID    pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) UpdateStaffPositionPerms(ctx context.Context, arg UpdateStaffPositionPermsParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateStaffPositionPerms, arg.Perms, arg.ID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertEntityBadge = `-- name: UpsertEntityBadge :exec
INSERT INTO entity_badges (target_type, target_id, badge_id, reason, awarded_by)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (target_type, target_id, badge_id) DO UPDATE SET reason = $4, awarded_by = $5, created_at = NOW()
`

type UpsertEntityBadgeParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
	BadgeID    string `db:"badge_id" json:"badge_id"`
	Reason     string `db:"reason" json:"reason"`
	AwardedBy  string `db:"awarded_by" json:"awarded_by"`
}

func (q *Queries) UpsertEntityBadge(ctx context.Context, arg UpsertEntityBadgeParams) error {
	_, err := q.db.Exec(ctx, upsertEntityBadge,
		arg.TargetType,
		arg.TargetID,
		arg.BadgeID,
		arg.Reason,
		arg.AwardedBy,
	)
	return err
}
