// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: badges.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBadgeByID = `-- name: CountBadgeByID :one
SELECT EXISTS(SELECT 1 FROM badges WHERE id = $1)
`

func (q *Queries) CountBadgeByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countBadgeByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteBadge = `-- name: DeleteBadge :exec
DELETE FROM badges WHERE id = $1
`

func (q *Queries) DeleteBadge(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteBadge, id)
	return err
}

const getEntityBadges = `-- name: GetEntityBadges :many
SELECT eb.reason, eb.awarded_by, eb.created_at,
       b.id AS badge_id, b.name, b.description, b.icon, b.color, b.target_types
FROM entity_badges eb
INNER JOIN badges b ON b.id = eb.badge_id
WHERE eb.target_type = $1 AND eb.target_id = $2
ORDER BY eb.created_at ASC
`

type GetEntityBadgesParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

type GetEntityBadgesRow struct {
	Reason      string             `db:"reason" json:"reason"`
	AwardedBy   string             `db:"awarded_by" json:"awarded_by"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	BadgeID     string             `db:"badge_id" json:"badge_id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	Icon        string             `db:"icon" json:"icon"`
	Color       string             `db:"color" json:"color"`
	TargetTypes []string           `db:"target_types" json:"target_types"`
}

func (q *Queries) GetEntityBadges(ctx context.Context, arg GetEntityBadgesParams) ([]GetEntityBadgesRow, error) {
	rows, err := q.db.Query(ctx, getEntityBadges, arg.TargetType, arg.TargetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityBadgesRow
	for rows.Next() {
		var i GetEntityBadgesRow
		if err := rows.Scan(
			&i.Reason,
			&i.AwardedBy,
			&i.CreatedAt,
			&i.BadgeID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.TargetTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBadge = `-- name: InsertBadge :exec
INSERT INTO badges (id, name, description, icon, color, target_types, created_by, updated_by) VALUES ($1, $2, $3, $4, $5, $6, $7, $7)
`

type InsertBadgeParams struct {
	ID          string   `db:"id" json:"id"`
	Name        string   `db:"name" json:"name"`
	Description string   `db:"description" json:"description"`
	Icon        string   `db:"icon" json:"icon"`
	Color       string   `db:"color" json:"color"`
	TargetTypes []string `db:"target_types" json:"target_types"`
	CreatedBy   string   `db:"created_by" json:"created_by"`
}

func (q *Queries) InsertBadge(ctx context.Context, arg InsertBadgeParams) error {
	_, err := q.db.Exec(ctx, insertBadge,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.TargetTypes,
		arg.CreatedBy,
	)
	return err
}

const listBadges = `-- name: ListBadges :many

SELECT id, name, description, icon, color, target_types, created_at, created_by, last_updated, updated_by
FROM badges ORDER BY created_at DESC
`

// The badge catalog itself (panel ops_badges.go).
func (q *Queries) ListBadges(ctx context.Context) ([]Badge, error) {
	rows, err := q.db.Query(ctx, listBadges)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Badge
	for rows.Next() {
		var i Badge
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Icon,
			&i.Color,
			&i.TargetTypes,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.LastUpdated,
			&i.UpdatedBy,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBadge = `-- name: UpdateBadge :exec
UPDATE badges SET name = $1, description = $2, icon = $3, color = $4, target_types = $5, last_updated = NOW(), updated_by = $6 WHERE id = $7
`

type UpdateBadgeParams struct {
	Name        string   `db:"name" json:"name"`
	Description string   `db:"description" json:"description"`
	Icon        string   `db:"icon" json:"icon"`
	Color       string   `db:"color" json:"color"`
	TargetTypes []string `db:"target_types" json:"target_types"`
	UpdatedBy   string   `db:"updated_by" json:"updated_by"`
	ID          string   `db:"id" json:"id"`
}

func (q *Queries) UpdateBadge(ctx context.Context, arg UpdateBadgeParams) error {
	_, err := q.db.Exec(ctx, updateBadge,
		arg.Name,
		arg.Description,
		arg.Icon,
		arg.Color,
		arg.TargetTypes,
		arg.UpdatedBy,
		arg.ID,
	)
	return err
}
