// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: blogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBlogByItag = `-- name: CountBlogByItag :one
SELECT EXISTS(SELECT 1 FROM blogs WHERE itag = $1)
`

func (q *Queries) CountBlogByItag(ctx context.Context, itag pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, countBlogByItag, itag)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteBlogByItag = `-- name: DeleteBlogByItag :exec
DELETE FROM blogs WHERE itag = $1
`

func (q *Queries) DeleteBlogByItag(ctx context.Context, itag pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteBlogByItag, itag)
	return err
}

const getBlogDraftByItag = `-- name: GetBlogDraftByItag :one
SELECT draft FROM blogs WHERE itag = $1
`

func (q *Queries) GetBlogDraftByItag(ctx context.Context, itag pgtype.UUID) (bool, error) {
	row := q.db.QueryRow(ctx, getBlogDraftByItag, itag)
	var draft bool
	err := row.Scan(&draft)
	return draft, err
}

const getBlogList = `-- name: GetBlogList :many
SELECT slug, title, description, user_id, created_at, draft, tags
FROM blogs
WHERE draft = false
ORDER BY created_at DESC
`

type GetBlogListRow struct {
	Slug        string             `db:"slug" json:"slug"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	UserID      string             `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Draft       bool               `db:"draft" json:"draft"`
	Tags        []string           `db:"tags" json:"tags"`
}

func (q *Queries) GetBlogList(ctx context.Context) ([]GetBlogListRow, error) {
	rows, err := q.db.Query(ctx, getBlogList)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBlogListRow
	for rows.Next() {
		var i GetBlogListRow
		if err := rows.Scan(
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.CreatedAt,
			&i.Draft,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBlogPost = `-- name: GetBlogPost :one
SELECT slug, title, description, user_id, created_at, content, draft, tags
FROM blogs
WHERE slug = $1
`

type GetBlogPostRow struct {
	Slug        string             `db:"slug" json:"slug"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	UserID      string             `db:"user_id" json:"user_id"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Content     string             `db:"content" json:"content"`
	Draft       bool               `db:"draft" json:"draft"`
	Tags        []string           `db:"tags" json:"tags"`
}

func (q *Queries) GetBlogPost(ctx context.Context, slug string) (GetBlogPostRow, error) {
	row := q.db.QueryRow(ctx, getBlogPost, slug)
	var i GetBlogPostRow
	err := row.Scan(
		&i.Slug,
		&i.Title,
		&i.Description,
		&i.UserID,
		&i.CreatedAt,
		&i.Content,
		&i.Draft,
		&i.Tags,
	)
	return i, err
}

const getBlogSEO = `-- name: GetBlogSEO :one
SELECT title, description FROM blogs WHERE slug = $1
`

type GetBlogSEORow struct {
	Title       string `db:"title" json:"title"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) GetBlogSEO(ctx context.Context, slug string) (GetBlogSEORow, error) {
	row := q.db.QueryRow(ctx, getBlogSEO, slug)
	var i GetBlogSEORow
	err := row.Scan(&i.Title, &i.Description)
	return i, err
}

const insertBlogEntry = `-- name: InsertBlogEntry :exec
INSERT INTO blogs (slug, title, description, content, tags, user_id) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBlogEntryParams struct {
	Slug        string   `db:"slug" json:"slug"`
	Title       string   `db:"title" json:"title"`
	Description string   `db:"description" json:"description"`
	Content     string   `db:"content" json:"content"`
	Tags        []string `db:"tags" json:"tags"`
	UserID      string   `db:"user_id" json:"user_id"`
}

func (q *Queries) InsertBlogEntry(ctx context.Context, arg InsertBlogEntryParams) error {
	_, err := q.db.Exec(ctx, insertBlogEntry,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Tags,
		arg.UserID,
	)
	return err
}

const listBlogEntriesFull = `-- name: ListBlogEntriesFull :many

SELECT itag, slug, title, description, user_id, content, created_at, draft, tags
FROM blogs ORDER BY created_at DESC
`

type ListBlogEntriesFullRow struct {
	Itag        pgtype.UUID        `db:"itag" json:"itag"`
	Slug        string             `db:"slug" json:"slug"`
	Title       string             `db:"title" json:"title"`
	Description string             `db:"description" json:"description"`
	UserID      string             `db:"user_id" json:"user_id"`
	Content     string             `db:"content" json:"content"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Draft       bool               `db:"draft" json:"draft"`
	Tags        []string           `db:"tags" json:"tags"`
}

// Panel blog CRUD (arcadia/panel ops_content.go) sees drafts too, which is
// why it can't reuse GetBlogList above.
func (q *Queries) ListBlogEntriesFull(ctx context.Context) ([]ListBlogEntriesFullRow, error) {
	rows, err := q.db.Query(ctx, listBlogEntriesFull)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBlogEntriesFullRow
	for rows.Next() {
		var i ListBlogEntriesFullRow
		if err := rows.Scan(
			&i.Itag,
			&i.Slug,
			&i.Title,
			&i.Description,
			&i.UserID,
			&i.Content,
			&i.CreatedAt,
			&i.Draft,
			&i.Tags,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateBlogEntry = `-- name: UpdateBlogEntry :exec
UPDATE blogs SET slug = $2, title = $3, description = $4, content = $5, tags = $6, draft = $7 WHERE itag = $1
`

type UpdateBlogEntryParams struct {
	Itag        pgtype.UUID `db:"itag" json:"itag"`
	Slug        string      `db:"slug" json:"slug"`
	Title       string      `db:"title" json:"title"`
	Description string      `db:"description" json:"description"`
	Content     string      `db:"content" json:"content"`
	Tags        []string    `db:"tags" json:"tags"`
	Draft       bool        `db:"draft" json:"draft"`
}

func (q *Queries) UpdateBlogEntry(ctx context.Context, arg UpdateBlogEntryParams) error {
	_, err := q.db.Exec(ctx, updateBlogEntry,
		arg.Itag,
		arg.Slug,
		arg.Title,
		arg.Description,
		arg.Content,
		arg.Tags,
		arg.Draft,
	)
	return err
}
