// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: bots.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"popplio/validators/timex"
)

const appendBotUniqueClick = `-- name: AppendBotUniqueClick :exec
UPDATE bots SET unique_clicks = array_append(unique_clicks, $1) WHERE bot_id = $2
`

type AppendBotUniqueClickParams struct {
	ArrayAppend interface{} `db:"array_append" json:"array_append"`
	BotID       string      `db:"bot_id" json:"bot_id"`
}

func (q *Queries) AppendBotUniqueClick(ctx context.Context, arg AppendBotUniqueClickParams) error {
	_, err := q.db.Exec(ctx, appendBotUniqueClick, arg.ArrayAppend, arg.BotID)
	return err
}

const approveBot = `-- name: ApproveBot :exec
UPDATE bots SET type = 'approved', claimed_by = NULL WHERE bot_id = $1
`

func (q *Queries) ApproveBot(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, approveBot, botID)
	return err
}

const botQueuePending = `-- name: BotQueuePending :many

SELECT bot_id, client_id, last_claimed, claimed_by, type, approval_note, short,
       invite, approximate_votes, shards, library, invite_clicks, clicks, servers,
       moderation_flagged, moderation_categories
FROM bots WHERE type = 'pending' OR type = 'claimed' ORDER BY created_at
`

type BotQueuePendingRow struct {
	BotID                string             `db:"bot_id" json:"bot_id"`
	ClientID             string             `db:"client_id" json:"client_id"`
	LastClaimed          pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
	ClaimedBy            pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	Type                 string             `db:"type" json:"type"`
	ApprovalNote         string             `db:"approval_note" json:"approval_note"`
	Short                string             `db:"short" json:"short"`
	Invite               string             `db:"invite" json:"invite"`
	ApproximateVotes     int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards               int32              `db:"shards" json:"shards"`
	Library              string             `db:"library" json:"library"`
	InviteClicks         int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks               int32              `db:"clicks" json:"clicks"`
	Servers              int32              `db:"servers" json:"servers"`
	ModerationFlagged    bool               `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string           `db:"moderation_categories" json:"moderation_categories"`
}

// Panel bot review queue and search (arcadia/panel ops_queue.go, ops_search.go).
func (q *Queries) BotQueuePending(ctx context.Context) ([]BotQueuePendingRow, error) {
	rows, err := q.db.Query(ctx, botQueuePending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BotQueuePendingRow
	for rows.Next() {
		var i BotQueuePendingRow
		if err := rows.Scan(
			&i.BotID,
			&i.ClientID,
			&i.LastClaimed,
			&i.ClaimedBy,
			&i.Type,
			&i.ApprovalNote,
			&i.Short,
			&i.Invite,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.ModerationFlagged,
			&i.ModerationCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const certifyBot = `-- name: CertifyBot :exec
UPDATE bots SET type = 'certified' WHERE bot_id = $1
`

func (q *Queries) CertifyBot(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, certifyBot, botID)
	return err
}

const checkBotHasUniqueClick = `-- name: CheckBotHasUniqueClick :one
SELECT $1::text = ANY(unique_clicks) FROM bots WHERE bot_id = $2::text
`

type CheckBotHasUniqueClickParams struct {
	HashedIp string `db:"hashed_ip" json:"hashed_ip"`
	BotID    string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) CheckBotHasUniqueClick(ctx context.Context, arg CheckBotHasUniqueClickParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkBotHasUniqueClick, arg.HashedIp, arg.BotID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const clearBotFeaturedUntil = `-- name: ClearBotFeaturedUntil :exec
UPDATE bots SET featured_until = NULL WHERE bot_id = $1
`

func (q *Queries) ClearBotFeaturedUntil(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, clearBotFeaturedUntil, botID)
	return err
}

const clearBotSpotlightedUntil = `-- name: ClearBotSpotlightedUntil :exec
UPDATE bots SET spotlighted_until = NULL WHERE bot_id = $1
`

func (q *Queries) ClearBotSpotlightedUntil(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, clearBotSpotlightedUntil, botID)
	return err
}

const countBots = `-- name: CountBots :one
SELECT COUNT(*) FROM bots
`

func (q *Queries) CountBots(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countBots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTrendingBots = `-- name: CountTrendingBots :one
SELECT COUNT(*) FROM bots
WHERE (type = 'approved' OR type = 'certified') AND bot_id IN (
	SELECT target_id FROM entity_votes
	WHERE target_type = 'bot' AND void = false AND created_at > now() - interval '7 days'
	GROUP BY target_id
)
`

func (q *Queries) CountTrendingBots(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrendingBots)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteBotByID = `-- name: DeleteBotByID :exec
DELETE FROM bots WHERE bot_id = $1
`

func (q *Queries) DeleteBotByID(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, deleteBotByID, botID)
	return err
}

const deleteBotChangelog = `-- name: DeleteBotChangelog :execrows
DELETE FROM bot_changelogs WHERE id = $1 AND bot_id = $2
`

type DeleteBotChangelogParams struct {
	ID    string `db:"id" json:"id"`
	BotID string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) DeleteBotChangelog(ctx context.Context, arg DeleteBotChangelogParams) (int64, error) {
	result, err := q.db.Exec(ctx, deleteBotChangelog, arg.ID, arg.BotID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const deleteBotCommands = `-- name: DeleteBotCommands :exec
DELETE FROM bot_commands WHERE bot_id = $1
`

func (q *Queries) DeleteBotCommands(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, deleteBotCommands, botID)
	return err
}

const denyBot = `-- name: DenyBot :exec
UPDATE bots SET type = 'denied', claimed_by = NULL WHERE bot_id = $1
`

func (q *Queries) DenyBot(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, denyBot, botID)
	return err
}

const fixNoneClaimedBots = `-- name: FixNoneClaimedBots :exec
UPDATE bots SET claimed_by = NULL, type = 'pending' WHERE LOWER(claimed_by) = 'none'
`

func (q *Queries) FixNoneClaimedBots(ctx context.Context) error {
	_, err := q.db.Exec(ctx, fixNoneClaimedBots)
	return err
}

const getAllBotIDs = `-- name: GetAllBotIDs :many
SELECT bot_id FROM bots
`

func (q *Queries) GetAllBotIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllBotIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotByID = `-- name: GetBotByID :one
SELECT itag, bot_id, client_id, extra_links, tags, prefix, owner, short, library, nsfw, premium, last_stats_post, last_japi_update, servers, shards, shard_list, users, approximate_votes, clicks, invite_clicks, invite, type, vanity_ref, vote_banned, start_premium_period, premium_period_length, cert_reason, uptime, total_uptime, uptime_last_checked, approval_note, created_at, claimed_by, updated_at, last_claimed, team_owner, captcha_opt_out, self_status, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until, moderation_flagged, moderation_categories
FROM bots
WHERE bot_id = $1
`

type GetBotByIDRow struct {
	Itag                 pgtype.UUID        `db:"itag" json:"itag"`
	BotID                string             `db:"bot_id" json:"bot_id"`
	ClientID             string             `db:"client_id" json:"client_id"`
	ExtraLinks           []byte             `db:"extra_links" json:"extra_links"`
	Tags                 []string           `db:"tags" json:"tags"`
	Prefix               string             `db:"prefix" json:"prefix"`
	Owner                pgtype.Text        `db:"owner" json:"owner"`
	Short                string             `db:"short" json:"short"`
	Library              string             `db:"library" json:"library"`
	Nsfw                 bool               `db:"nsfw" json:"nsfw"`
	Premium              bool               `db:"premium" json:"premium"`
	LastStatsPost        pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	LastJapiUpdate       pgtype.Timestamptz `db:"last_japi_update" json:"last_japi_update"`
	Servers              int32              `db:"servers" json:"servers"`
	Shards               int32              `db:"shards" json:"shards"`
	ShardList            []int64            `db:"shard_list" json:"shard_list"`
	Users                int32              `db:"users" json:"users"`
	ApproximateVotes     int32              `db:"approximate_votes" json:"approximate_votes"`
	Clicks               int32              `db:"clicks" json:"clicks"`
	InviteClicks         int32              `db:"invite_clicks" json:"invite_clicks"`
	Invite               string             `db:"invite" json:"invite"`
	Type                 string             `db:"type" json:"type"`
	VanityRef            pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	VoteBanned           bool               `db:"vote_banned" json:"vote_banned"`
	StartPremiumPeriod   pgtype.Timestamptz `db:"start_premium_period" json:"start_premium_period"`
	PremiumPeriodLength  timex.Duration     `db:"premium_period_length" json:"premium_period_length"`
	CertReason           pgtype.Text        `db:"cert_reason" json:"cert_reason"`
	Uptime               int64              `db:"uptime" json:"uptime"`
	TotalUptime          int64              `db:"total_uptime" json:"total_uptime"`
	UptimeLastChecked    pgtype.Timestamptz `db:"uptime_last_checked" json:"uptime_last_checked"`
	ApprovalNote         string             `db:"approval_note" json:"approval_note"`
	CreatedAt            pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ClaimedBy            pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	UpdatedAt            pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastClaimed          pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
	TeamOwner            pgtype.UUID        `db:"team_owner" json:"team_owner"`
	CaptchaOptOut        bool               `db:"captcha_opt_out" json:"captcha_opt_out"`
	SelfStatus           pgtype.Text        `db:"self_status" json:"self_status"`
	SupporterBadge       bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil         pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil        pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil     pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil       pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
	ModerationFlagged    bool               `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string           `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) GetBotByID(ctx context.Context, botID string) (GetBotByIDRow, error) {
	row := q.db.QueryRow(ctx, getBotByID, botID)
	var i GetBotByIDRow
	err := row.Scan(
		&i.Itag,
		&i.BotID,
		&i.ClientID,
		&i.ExtraLinks,
		&i.Tags,
		&i.Prefix,
		&i.Owner,
		&i.Short,
		&i.Library,
		&i.Nsfw,
		&i.Premium,
		&i.LastStatsPost,
		&i.LastJapiUpdate,
		&i.Servers,
		&i.Shards,
		&i.ShardList,
		&i.Users,
		&i.ApproximateVotes,
		&i.Clicks,
		&i.InviteClicks,
		&i.Invite,
		&i.Type,
		&i.VanityRef,
		&i.VoteBanned,
		&i.StartPremiumPeriod,
		&i.PremiumPeriodLength,
		&i.CertReason,
		&i.Uptime,
		&i.TotalUptime,
		&i.UptimeLastChecked,
		&i.ApprovalNote,
		&i.CreatedAt,
		&i.ClaimedBy,
		&i.UpdatedAt,
		&i.LastClaimed,
		&i.TeamOwner,
		&i.CaptchaOptOut,
		&i.SelfStatus,
		&i.SupporterBadge,
		&i.BoostedUntil,
		&i.FeaturedUntil,
		&i.SpotlightedUntil,
		&i.VoteBlitzUntil,
		&i.ModerationFlagged,
		&i.ModerationCategories,
	)
	return i, err
}

const getBotCaptchaOptOut = `-- name: GetBotCaptchaOptOut :one
SELECT captcha_opt_out FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotCaptchaOptOut(ctx context.Context, botID string) (bool, error) {
	row := q.db.QueryRow(ctx, getBotCaptchaOptOut, botID)
	var captcha_opt_out bool
	err := row.Scan(&captcha_opt_out)
	return captcha_opt_out, err
}

const getBotCertStats = `-- name: GetBotCertStats :one
SELECT type, servers, cardinality(unique_clicks) AS unique_clicks, approximate_votes, created_at
FROM bots
WHERE bot_id = $1
`

type GetBotCertStatsRow struct {
	Type             string             `db:"type" json:"type"`
	Servers          int32              `db:"servers" json:"servers"`
	UniqueClicks     int32              `db:"unique_clicks" json:"unique_clicks"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetBotCertStats(ctx context.Context, botID string) (GetBotCertStatsRow, error) {
	row := q.db.QueryRow(ctx, getBotCertStats, botID)
	var i GetBotCertStatsRow
	err := row.Scan(
		&i.Type,
		&i.Servers,
		&i.UniqueClicks,
		&i.ApproximateVotes,
		&i.CreatedAt,
	)
	return i, err
}

const getBotChangelogs = `-- name: GetBotChangelogs :many
SELECT id, title, content, version, created_by, created_at
FROM bot_changelogs
WHERE bot_id = $1
ORDER BY created_at DESC
`

type GetBotChangelogsRow struct {
	ID        string             `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Content   string             `db:"content" json:"content"`
	Version   string             `db:"version" json:"version"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetBotChangelogs(ctx context.Context, botID string) ([]GetBotChangelogsRow, error) {
	rows, err := q.db.Query(ctx, getBotChangelogs, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBotChangelogsRow
	for rows.Next() {
		var i GetBotChangelogsRow
		if err := rows.Scan(
			&i.ID,
			&i.Title,
			&i.Content,
			&i.Version,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotClientID = `-- name: GetBotClientID :one
SELECT client_id FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotClientID(ctx context.Context, botID string) (string, error) {
	row := q.db.QueryRow(ctx, getBotClientID, botID)
	var client_id string
	err := row.Scan(&client_id)
	return client_id, err
}

const getBotCommands = `-- name: GetBotCommands :many
SELECT id, name, description, usage, category, position, created_at, updated_at
FROM bot_commands
WHERE bot_id = $1
ORDER BY position ASC, created_at ASC
`

type GetBotCommandsRow struct {
	ID          string             `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Description string             `db:"description" json:"description"`
	Usage       string             `db:"usage" json:"usage"`
	Category    string             `db:"category" json:"category"`
	Position    int32              `db:"position" json:"position"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetBotCommands(ctx context.Context, botID string) ([]GetBotCommandsRow, error) {
	rows, err := q.db.Query(ctx, getBotCommands, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBotCommandsRow
	for rows.Next() {
		var i GetBotCommandsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.Usage,
			&i.Category,
			&i.Position,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotInvite = `-- name: GetBotInvite :one
SELECT invite FROM bots WHERE bot_id = $1 ORDER BY created_at DESC LIMIT 1
`

func (q *Queries) GetBotInvite(ctx context.Context, botID string) (string, error) {
	row := q.db.QueryRow(ctx, getBotInvite, botID)
	var invite string
	err := row.Scan(&invite)
	return invite, err
}

const getBotLongDescription = `-- name: GetBotLongDescription :one
SELECT long FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotLongDescription(ctx context.Context, botID string) (string, error) {
	row := q.db.QueryRow(ctx, getBotLongDescription, botID)
	var long string
	err := row.Scan(&long)
	return long, err
}

const getBotReviewStatus = `-- name: GetBotReviewStatus :one
SELECT type, claimed_by, last_claimed FROM bots WHERE bot_id = $1
`

type GetBotReviewStatusRow struct {
	Type        string             `db:"type" json:"type"`
	ClaimedBy   pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	LastClaimed pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
}

func (q *Queries) GetBotReviewStatus(ctx context.Context, botID string) (GetBotReviewStatusRow, error) {
	row := q.db.QueryRow(ctx, getBotReviewStatus, botID)
	var i GetBotReviewStatusRow
	err := row.Scan(&i.Type, &i.ClaimedBy, &i.LastClaimed)
	return i, err
}

const getBotReviewStatusWithOwner = `-- name: GetBotReviewStatusWithOwner :one
SELECT type, claimed_by, owner, last_claimed FROM bots WHERE bot_id = $1
`

type GetBotReviewStatusWithOwnerRow struct {
	Type        string             `db:"type" json:"type"`
	ClaimedBy   pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	Owner       pgtype.Text        `db:"owner" json:"owner"`
	LastClaimed pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
}

func (q *Queries) GetBotReviewStatusWithOwner(ctx context.Context, botID string) (GetBotReviewStatusWithOwnerRow, error) {
	row := q.db.QueryRow(ctx, getBotReviewStatusWithOwner, botID)
	var i GetBotReviewStatusWithOwnerRow
	err := row.Scan(
		&i.Type,
		&i.ClaimedBy,
		&i.Owner,
		&i.LastClaimed,
	)
	return i, err
}

const getBotSEO = `-- name: GetBotSEO :one
SELECT short FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotSEO(ctx context.Context, botID string) (string, error) {
	row := q.db.QueryRow(ctx, getBotSEO, botID)
	var short string
	err := row.Scan(&short)
	return short, err
}

const getBotSEOFields = `-- name: GetBotSEOFields :one
SELECT short, owner, team_owner, created_at, updated_at
FROM bots
WHERE bot_id = $1 AND (type = 'approved' OR type = 'certified')
`

type GetBotSEOFieldsRow struct {
	Short     string             `db:"short" json:"short"`
	Owner     pgtype.Text        `db:"owner" json:"owner"`
	TeamOwner pgtype.UUID        `db:"team_owner" json:"team_owner"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetBotSEOFields(ctx context.Context, botID string) (GetBotSEOFieldsRow, error) {
	row := q.db.QueryRow(ctx, getBotSEOFields, botID)
	var i GetBotSEOFieldsRow
	err := row.Scan(
		&i.Short,
		&i.Owner,
		&i.TeamOwner,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getBotTeamAndOwner = `-- name: GetBotTeamAndOwner :one
SELECT team_owner, owner FROM bots WHERE bot_id = $1
`

type GetBotTeamAndOwnerRow struct {
	TeamOwner pgtype.UUID `db:"team_owner" json:"team_owner"`
	Owner     pgtype.Text `db:"owner" json:"owner"`
}

func (q *Queries) GetBotTeamAndOwner(ctx context.Context, botID string) (GetBotTeamAndOwnerRow, error) {
	row := q.db.QueryRow(ctx, getBotTeamAndOwner, botID)
	var i GetBotTeamAndOwnerRow
	err := row.Scan(&i.TeamOwner, &i.Owner)
	return i, err
}

const getBotTeamOwner = `-- name: GetBotTeamOwner :one
SELECT team_owner FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotTeamOwner(ctx context.Context, botID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getBotTeamOwner, botID)
	var team_owner pgtype.UUID
	err := row.Scan(&team_owner)
	return team_owner, err
}

const getBotType = `-- name: GetBotType :one
SELECT type FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotType(ctx context.Context, botID string) (string, error) {
	row := q.db.QueryRow(ctx, getBotType, botID)
	var type_ string
	err := row.Scan(&type_)
	return type_, err
}

const getBotTypeAndClaimedBy = `-- name: GetBotTypeAndClaimedBy :one
SELECT type, claimed_by FROM bots WHERE bot_id = $1
`

type GetBotTypeAndClaimedByRow struct {
	Type      string      `db:"type" json:"type"`
	ClaimedBy pgtype.Text `db:"claimed_by" json:"claimed_by"`
}

func (q *Queries) GetBotTypeAndClaimedBy(ctx context.Context, botID string) (GetBotTypeAndClaimedByRow, error) {
	row := q.db.QueryRow(ctx, getBotTypeAndClaimedBy, botID)
	var i GetBotTypeAndClaimedByRow
	err := row.Scan(&i.Type, &i.ClaimedBy)
	return i, err
}

const getBotUniqueClicksCount = `-- name: GetBotUniqueClicksCount :one
SELECT cardinality(unique_clicks) FROM bots WHERE bot_id = $1
`

func (q *Queries) GetBotUniqueClicksCount(ctx context.Context, botID string) (int32, error) {
	row := q.db.QueryRow(ctx, getBotUniqueClicksCount, botID)
	var cardinality int32
	err := row.Scan(&cardinality)
	return cardinality, err
}

const getBotsDueForJapiUpdate = `-- name: GetBotsDueForJapiUpdate :many
SELECT bot_id FROM bots
WHERE (type = 'approved' OR type = 'certified')
AND (last_stats_post IS NULL OR NOW() - last_stats_post > INTERVAL '3 days')
AND (last_japi_update IS NULL OR NOW() - last_japi_update > INTERVAL '3 days')
ORDER BY RANDOM() LIMIT 10
`

func (q *Queries) GetBotsDueForJapiUpdate(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getBotsDueForJapiUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getBotsDueForModerationScan = `-- name: GetBotsDueForModerationScan :many
SELECT bot_id, short, long, nsfw
FROM bots
WHERE type IN ('approved', 'certified', 'pending')
AND (moderation_checked_at IS NULL OR moderation_checked_at < NOW() - INTERVAL '7 days')
ORDER BY moderation_checked_at ASC NULLS FIRST
LIMIT $1
`

type GetBotsDueForModerationScanRow struct {
	BotID string `db:"bot_id" json:"bot_id"`
	Short string `db:"short" json:"short"`
	Long  string `db:"long" json:"long"`
	Nsfw  bool   `db:"nsfw" json:"nsfw"`
}

func (q *Queries) GetBotsDueForModerationScan(ctx context.Context, limit int32) ([]GetBotsDueForModerationScanRow, error) {
	rows, err := q.db.Query(ctx, getBotsDueForModerationScan, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetBotsDueForModerationScanRow
	for rows.Next() {
		var i GetBotsDueForModerationScanRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Long,
			&i.Nsfw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getCertifiedIndexBots = `-- name: GetCertifiedIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE type = 'certified' ORDER BY approximate_votes DESC LIMIT 9
`

type GetCertifiedIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetCertifiedIndexBots(ctx context.Context) ([]GetCertifiedIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getCertifiedIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCertifiedIndexBotsRow
	for rows.Next() {
		var i GetCertifiedIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getExpiredPremiumBots = `-- name: GetExpiredPremiumBots :many
SELECT bot_id, start_premium_period, premium_period_length, type FROM bots
WHERE (
	premium = true
	AND (
		(type != 'approved' AND type != 'certified')
		OR (start_premium_period + premium_period_length) < NOW()
	)
)
`

type GetExpiredPremiumBotsRow struct {
	BotID               string             `db:"bot_id" json:"bot_id"`
	StartPremiumPeriod  pgtype.Timestamptz `db:"start_premium_period" json:"start_premium_period"`
	PremiumPeriodLength timex.Duration     `db:"premium_period_length" json:"premium_period_length"`
	Type                string             `db:"type" json:"type"`
}

func (q *Queries) GetExpiredPremiumBots(ctx context.Context) ([]GetExpiredPremiumBotsRow, error) {
	rows, err := q.db.Query(ctx, getExpiredPremiumBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetExpiredPremiumBotsRow
	for rows.Next() {
		var i GetExpiredPremiumBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.StartPremiumPeriod,
			&i.PremiumPeriodLength,
			&i.Type,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedIndexBots = `-- name: GetFeaturedIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE (type = 'approved' OR type = 'certified') AND featured_until IS NOT NULL AND featured_until > NOW() ORDER BY featured_until DESC LIMIT 9
`

type GetFeaturedIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetFeaturedIndexBots(ctx context.Context) ([]GetFeaturedIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getFeaturedIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturedIndexBotsRow
	for rows.Next() {
		var i GetFeaturedIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexBotByID = `-- name: GetIndexBotByID :one

SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE bot_id = $1
`

type GetIndexBotByIDRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

// IndexBot is the reduced projection used for listings, search results, and
// embedding a bot inside other entities (packs, etc.) -- shared across
// several packages, hence its own file even though "bots" the full package
// hasn't been converted yet.
func (q *Queries) GetIndexBotByID(ctx context.Context, botID string) (GetIndexBotByIDRow, error) {
	row := q.db.QueryRow(ctx, getIndexBotByID, botID)
	var i GetIndexBotByIDRow
	err := row.Scan(
		&i.BotID,
		&i.Short,
		&i.Type,
		&i.VanityRef,
		&i.ApproximateVotes,
		&i.Shards,
		&i.Library,
		&i.InviteClicks,
		&i.Clicks,
		&i.Servers,
		&i.Nsfw,
		&i.Tags,
		&i.Premium,
		&i.CreatedAt,
		&i.SelfStatus,
		&i.LastStatsPost,
		&i.SupporterBadge,
		&i.BoostedUntil,
		&i.FeaturedUntil,
		&i.SpotlightedUntil,
		&i.VoteBlitzUntil,
	)
	return i, err
}

const getIndexBotsByOwner = `-- name: GetIndexBotsByOwner :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE owner = $1
`

type GetIndexBotsByOwnerRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetIndexBotsByOwner(ctx context.Context, owner pgtype.Text) ([]GetIndexBotsByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getIndexBotsByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexBotsByOwnerRow
	for rows.Next() {
		var i GetIndexBotsByOwnerRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexBotsByTeamMembership = `-- name: GetIndexBotsByTeamMembership :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE team_owner IN (SELECT team_id FROM team_members WHERE user_id = $1)
`

type GetIndexBotsByTeamMembershipRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

// A bot's owner and team_owner are mutually exclusive (TransferToTeam
// clears owner when setting team_owner), so this and GetIndexBotsByOwner
// never return the same row -- callers union both, same pattern
// GetIndexServersByTeamMembership already established for servers.
func (q *Queries) GetIndexBotsByTeamMembership(ctx context.Context, userID string) ([]GetIndexBotsByTeamMembershipRow, error) {
	rows, err := q.db.Query(ctx, getIndexBotsByTeamMembership, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexBotsByTeamMembershipRow
	for rows.Next() {
		var i GetIndexBotsByTeamMembershipRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexBotsByTeamOwner = `-- name: GetIndexBotsByTeamOwner :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE team_owner = $1
`

type GetIndexBotsByTeamOwnerRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetIndexBotsByTeamOwner(ctx context.Context, teamOwner pgtype.UUID) ([]GetIndexBotsByTeamOwnerRow, error) {
	rows, err := q.db.Query(ctx, getIndexBotsByTeamOwner, teamOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexBotsByTeamOwnerRow
	for rows.Next() {
		var i GetIndexBotsByTeamOwnerRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexBotsPaged = `-- name: GetIndexBotsPaged :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE (type = 'approved' OR type = 'certified')
ORDER BY (boosted_until IS NOT NULL AND boosted_until > NOW()) DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type GetIndexBotsPagedParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetIndexBotsPagedRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetIndexBotsPaged(ctx context.Context, arg GetIndexBotsPagedParams) ([]GetIndexBotsPagedRow, error) {
	rows, err := q.db.Query(ctx, getIndexBotsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexBotsPagedRow
	for rows.Next() {
		var i GetIndexBotsPagedRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListedBotIDs = `-- name: GetListedBotIDs :many
SELECT bot_id FROM bots WHERE type = 'approved' OR type = 'certified'
`

func (q *Queries) GetListedBotIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getListedBotIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostViewedIndexBots = `-- name: GetMostViewedIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE type = 'approved' OR type = 'certified' ORDER BY clicks DESC LIMIT 9
`

type GetMostViewedIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetMostViewedIndexBots(ctx context.Context) ([]GetMostViewedIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getMostViewedIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMostViewedIndexBotsRow
	for rows.Next() {
		var i GetMostViewedIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPremiumIndexBots = `-- name: GetPremiumIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE premium = true ORDER BY approximate_votes DESC LIMIT 9
`

type GetPremiumIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetPremiumIndexBots(ctx context.Context) ([]GetPremiumIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getPremiumIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPremiumIndexBotsRow
	for rows.Next() {
		var i GetPremiumIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomIndexBots = `-- name: GetRandomIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE (type = 'approved' OR type = 'certified')
ORDER BY RANDOM()
LIMIT 6
`

type GetRandomIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetRandomIndexBots(ctx context.Context) ([]GetRandomIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getRandomIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomIndexBotsRow
	for rows.Next() {
		var i GetRandomIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyAddedIndexBots = `-- name: GetRecentlyAddedIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE type = 'approved' ORDER BY created_at DESC LIMIT 9
`

type GetRecentlyAddedIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetRecentlyAddedIndexBots(ctx context.Context) ([]GetRecentlyAddedIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyAddedIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyAddedIndexBotsRow
	for rows.Next() {
		var i GetRecentlyAddedIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimilarBots = `-- name: GetSimilarBots :many
WITH source_tags AS (
    SELECT tags FROM bots WHERE bot_id = $1
)
SELECT b.bot_id, b.short, b.type, b.vanity_ref, b.approximate_votes, b.shards, b.library, b.invite_clicks, b.clicks, b.servers, b.nsfw, b.tags, b.premium, b.created_at, b.self_status, b.last_stats_post, b.supporter_badge, b.boosted_until, b.featured_until, b.spotlighted_until, b.vote_blitz_until
FROM bots b, source_tags st
WHERE (b.type = 'approved' OR b.type = 'certified')
AND b.bot_id != $1
AND b.tags && st.tags
ORDER BY cardinality(ARRAY(SELECT unnest(b.tags) INTERSECT SELECT unnest(st.tags))) DESC, b.approximate_votes DESC
LIMIT 6
`

type GetSimilarBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

// Tag-overlap similarity: other approved/certified bots sharing at least
// one tag with bot_id, ranked by how many tags they share (most first),
// votes as the tiebreak. No ML/embeddings -- tags are the only structured
// signal bots already carry, and it's cheap, deterministic, and explains
// itself ("shares N tags with this bot").
func (q *Queries) GetSimilarBots(ctx context.Context, botID string) ([]GetSimilarBotsRow, error) {
	rows, err := q.db.Query(ctx, getSimilarBots, botID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimilarBotsRow
	for rows.Next() {
		var i GetSimilarBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotlightIndexBots = `-- name: GetSpotlightIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE (type = 'approved' OR type = 'certified') AND spotlighted_until IS NOT NULL AND spotlighted_until > NOW() ORDER BY spotlighted_until DESC LIMIT 9
`

type GetSpotlightIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetSpotlightIndexBots(ctx context.Context) ([]GetSpotlightIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getSpotlightIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotlightIndexBotsRow
	for rows.Next() {
		var i GetSpotlightIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaleClaimedBotsForUpdate = `-- name: GetStaleClaimedBotsForUpdate :many
SELECT bot_id, claimed_by, last_claimed FROM bots WHERE claimed_by IS NOT NULL AND NOW() - last_claimed > INTERVAL '1 hour' FOR UPDATE
`

type GetStaleClaimedBotsForUpdateRow struct {
	BotID       string             `db:"bot_id" json:"bot_id"`
	ClaimedBy   pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	LastClaimed pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
}

func (q *Queries) GetStaleClaimedBotsForUpdate(ctx context.Context) ([]GetStaleClaimedBotsForUpdateRow, error) {
	rows, err := q.db.Query(ctx, getStaleClaimedBotsForUpdate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaleClaimedBotsForUpdateRow
	for rows.Next() {
		var i GetStaleClaimedBotsForUpdateRow
		if err := rows.Scan(&i.BotID, &i.ClaimedBy, &i.LastClaimed); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopVotedIndexBots = `-- name: GetTopVotedIndexBots :many
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots WHERE type = 'approved' OR type = 'certified' ORDER BY approximate_votes DESC LIMIT 9
`

type GetTopVotedIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetTopVotedIndexBots(ctx context.Context) ([]GetTopVotedIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getTopVotedIndexBots)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopVotedIndexBotsRow
	for rows.Next() {
		var i GetTopVotedIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrendingIndexBots = `-- name: GetTrendingIndexBots :many
WITH scored AS (
	SELECT target_id, COUNT(*) FILTER (WHERE upvote) - COUNT(*) FILTER (WHERE NOT upvote) AS score
	FROM entity_votes
	WHERE target_type = 'bot' AND void = false AND created_at > now() - interval '7 days'
	GROUP BY target_id
)
SELECT bot_id, short, type, vanity_ref, approximate_votes, shards, library, invite_clicks, clicks, servers, nsfw, tags, premium, created_at, self_status, last_stats_post, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until
FROM bots
WHERE (type = 'approved' OR type = 'certified') AND bot_id IN (SELECT target_id FROM scored)
ORDER BY (SELECT score FROM scored WHERE scored.target_id = bots.bot_id) DESC
LIMIT $1 OFFSET $2
`

type GetTrendingIndexBotsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetTrendingIndexBotsRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetTrendingIndexBots(ctx context.Context, arg GetTrendingIndexBotsParams) ([]GetTrendingIndexBotsRow, error) {
	rows, err := q.db.Query(ctx, getTrendingIndexBots, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrendingIndexBotsRow
	for rows.Next() {
		var i GetTrendingIndexBotsRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBot = `-- name: InsertBot :exec
INSERT INTO bots (bot_id, client_id, short, long, prefix, invite, library, extra_links, tags, nsfw, approval_note, team_owner, servers, vanity_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14)
`

type InsertBotParams struct {
	BotID        string      `db:"bot_id" json:"bot_id"`
	ClientID     string      `db:"client_id" json:"client_id"`
	Short        string      `db:"short" json:"short"`
	Long         string      `db:"long" json:"long"`
	Prefix       string      `db:"prefix" json:"prefix"`
	Invite       string      `db:"invite" json:"invite"`
	Library      string      `db:"library" json:"library"`
	ExtraLinks   []byte      `db:"extra_links" json:"extra_links"`
	Tags         []string    `db:"tags" json:"tags"`
	Nsfw         bool        `db:"nsfw" json:"nsfw"`
	ApprovalNote string      `db:"approval_note" json:"approval_note"`
	TeamOwner    pgtype.UUID `db:"team_owner" json:"team_owner"`
	Servers      int32       `db:"servers" json:"servers"`
	VanityRef    pgtype.UUID `db:"vanity_ref" json:"vanity_ref"`
}

func (q *Queries) InsertBot(ctx context.Context, arg InsertBotParams) error {
	_, err := q.db.Exec(ctx, insertBot,
		arg.BotID,
		arg.ClientID,
		arg.Short,
		arg.Long,
		arg.Prefix,
		arg.Invite,
		arg.Library,
		arg.ExtraLinks,
		arg.Tags,
		arg.Nsfw,
		arg.ApprovalNote,
		arg.TeamOwner,
		arg.Servers,
		arg.VanityRef,
	)
	return err
}

const insertBotChangelog = `-- name: InsertBotChangelog :one
INSERT INTO bot_changelogs (bot_id, title, content, version, created_by)
VALUES ($1, $2, $3, $4, $5)
RETURNING id, title, content, version, created_by, created_at
`

type InsertBotChangelogParams struct {
	BotID     string `db:"bot_id" json:"bot_id"`
	Title     string `db:"title" json:"title"`
	Content   string `db:"content" json:"content"`
	Version   string `db:"version" json:"version"`
	CreatedBy string `db:"created_by" json:"created_by"`
}

type InsertBotChangelogRow struct {
	ID        string             `db:"id" json:"id"`
	Title     string             `db:"title" json:"title"`
	Content   string             `db:"content" json:"content"`
	Version   string             `db:"version" json:"version"`
	CreatedBy string             `db:"created_by" json:"created_by"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertBotChangelog(ctx context.Context, arg InsertBotChangelogParams) (InsertBotChangelogRow, error) {
	row := q.db.QueryRow(ctx, insertBotChangelog,
		arg.BotID,
		arg.Title,
		arg.Content,
		arg.Version,
		arg.CreatedBy,
	)
	var i InsertBotChangelogRow
	err := row.Scan(
		&i.ID,
		&i.Title,
		&i.Content,
		&i.Version,
		&i.CreatedBy,
		&i.CreatedAt,
	)
	return i, err
}

const insertBotCommand = `-- name: InsertBotCommand :exec
INSERT INTO bot_commands (bot_id, name, description, usage, category, position) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertBotCommandParams struct {
	BotID       string `db:"bot_id" json:"bot_id"`
	Name        string `db:"name" json:"name"`
	Description string `db:"description" json:"description"`
	Usage       string `db:"usage" json:"usage"`
	Category    string `db:"category" json:"category"`
	Position    int32  `db:"position" json:"position"`
}

func (q *Queries) InsertBotCommand(ctx context.Context, arg InsertBotCommandParams) error {
	_, err := q.db.Exec(ctx, insertBotCommand,
		arg.BotID,
		arg.Name,
		arg.Description,
		arg.Usage,
		arg.Category,
		arg.Position,
	)
	return err
}

const recordBotModerationScan = `-- name: RecordBotModerationScan :exec
UPDATE bots SET moderation_flagged = $2, moderation_categories = $3, moderation_checked_at = NOW() WHERE bot_id = $1
`

type RecordBotModerationScanParams struct {
	BotID                string   `db:"bot_id" json:"bot_id"`
	ModerationFlagged    bool     `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) RecordBotModerationScan(ctx context.Context, arg RecordBotModerationScanParams) error {
	_, err := q.db.Exec(ctx, recordBotModerationScan, arg.BotID, arg.ModerationFlagged, arg.ModerationCategories)
	return err
}

const recordBotUptimeCheck = `-- name: RecordBotUptimeCheck :exec
UPDATE bots SET
	total_uptime = total_uptime + 1,
	uptime = uptime + CASE WHEN $1::boolean THEN 1 ELSE 0 END,
	uptime_last_checked = NOW()
WHERE bot_id = $2::text
`

type RecordBotUptimeCheckParams struct {
	Online bool   `db:"online" json:"online"`
	BotID  string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) RecordBotUptimeCheck(ctx context.Context, arg RecordBotUptimeCheckParams) error {
	_, err := q.db.Exec(ctx, recordBotUptimeCheck, arg.Online, arg.BotID)
	return err
}

const removeBotPremium = `-- name: RemoveBotPremium :exec
UPDATE bots SET premium = false WHERE bot_id = $1
`

func (q *Queries) RemoveBotPremium(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, removeBotPremium, botID)
	return err
}

const resubmitBot = `-- name: ResubmitBot :exec
UPDATE bots SET type = 'pending', claimed_by = NULL WHERE bot_id = $1
`

func (q *Queries) ResubmitBot(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, resubmitBot, botID)
	return err
}

const searchBotsPublic = `-- name: SearchBotsPublic :many
SELECT bots.bot_id, bots.short, bots.type, bots.vanity_ref, bots.approximate_votes, bots.shards, bots.library,
    bots.invite_clicks, bots.clicks, bots.servers, bots.nsfw, bots.tags, bots.premium, bots.created_at,
    bots.self_status, bots.last_stats_post, bots.supporter_badge, bots.boosted_until, bots.featured_until,
    bots.spotlighted_until, bots.vote_blitz_until
FROM bots
LEFT JOIN internal_user_cache__discord iucd ON bots.bot_id = iucd.id
WHERE (bots.type = 'approved' OR bots.type = 'certified')
AND ($1::int = 0 OR bots.servers >= $1::int)
AND ($2::int = 0 OR bots.servers <= $2::int)
AND ($3::int = 0 OR bots.approximate_votes >= $3::int)
AND ($4::int = 0 OR bots.approximate_votes <= $4::int)
AND ($5::int = 0 OR bots.shards >= $5::int)
AND ($6::int = 0 OR bots.shards <= $6::int)
AND (
    cardinality($7::text[]) = 0
    OR ($8::text = '@>' AND bots.tags @> $7::text[])
    OR ($8::text = '&&' AND bots.tags && $7::text[])
)
AND (
    $9::text = ''
    OR bots.short @@ $9::text
    OR bots.bot_id = $9::text
    OR bots.client_id = $9::text
    OR iucd.username @@ $9::text
    OR iucd.username ILIKE $10::text
)
ORDER BY bots.approximate_votes DESC, bots.type DESC
LIMIT 12
`

type SearchBotsPublicParams struct {
	ServersFrom int32    `db:"servers_from" json:"servers_from"`
	ServersTo   int32    `db:"servers_to" json:"servers_to"`
	VotesFrom   int32    `db:"votes_from" json:"votes_from"`
	VotesTo     int32    `db:"votes_to" json:"votes_to"`
	ShardsFrom  int32    `db:"shards_from" json:"shards_from"`
	ShardsTo    int32    `db:"shards_to" json:"shards_to"`
	Tags        []string `db:"tags" json:"tags"`
	TagMode     string   `db:"tag_mode" json:"tag_mode"`
	Query       string   `db:"query" json:"query"`
	Pattern     string   `db:"pattern" json:"pattern"`
}

type SearchBotsPublicRow struct {
	BotID            string             `db:"bot_id" json:"bot_id"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards           int32              `db:"shards" json:"shards"`
	Library          string             `db:"library" json:"library"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Servers          int32              `db:"servers" json:"servers"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	SelfStatus       pgtype.Text        `db:"self_status" json:"self_status"`
	LastStatsPost    pgtype.Timestamptz `db:"last_stats_post" json:"last_stats_post"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil   pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

// Backs POST /list/search's "bot" target type. iucd is the Discord user
// cache (internal_user_cache__discord) -- left-joined unconditionally so
// bots with no cached user row still show up when there's no text query,
// same as the raw-SQL version this replaced only inner-joining when needed.
func (q *Queries) SearchBotsPublic(ctx context.Context, arg SearchBotsPublicParams) ([]SearchBotsPublicRow, error) {
	rows, err := q.db.Query(ctx, searchBotsPublic,
		arg.ServersFrom,
		arg.ServersTo,
		arg.VotesFrom,
		arg.VotesTo,
		arg.ShardsFrom,
		arg.ShardsTo,
		arg.Tags,
		arg.TagMode,
		arg.Query,
		arg.Pattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBotsPublicRow
	for rows.Next() {
		var i SearchBotsPublicRow
		if err := rows.Scan(
			&i.BotID,
			&i.Short,
			&i.Type,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.CreatedAt,
			&i.SelfStatus,
			&i.LastStatsPost,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
			&i.VoteBlitzUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchBotsQueue = `-- name: SearchBotsQueue :many
SELECT bots.bot_id, bots.client_id, bots.type, bots.approximate_votes, bots.shards, bots.library, bots.invite_clicks, bots.clicks,
       bots.servers, bots.last_claimed, bots.claimed_by, bots.approval_note, bots.short, bots.invite,
       bots.moderation_flagged, bots.moderation_categories
FROM bots
INNER JOIN internal_user_cache__discord discord_users ON bots.bot_id = discord_users.id
WHERE bots.bot_id = $1::text OR bots.client_id = $1::text OR discord_users.username ILIKE $2::text
ORDER BY bots.created_at
`

type SearchBotsQueueParams struct {
	Query   string `db:"query" json:"query"`
	Pattern string `db:"pattern" json:"pattern"`
}

type SearchBotsQueueRow struct {
	BotID                string             `db:"bot_id" json:"bot_id"`
	ClientID             string             `db:"client_id" json:"client_id"`
	Type                 string             `db:"type" json:"type"`
	ApproximateVotes     int32              `db:"approximate_votes" json:"approximate_votes"`
	Shards               int32              `db:"shards" json:"shards"`
	Library              string             `db:"library" json:"library"`
	InviteClicks         int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks               int32              `db:"clicks" json:"clicks"`
	Servers              int32              `db:"servers" json:"servers"`
	LastClaimed          pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
	ClaimedBy            pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	ApprovalNote         string             `db:"approval_note" json:"approval_note"`
	Short                string             `db:"short" json:"short"`
	Invite               string             `db:"invite" json:"invite"`
	ModerationFlagged    bool               `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string           `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) SearchBotsQueue(ctx context.Context, arg SearchBotsQueueParams) ([]SearchBotsQueueRow, error) {
	rows, err := q.db.Query(ctx, searchBotsQueue, arg.Query, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchBotsQueueRow
	for rows.Next() {
		var i SearchBotsQueueRow
		if err := rows.Scan(
			&i.BotID,
			&i.ClientID,
			&i.Type,
			&i.ApproximateVotes,
			&i.Shards,
			&i.Library,
			&i.InviteClicks,
			&i.Clicks,
			&i.Servers,
			&i.LastClaimed,
			&i.ClaimedBy,
			&i.ApprovalNote,
			&i.Short,
			&i.Invite,
			&i.ModerationFlagged,
			&i.ModerationCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setBotSpotlightedUntil = `-- name: SetBotSpotlightedUntil :exec
UPDATE bots SET spotlighted_until = GREATEST(COALESCE(spotlighted_until, NOW()), NOW()) + make_interval(hours => $1::int) WHERE bot_id = $2::text
`

type SetBotSpotlightedUntilParams struct {
	Hours int32  `db:"hours" json:"hours"`
	BotID string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) SetBotSpotlightedUntil(ctx context.Context, arg SetBotSpotlightedUntilParams) error {
	_, err := q.db.Exec(ctx, setBotSpotlightedUntil, arg.Hours, arg.BotID)
	return err
}

const setBotTeamOwnerDirect = `-- name: SetBotTeamOwnerDirect :exec
UPDATE bots SET team_owner = $2 WHERE bot_id = $1
`

type SetBotTeamOwnerDirectParams struct {
	BotID     string      `db:"bot_id" json:"bot_id"`
	TeamOwner pgtype.UUID `db:"team_owner" json:"team_owner"`
}

func (q *Queries) SetBotTeamOwnerDirect(ctx context.Context, arg SetBotTeamOwnerDirectParams) error {
	_, err := q.db.Exec(ctx, setBotTeamOwnerDirect, arg.BotID, arg.TeamOwner)
	return err
}

const setBotVoteBanned = `-- name: SetBotVoteBanned :exec
UPDATE bots SET vote_banned = $2 WHERE bot_id = $1
`

type SetBotVoteBannedParams struct {
	BotID      string `db:"bot_id" json:"bot_id"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SetBotVoteBanned(ctx context.Context, arg SetBotVoteBannedParams) error {
	_, err := q.db.Exec(ctx, setBotVoteBanned, arg.BotID, arg.VoteBanned)
	return err
}

const touchBotJapiUpdate = `-- name: TouchBotJapiUpdate :exec
UPDATE bots SET last_japi_update = NOW() WHERE bot_id = $1
`

func (q *Queries) TouchBotJapiUpdate(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, touchBotJapiUpdate, botID)
	return err
}

const uncertifyBot = `-- name: UncertifyBot :exec
UPDATE bots SET type = 'approved' WHERE bot_id = $1
`

func (q *Queries) UncertifyBot(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, uncertifyBot, botID)
	return err
}

const updateBotClaim = `-- name: UpdateBotClaim :exec
UPDATE bots SET last_claimed = NOW(), claimed_by = $1 WHERE bot_id = $2
`

type UpdateBotClaimParams struct {
	ClaimedBy pgtype.Text `db:"claimed_by" json:"claimed_by"`
	BotID     string      `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotClaim(ctx context.Context, arg UpdateBotClaimParams) error {
	_, err := q.db.Exec(ctx, updateBotClaim, arg.ClaimedBy, arg.BotID)
	return err
}

const updateBotClicks = `-- name: UpdateBotClicks :exec
UPDATE bots SET clicks = clicks + 1 WHERE bot_id = $1
`

func (q *Queries) UpdateBotClicks(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, updateBotClicks, botID)
	return err
}

const updateBotInviteClicks = `-- name: UpdateBotInviteClicks :exec
UPDATE bots SET invite_clicks = invite_clicks + 1 WHERE bot_id = $1
`

func (q *Queries) UpdateBotInviteClicks(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, updateBotInviteClicks, botID)
	return err
}

const updateBotJapiServers = `-- name: UpdateBotJapiServers :exec
UPDATE bots SET last_japi_update = NOW(), servers = $1 WHERE bot_id = $2
`

type UpdateBotJapiServersParams struct {
	Servers int32  `db:"servers" json:"servers"`
	BotID   string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotJapiServers(ctx context.Context, arg UpdateBotJapiServersParams) error {
	_, err := q.db.Exec(ctx, updateBotJapiServers, arg.Servers, arg.BotID)
	return err
}

const updateBotLastStatsPost = `-- name: UpdateBotLastStatsPost :exec
UPDATE bots SET last_stats_post = NOW() WHERE bot_id = $1
`

func (q *Queries) UpdateBotLastStatsPost(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, updateBotLastStatsPost, botID)
	return err
}

const updateBotModerationResult = `-- name: UpdateBotModerationResult :exec
UPDATE bots SET moderation_flagged = $2, moderation_categories = $3 WHERE bot_id = $1
`

type UpdateBotModerationResultParams struct {
	BotID                string   `db:"bot_id" json:"bot_id"`
	ModerationFlagged    bool     `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) UpdateBotModerationResult(ctx context.Context, arg UpdateBotModerationResultParams) error {
	_, err := q.db.Exec(ctx, updateBotModerationResult, arg.BotID, arg.ModerationFlagged, arg.ModerationCategories)
	return err
}

const updateBotOwner = `-- name: UpdateBotOwner :exec
UPDATE bots SET owner = $2 WHERE bot_id = $1
`

type UpdateBotOwnerParams struct {
	BotID string      `db:"bot_id" json:"bot_id"`
	Owner pgtype.Text `db:"owner" json:"owner"`
}

func (q *Queries) UpdateBotOwner(ctx context.Context, arg UpdateBotOwnerParams) error {
	_, err := q.db.Exec(ctx, updateBotOwner, arg.BotID, arg.Owner)
	return err
}

const updateBotSelfStatus = `-- name: UpdateBotSelfStatus :exec
UPDATE bots SET self_status = $1 WHERE bot_id = $2
`

type UpdateBotSelfStatusParams struct {
	SelfStatus pgtype.Text `db:"self_status" json:"self_status"`
	BotID      string      `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotSelfStatus(ctx context.Context, arg UpdateBotSelfStatusParams) error {
	_, err := q.db.Exec(ctx, updateBotSelfStatus, arg.SelfStatus, arg.BotID)
	return err
}

const updateBotServers = `-- name: UpdateBotServers :exec
UPDATE bots SET servers = $1 WHERE bot_id = $2
`

type UpdateBotServersParams struct {
	Servers int32  `db:"servers" json:"servers"`
	BotID   string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotServers(ctx context.Context, arg UpdateBotServersParams) error {
	_, err := q.db.Exec(ctx, updateBotServers, arg.Servers, arg.BotID)
	return err
}

const updateBotSettings = `-- name: UpdateBotSettings :exec
UPDATE bots SET short = $1, long = $2, prefix = $3, invite = $4, library = $5, extra_links = $6, tags = $7, nsfw = $8, captcha_opt_out = $9, updated_at = NOW()
WHERE bot_id = $10
`

type UpdateBotSettingsParams struct {
	Short         string   `db:"short" json:"short"`
	Long          string   `db:"long" json:"long"`
	Prefix        string   `db:"prefix" json:"prefix"`
	Invite        string   `db:"invite" json:"invite"`
	Library       string   `db:"library" json:"library"`
	ExtraLinks    []byte   `db:"extra_links" json:"extra_links"`
	Tags          []string `db:"tags" json:"tags"`
	Nsfw          bool     `db:"nsfw" json:"nsfw"`
	CaptchaOptOut bool     `db:"captcha_opt_out" json:"captcha_opt_out"`
	BotID         string   `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotSettings(ctx context.Context, arg UpdateBotSettingsParams) error {
	_, err := q.db.Exec(ctx, updateBotSettings,
		arg.Short,
		arg.Long,
		arg.Prefix,
		arg.Invite,
		arg.Library,
		arg.ExtraLinks,
		arg.Tags,
		arg.Nsfw,
		arg.CaptchaOptOut,
		arg.BotID,
	)
	return err
}

const updateBotShardList = `-- name: UpdateBotShardList :exec
UPDATE bots SET shard_list = $1 WHERE bot_id = $2
`

type UpdateBotShardListParams struct {
	ShardList []int64 `db:"shard_list" json:"shard_list"`
	BotID     string  `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotShardList(ctx context.Context, arg UpdateBotShardListParams) error {
	_, err := q.db.Exec(ctx, updateBotShardList, arg.ShardList, arg.BotID)
	return err
}

const updateBotShards = `-- name: UpdateBotShards :exec
UPDATE bots SET shards = $1 WHERE bot_id = $2
`

type UpdateBotShardsParams struct {
	Shards int32  `db:"shards" json:"shards"`
	BotID  string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotShards(ctx context.Context, arg UpdateBotShardsParams) error {
	_, err := q.db.Exec(ctx, updateBotShards, arg.Shards, arg.BotID)
	return err
}

const updateBotTeamOwner = `-- name: UpdateBotTeamOwner :exec
UPDATE bots SET team_owner = $1, owner = NULL WHERE bot_id = $2
`

type UpdateBotTeamOwnerParams struct {
	TeamOwner pgtype.UUID `db:"team_owner" json:"team_owner"`
	BotID     string      `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotTeamOwner(ctx context.Context, arg UpdateBotTeamOwnerParams) error {
	_, err := q.db.Exec(ctx, updateBotTeamOwner, arg.TeamOwner, arg.BotID)
	return err
}

const updateBotUsers = `-- name: UpdateBotUsers :exec
UPDATE bots SET users = $1 WHERE bot_id = $2
`

type UpdateBotUsersParams struct {
	Users int32  `db:"users" json:"users"`
	BotID string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotUsers(ctx context.Context, arg UpdateBotUsersParams) error {
	_, err := q.db.Exec(ctx, updateBotUsers, arg.Users, arg.BotID)
	return err
}
