// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: changelogs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countChangelogByItag = `-- name: CountChangelogByItag :one
SELECT EXISTS(SELECT 1 FROM changelogs WHERE itag = $1)
`

func (q *Queries) CountChangelogByItag(ctx context.Context, itag string) (bool, error) {
	row := q.db.QueryRow(ctx, countChangelogByItag, itag)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deleteChangelogByItag = `-- name: DeleteChangelogByItag :exec
DELETE FROM changelogs WHERE itag = $1
`

func (q *Queries) DeleteChangelogByItag(ctx context.Context, itag string) error {
	_, err := q.db.Exec(ctx, deleteChangelogByItag, itag)
	return err
}

const getChangelogList = `-- name: GetChangelogList :many
SELECT itag, project, version, added, updated, fixed, removed, extra_description, prerelease, created_by, created_at
FROM changelogs
WHERE published = true AND ($1::text IS NULL OR project = $1)
ORDER BY created_at DESC
`

type GetChangelogListRow struct {
	Itag             string             `db:"itag" json:"itag"`
	Project          string             `db:"project" json:"project"`
	Version          string             `db:"version" json:"version"`
	Added            []string           `db:"added" json:"added"`
	Updated          []string           `db:"updated" json:"updated"`
	Fixed            []string           `db:"fixed" json:"fixed"`
	Removed          []string           `db:"removed" json:"removed"`
	ExtraDescription string             `db:"extra_description" json:"extra_description"`
	Prerelease       bool               `db:"prerelease" json:"prerelease"`
	CreatedBy        string             `db:"created_by" json:"created_by"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetChangelogList(ctx context.Context, project pgtype.Text) ([]GetChangelogListRow, error) {
	rows, err := q.db.Query(ctx, getChangelogList, project)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetChangelogListRow
	for rows.Next() {
		var i GetChangelogListRow
		if err := rows.Scan(
			&i.Itag,
			&i.Project,
			&i.Version,
			&i.Added,
			&i.Updated,
			&i.Fixed,
			&i.Removed,
			&i.ExtraDescription,
			&i.Prerelease,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getChangelogPublishedByItag = `-- name: GetChangelogPublishedByItag :one
SELECT published FROM changelogs WHERE itag = $1
`

func (q *Queries) GetChangelogPublishedByItag(ctx context.Context, itag string) (bool, error) {
	row := q.db.QueryRow(ctx, getChangelogPublishedByItag, itag)
	var published bool
	err := row.Scan(&published)
	return published, err
}

const insertChangelogEntry = `-- name: InsertChangelogEntry :exec
INSERT INTO changelogs (project, version, added, updated, fixed, removed, extra_description, prerelease, published, created_by, created_at)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, COALESCE($11::timestamptz, NOW()))
`

type InsertChangelogEntryParams struct {
	Project          string             `db:"project" json:"project"`
	Version          string             `db:"version" json:"version"`
	Added            []string           `db:"added" json:"added"`
	Updated          []string           `db:"updated" json:"updated"`
	Fixed            []string           `db:"fixed" json:"fixed"`
	Removed          []string           `db:"removed" json:"removed"`
	ExtraDescription string             `db:"extra_description" json:"extra_description"`
	Prerelease       bool               `db:"prerelease" json:"prerelease"`
	Published        bool               `db:"published" json:"published"`
	CreatedBy        string             `db:"created_by" json:"created_by"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) InsertChangelogEntry(ctx context.Context, arg InsertChangelogEntryParams) error {
	_, err := q.db.Exec(ctx, insertChangelogEntry,
		arg.Project,
		arg.Version,
		arg.Added,
		arg.Updated,
		arg.Fixed,
		arg.Removed,
		arg.ExtraDescription,
		arg.Prerelease,
		arg.Published,
		arg.CreatedBy,
		arg.CreatedAt,
	)
	return err
}

const listChangelogEntries = `-- name: ListChangelogEntries :many

SELECT itag, project, version, added, updated, fixed, removed, extra_description, prerelease, published, created_by, created_at
FROM changelogs ORDER BY created_at DESC
`

type ListChangelogEntriesRow struct {
	Itag             string             `db:"itag" json:"itag"`
	Project          string             `db:"project" json:"project"`
	Version          string             `db:"version" json:"version"`
	Added            []string           `db:"added" json:"added"`
	Updated          []string           `db:"updated" json:"updated"`
	Fixed            []string           `db:"fixed" json:"fixed"`
	Removed          []string           `db:"removed" json:"removed"`
	ExtraDescription string             `db:"extra_description" json:"extra_description"`
	Prerelease       bool               `db:"prerelease" json:"prerelease"`
	Published        bool               `db:"published" json:"published"`
	CreatedBy        string             `db:"created_by" json:"created_by"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Panel changelog CRUD (arcadia/panel ops_content.go) sees every entry,
// published or not, which is why it can't reuse GetChangelogList above.
func (q *Queries) ListChangelogEntries(ctx context.Context) ([]ListChangelogEntriesRow, error) {
	rows, err := q.db.Query(ctx, listChangelogEntries)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChangelogEntriesRow
	for rows.Next() {
		var i ListChangelogEntriesRow
		if err := rows.Scan(
			&i.Itag,
			&i.Project,
			&i.Version,
			&i.Added,
			&i.Updated,
			&i.Fixed,
			&i.Removed,
			&i.ExtraDescription,
			&i.Prerelease,
			&i.Published,
			&i.CreatedBy,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChangelogEntry = `-- name: UpdateChangelogEntry :exec
UPDATE changelogs SET project = $2, version = $3, added = $4, updated = $5, fixed = $6, removed = $7, extra_description = $8, prerelease = $9, published = $10, created_at = COALESCE($11::timestamptz, created_at)
WHERE itag = $1
`

type UpdateChangelogEntryParams struct {
	Itag             string             `db:"itag" json:"itag"`
	Project          string             `db:"project" json:"project"`
	Version          string             `db:"version" json:"version"`
	Added            []string           `db:"added" json:"added"`
	Updated          []string           `db:"updated" json:"updated"`
	Fixed            []string           `db:"fixed" json:"fixed"`
	Removed          []string           `db:"removed" json:"removed"`
	ExtraDescription string             `db:"extra_description" json:"extra_description"`
	Prerelease       bool               `db:"prerelease" json:"prerelease"`
	Published        bool               `db:"published" json:"published"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) UpdateChangelogEntry(ctx context.Context, arg UpdateChangelogEntryParams) error {
	_, err := q.db.Exec(ctx, updateChangelogEntry,
		arg.Itag,
		arg.Project,
		arg.Version,
		arg.Added,
		arg.Updated,
		arg.Fixed,
		arg.Removed,
		arg.ExtraDescription,
		arg.Prerelease,
		arg.Published,
		arg.CreatedAt,
	)
	return err
}
