// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: entityassets.sql

package db

import (
	"context"
)

const getEntityAssetVersions = `-- name: GetEntityAssetVersions :many
SELECT target_id, kind, version FROM entity_assets
WHERE target_type = $1 AND target_id = ANY($2::text[])
`

type GetEntityAssetVersionsParams struct {
	TargetType string   `db:"target_type" json:"target_type"`
	TargetIds  []string `db:"target_ids" json:"target_ids"`
}

type GetEntityAssetVersionsRow struct {
	TargetID string `db:"target_id" json:"target_id"`
	Kind     string `db:"kind" json:"kind"`
	Version  string `db:"version" json:"version"`
}

func (q *Queries) GetEntityAssetVersions(ctx context.Context, arg GetEntityAssetVersionsParams) ([]GetEntityAssetVersionsRow, error) {
	rows, err := q.db.Query(ctx, getEntityAssetVersions, arg.TargetType, arg.TargetIds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityAssetVersionsRow
	for rows.Next() {
		var i GetEntityAssetVersionsRow
		if err := rows.Scan(&i.TargetID, &i.Kind, &i.Version); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEntityAssetVersion = `-- name: UpsertEntityAssetVersion :exec
INSERT INTO entity_assets (target_type, target_id, kind, version)
VALUES ($1, $2, $3, $4)
ON CONFLICT (target_type, target_id, kind)
DO UPDATE SET version = EXCLUDED.version, updated_at = NOW()
`

type UpsertEntityAssetVersionParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
	Kind       string `db:"kind" json:"kind"`
	Version    string `db:"version" json:"version"`
}

func (q *Queries) UpsertEntityAssetVersion(ctx context.Context, arg UpsertEntityAssetVersionParams) error {
	_, err := q.db.Exec(ctx, upsertEntityAssetVersion,
		arg.TargetType,
		arg.TargetID,
		arg.Kind,
		arg.Version,
	)
	return err
}
