// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: list.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getCertifiedBotIDs = `-- name: GetCertifiedBotIDs :many
SELECT bot_id FROM bots WHERE type = 'certified' ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetCertifiedBotIDsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetCertifiedBotIDs(ctx context.Context, arg GetCertifiedBotIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getCertifiedBotIDs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getListStats = `-- name: GetListStats :one
SELECT
    (SELECT COUNT(*) FROM bots) AS total_bots,
    (SELECT COUNT(*) FROM bots WHERE type = 'approved') AS total_approved_bots,
    (SELECT COUNT(*) FROM bots WHERE type = 'certified') AS total_certified_bots,
    (SELECT COUNT(*) FROM bots WHERE type = 'pending') AS total_pending_bots,
    (SELECT COUNT(*) FROM bots WHERE type = 'denied') AS total_denied_bots,
    (SELECT COUNT(*) FROM staff_members) AS total_staff,
    (SELECT COUNT(*) FROM users) AS total_users,
    -- COALESCE guards against SUM() returning NULL when bots is empty --
    -- the original raw-SQL version scanned straight into a non-nullable
    -- int64 and would have panicked on an empty table. Found via live
    -- testing against the (empty) test database.
    (SELECT COALESCE(SUM(approximate_votes), 0)::bigint FROM bots) AS total_votes,
    (SELECT COUNT(*) FROM packs) AS total_packs,
    (SELECT COUNT(*) FROM tickets) AS total_tickets,
    (SELECT COUNT(*) FROM users WHERE banned = true) AS total_banned_users,
    (SELECT COUNT(*) FROM bots WHERE vote_banned = true) AS total_vote_banned_bots,
    (SELECT COUNT(*) FROM servers) AS total_servers,
    (SELECT COUNT(*) FROM servers WHERE type = 'approved') AS total_approved_servers,
    (SELECT COUNT(*) FROM servers WHERE type = 'certified') AS total_certified_servers,
    (SELECT COUNT(*) FROM servers WHERE type = 'pending') AS total_pending_servers,
    (SELECT COUNT(*) FROM servers WHERE type = 'denied') AS total_denied_servers,
    (SELECT COUNT(*) FROM servers WHERE vote_banned = true) AS total_vote_banned_servers
`

type GetListStatsRow struct {
	TotalBots              int64 `db:"total_bots" json:"total_bots"`
	TotalApprovedBots      int64 `db:"total_approved_bots" json:"total_approved_bots"`
	TotalCertifiedBots     int64 `db:"total_certified_bots" json:"total_certified_bots"`
	TotalPendingBots       int64 `db:"total_pending_bots" json:"total_pending_bots"`
	TotalDeniedBots        int64 `db:"total_denied_bots" json:"total_denied_bots"`
	TotalStaff             int64 `db:"total_staff" json:"total_staff"`
	TotalUsers             int64 `db:"total_users" json:"total_users"`
	TotalVotes             int64 `db:"total_votes" json:"total_votes"`
	TotalPacks             int64 `db:"total_packs" json:"total_packs"`
	TotalTickets           int64 `db:"total_tickets" json:"total_tickets"`
	TotalBannedUsers       int64 `db:"total_banned_users" json:"total_banned_users"`
	TotalVoteBannedBots    int64 `db:"total_vote_banned_bots" json:"total_vote_banned_bots"`
	TotalServers           int64 `db:"total_servers" json:"total_servers"`
	TotalApprovedServers   int64 `db:"total_approved_servers" json:"total_approved_servers"`
	TotalCertifiedServers  int64 `db:"total_certified_servers" json:"total_certified_servers"`
	TotalPendingServers    int64 `db:"total_pending_servers" json:"total_pending_servers"`
	TotalDeniedServers     int64 `db:"total_denied_servers" json:"total_denied_servers"`
	TotalVoteBannedServers int64 `db:"total_vote_banned_servers" json:"total_vote_banned_servers"`
}

// Folded from 17 separate COUNT(*) round-trips into one query with
// sub-selects -- same data, one round trip instead of seventeen.
func (q *Queries) GetListStats(ctx context.Context) (GetListStatsRow, error) {
	row := q.db.QueryRow(ctx, getListStats)
	var i GetListStatsRow
	err := row.Scan(
		&i.TotalBots,
		&i.TotalApprovedBots,
		&i.TotalCertifiedBots,
		&i.TotalPendingBots,
		&i.TotalDeniedBots,
		&i.TotalStaff,
		&i.TotalUsers,
		&i.TotalVotes,
		&i.TotalPacks,
		&i.TotalTickets,
		&i.TotalBannedUsers,
		&i.TotalVoteBannedBots,
		&i.TotalServers,
		&i.TotalApprovedServers,
		&i.TotalCertifiedServers,
		&i.TotalPendingServers,
		&i.TotalDeniedServers,
		&i.TotalVoteBannedServers,
	)
	return i, err
}

const getNewBotIDs = `-- name: GetNewBotIDs :many

SELECT bot_id FROM bots WHERE (type = 'approved' OR type = 'certified') ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetNewBotIDsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

// Shared by get_rss_feed and get_sitemap.
func (q *Queries) GetNewBotIDs(ctx context.Context, arg GetNewBotIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getNewBotIDs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartnerTypes = `-- name: GetPartnerTypes :many
SELECT id, name, short, icon, created_at FROM partner_types ORDER BY created_at DESC
`

func (q *Queries) GetPartnerTypes(ctx context.Context) ([]PartnerType, error) {
	rows, err := q.db.Query(ctx, getPartnerTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerType
	for rows.Next() {
		var i PartnerType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Short,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPartners = `-- name: GetPartners :many
SELECT id, name, short, links, type, created_at, user_id, bot_id FROM partners ORDER BY created_at DESC
`

type GetPartnersRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Short     string             `db:"short" json:"short"`
	Links     []byte             `db:"links" json:"links"`
	Type      string             `db:"type" json:"type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UserID    string             `db:"user_id" json:"user_id"`
	BotID     pgtype.Text        `db:"bot_id" json:"bot_id"`
}

func (q *Queries) GetPartners(ctx context.Context) ([]GetPartnersRow, error) {
	rows, err := q.db.Query(ctx, getPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPartnersRow
	for rows.Next() {
		var i GetPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Short,
			&i.Links,
			&i.Type,
			&i.CreatedAt,
			&i.UserID,
			&i.BotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPremiumBotIDs = `-- name: GetPremiumBotIDs :many
SELECT bot_id FROM bots WHERE premium = true AND (type = 'approved' OR type = 'certified') ORDER BY created_at DESC LIMIT $1 OFFSET $2
`

type GetPremiumBotIDsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

func (q *Queries) GetPremiumBotIDs(ctx context.Context, arg GetPremiumBotIDsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getPremiumBotIDs, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var bot_id string
		if err := rows.Scan(&bot_id); err != nil {
			return nil, err
		}
		items = append(items, bot_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffTemplateTypes = `-- name: GetStaffTemplateTypes :many
SELECT id, name, icon, short FROM staff_template_types ORDER BY created_at DESC
`

type GetStaffTemplateTypesRow struct {
	ID    string `db:"id" json:"id"`
	Name  string `db:"name" json:"name"`
	Icon  string `db:"icon" json:"icon"`
	Short string `db:"short" json:"short"`
}

func (q *Queries) GetStaffTemplateTypes(ctx context.Context) ([]GetStaffTemplateTypesRow, error) {
	rows, err := q.db.Query(ctx, getStaffTemplateTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffTemplateTypesRow
	for rows.Next() {
		var i GetStaffTemplateTypesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Icon,
			&i.Short,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffTemplates = `-- name: GetStaffTemplates :many
SELECT id, name, emoji, tags, description, type, entity_type, created_at
FROM staff_templates
WHERE $1::text IS NULL OR entity_type = $1
ORDER BY created_at DESC
`

type GetStaffTemplatesRow struct {
	ID          string             `db:"id" json:"id"`
	Name        string             `db:"name" json:"name"`
	Emoji       string             `db:"emoji" json:"emoji"`
	Tags        []string           `db:"tags" json:"tags"`
	Description string             `db:"description" json:"description"`
	Type        string             `db:"type" json:"type"`
	EntityType  string             `db:"entity_type" json:"entity_type"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetStaffTemplates(ctx context.Context, entityType pgtype.Text) ([]GetStaffTemplatesRow, error) {
	rows, err := q.db.Query(ctx, getStaffTemplates, entityType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffTemplatesRow
	for rows.Next() {
		var i GetStaffTemplatesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Emoji,
			&i.Tags,
			&i.Description,
			&i.Type,
			&i.EntityType,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
