// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: packsounds.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPackSounds = `-- name: CountPackSounds :one
SELECT COUNT(*) FROM pack_sounds
`

func (q *Queries) CountPackSounds(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPackSounds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePackSounds = `-- name: DeletePackSounds :exec
DELETE FROM pack_sounds WHERE pack_url = $1
`

func (q *Queries) DeletePackSounds(ctx context.Context, packUrl string) error {
	_, err := q.db.Exec(ctx, deletePackSounds, packUrl)
	return err
}

const getAllPackSoundsPaged = `-- name: GetAllPackSoundsPaged :many
SELECT s.id, s.name, s.duration_ms, s.downloads, s.created_at, s.pack_url, p.name AS pack_name
FROM pack_sounds s
JOIN packs p ON p.url = s.pack_url
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllPackSoundsPagedParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetAllPackSoundsPagedRow struct {
	ID         string             `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	DurationMs int32              `db:"duration_ms" json:"duration_ms"`
	Downloads  int32              `db:"downloads" json:"downloads"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackUrl    string             `db:"pack_url" json:"pack_url"`
	PackName   string             `db:"pack_name" json:"pack_name"`
}

func (q *Queries) GetAllPackSoundsPaged(ctx context.Context, arg GetAllPackSoundsPagedParams) ([]GetAllPackSoundsPagedRow, error) {
	rows, err := q.db.Query(ctx, getAllPackSoundsPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPackSoundsPagedRow
	for rows.Next() {
		var i GetAllPackSoundsPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.Downloads,
			&i.CreatedAt,
			&i.PackUrl,
			&i.PackName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackSoundByID = `-- name: GetPackSoundByID :one
SELECT id, pack_url, name, duration_ms, position, downloads, created_at FROM pack_sounds WHERE id = $1
`

// Backs the standalone /sounds/{id} page -- see GetPackEmojiByID's own
// comment, same reasoning.
func (q *Queries) GetPackSoundByID(ctx context.Context, id string) (PackSound, error) {
	row := q.db.QueryRow(ctx, getPackSoundByID, id)
	var i PackSound
	err := row.Scan(
		&i.ID,
		&i.PackUrl,
		&i.Name,
		&i.DurationMs,
		&i.Position,
		&i.Downloads,
		&i.CreatedAt,
	)
	return i, err
}

const getPackSounds = `-- name: GetPackSounds :many

SELECT id, name, duration_ms, position, downloads, created_at FROM pack_sounds WHERE pack_url = $1 ORDER BY position ASC
`

type GetPackSoundsRow struct {
	ID         string             `db:"id" json:"id"`
	Name       string             `db:"name" json:"name"`
	DurationMs int32              `db:"duration_ms" json:"duration_ms"`
	Position   int32              `db:"position" json:"position"`
	Downloads  int32              `db:"downloads" json:"downloads"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Sound packs' counterpart to the pack_stickers/pack_emojis queries in
// packs.sql/packstickers.sql -- same shape, with `duration_ms` standing in
// for `animated` since it's the audio-specific field that matters here.
func (q *Queries) GetPackSounds(ctx context.Context, packUrl string) ([]GetPackSoundsRow, error) {
	rows, err := q.db.Query(ctx, getPackSounds, packUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackSoundsRow
	for rows.Next() {
		var i GetPackSoundsRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.DurationMs,
			&i.Position,
			&i.Downloads,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPackSoundDownloads = `-- name: IncrementPackSoundDownloads :one
UPDATE pack_sounds SET downloads = downloads + 1 WHERE id = $1 RETURNING downloads
`

func (q *Queries) IncrementPackSoundDownloads(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPackSoundDownloads, id)
	var downloads int32
	err := row.Scan(&downloads)
	return downloads, err
}

const insertPackSound = `-- name: InsertPackSound :exec
INSERT INTO pack_sounds (id, pack_url, name, duration_ms, position, downloads, created_at)
VALUES ($1, $2, $3, $4, $5, COALESCE($6::integer, 0), COALESCE($7::timestamptz, now()))
`

type InsertPackSoundParams struct {
	ID         string             `db:"id" json:"id"`
	PackUrl    string             `db:"pack_url" json:"pack_url"`
	Name       string             `db:"name" json:"name"`
	DurationMs int32              `db:"duration_ms" json:"duration_ms"`
	Position   int32              `db:"position" json:"position"`
	Downloads  pgtype.Int4        `db:"downloads" json:"downloads"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// downloads/created_at are optional -- see InsertPackEmoji's own comment
// in packs.sql, same reasoning.
func (q *Queries) InsertPackSound(ctx context.Context, arg InsertPackSoundParams) error {
	_, err := q.db.Exec(ctx, insertPackSound,
		arg.ID,
		arg.PackUrl,
		arg.Name,
		arg.DurationMs,
		arg.Position,
		arg.Downloads,
		arg.CreatedAt,
	)
	return err
}
