// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: packs.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPackByURL = `-- name: CountPackByURL :one
SELECT COUNT(*) FROM packs WHERE url = $1
`

func (q *Queries) CountPackByURL(ctx context.Context, url string) (int64, error) {
	row := q.db.QueryRow(ctx, countPackByURL, url)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPacks = `-- name: CountPacks :one
SELECT COUNT(*) FROM packs
`

func (q *Queries) CountPacks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPacks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countPacksByType = `-- name: CountPacksByType :one
SELECT COUNT(*) FROM packs WHERE pack_type = $1
`

func (q *Queries) CountPacksByType(ctx context.Context, packType string) (int64, error) {
	row := q.db.QueryRow(ctx, countPacksByType, packType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePack = `-- name: DeletePack :exec
DELETE FROM packs WHERE url = $1
`

func (q *Queries) DeletePack(ctx context.Context, url string) error {
	_, err := q.db.Exec(ctx, deletePack, url)
	return err
}

const deletePackEmojis = `-- name: DeletePackEmojis :exec
DELETE FROM pack_emojis WHERE pack_url = $1
`

func (q *Queries) DeletePackEmojis(ctx context.Context, packUrl string) error {
	_, err := q.db.Exec(ctx, deletePackEmojis, packUrl)
	return err
}

const getAllPacks = `-- name: GetAllPacks :many
SELECT owner, name, short, tags, url, created_at, pack_type, bots, servers, vote_banned
FROM packs
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllPacksParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetAllPacksRow struct {
	Owner      string             `db:"owner" json:"owner"`
	Name       string             `db:"name" json:"name"`
	Short      string             `db:"short" json:"short"`
	Tags       []string           `db:"tags" json:"tags"`
	Url        string             `db:"url" json:"url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackType   string             `db:"pack_type" json:"pack_type"`
	Bots       []string           `db:"bots" json:"bots"`
	Servers    []string           `db:"servers" json:"servers"`
	VoteBanned bool               `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetAllPacks(ctx context.Context, arg GetAllPacksParams) ([]GetAllPacksRow, error) {
	rows, err := q.db.Query(ctx, getAllPacks, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPacksRow
	for rows.Next() {
		var i GetAllPacksRow
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Url,
			&i.CreatedAt,
			&i.PackType,
			&i.Bots,
			&i.Servers,
			&i.VoteBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getAllPacksByType = `-- name: GetAllPacksByType :many
SELECT owner, name, short, tags, url, created_at, pack_type, bots, servers, vote_banned
FROM packs
WHERE pack_type = $1
ORDER BY created_at DESC
LIMIT $2 OFFSET $3
`

type GetAllPacksByTypeParams struct {
	PackType string `db:"pack_type" json:"pack_type"`
	Limit    int32  `db:"limit" json:"limit"`
	Offset   int32  `db:"offset" json:"offset"`
}

type GetAllPacksByTypeRow struct {
	Owner      string             `db:"owner" json:"owner"`
	Name       string             `db:"name" json:"name"`
	Short      string             `db:"short" json:"short"`
	Tags       []string           `db:"tags" json:"tags"`
	Url        string             `db:"url" json:"url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackType   string             `db:"pack_type" json:"pack_type"`
	Bots       []string           `db:"bots" json:"bots"`
	Servers    []string           `db:"servers" json:"servers"`
	VoteBanned bool               `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetAllPacksByType(ctx context.Context, arg GetAllPacksByTypeParams) ([]GetAllPacksByTypeRow, error) {
	rows, err := q.db.Query(ctx, getAllPacksByType, arg.PackType, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPacksByTypeRow
	for rows.Next() {
		var i GetAllPacksByTypeRow
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Url,
			&i.CreatedAt,
			&i.PackType,
			&i.Bots,
			&i.Servers,
			&i.VoteBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackByURL = `-- name: GetPackByURL :one
SELECT owner, name, short, tags, url, created_at, pack_type, bots, servers, vote_banned
FROM packs
WHERE url = $1
`

type GetPackByURLRow struct {
	Owner      string             `db:"owner" json:"owner"`
	Name       string             `db:"name" json:"name"`
	Short      string             `db:"short" json:"short"`
	Tags       []string           `db:"tags" json:"tags"`
	Url        string             `db:"url" json:"url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackType   string             `db:"pack_type" json:"pack_type"`
	Bots       []string           `db:"bots" json:"bots"`
	Servers    []string           `db:"servers" json:"servers"`
	VoteBanned bool               `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetPackByURL(ctx context.Context, url string) (GetPackByURLRow, error) {
	row := q.db.QueryRow(ctx, getPackByURL, url)
	var i GetPackByURLRow
	err := row.Scan(
		&i.Owner,
		&i.Name,
		&i.Short,
		&i.Tags,
		&i.Url,
		&i.CreatedAt,
		&i.PackType,
		&i.Bots,
		&i.Servers,
		&i.VoteBanned,
	)
	return i, err
}

const getPackEmojis = `-- name: GetPackEmojis :many
SELECT id, name, animated, position FROM pack_emojis WHERE pack_url = $1 ORDER BY position ASC
`

type GetPackEmojisRow struct {
	ID       string `db:"id" json:"id"`
	Name     string `db:"name" json:"name"`
	Animated bool   `db:"animated" json:"animated"`
	Position int32  `db:"position" json:"position"`
}

func (q *Queries) GetPackEmojis(ctx context.Context, packUrl string) ([]GetPackEmojisRow, error) {
	rows, err := q.db.Query(ctx, getPackEmojis, packUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackEmojisRow
	for rows.Next() {
		var i GetPackEmojisRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Animated,
			&i.Position,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackOwner = `-- name: GetPackOwner :one
SELECT owner FROM packs WHERE url = $1
`

func (q *Queries) GetPackOwner(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRow(ctx, getPackOwner, url)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const getPackOwnerAndType = `-- name: GetPackOwnerAndType :one
SELECT owner, pack_type FROM packs WHERE url = $1
`

type GetPackOwnerAndTypeRow struct {
	Owner    string `db:"owner" json:"owner"`
	PackType string `db:"pack_type" json:"pack_type"`
}

func (q *Queries) GetPackOwnerAndType(ctx context.Context, url string) (GetPackOwnerAndTypeRow, error) {
	row := q.db.QueryRow(ctx, getPackOwnerAndType, url)
	var i GetPackOwnerAndTypeRow
	err := row.Scan(&i.Owner, &i.PackType)
	return i, err
}

const getPackSEO = `-- name: GetPackSEO :one
SELECT name, short FROM packs WHERE url = $1
`

type GetPackSEORow struct {
	Name  string `db:"name" json:"name"`
	Short string `db:"short" json:"short"`
}

func (q *Queries) GetPackSEO(ctx context.Context, url string) (GetPackSEORow, error) {
	row := q.db.QueryRow(ctx, getPackSEO, url)
	var i GetPackSEORow
	err := row.Scan(&i.Name, &i.Short)
	return i, err
}

const getRecentPacks = `-- name: GetRecentPacks :many
SELECT owner, name, short, tags, url, created_at, pack_type, bots, servers, vote_banned
FROM packs
ORDER BY created_at DESC
LIMIT 12
`

type GetRecentPacksRow struct {
	Owner      string             `db:"owner" json:"owner"`
	Name       string             `db:"name" json:"name"`
	Short      string             `db:"short" json:"short"`
	Tags       []string           `db:"tags" json:"tags"`
	Url        string             `db:"url" json:"url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackType   string             `db:"pack_type" json:"pack_type"`
	Bots       []string           `db:"bots" json:"bots"`
	Servers    []string           `db:"servers" json:"servers"`
	VoteBanned bool               `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetRecentPacks(ctx context.Context) ([]GetRecentPacksRow, error) {
	rows, err := q.db.Query(ctx, getRecentPacks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentPacksRow
	for rows.Next() {
		var i GetRecentPacksRow
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Url,
			&i.CreatedAt,
			&i.PackType,
			&i.Bots,
			&i.Servers,
			&i.VoteBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserPacksByOwner = `-- name: GetUserPacksByOwner :many
SELECT owner, name, short, tags, url, created_at, pack_type, bots, servers, vote_banned
FROM packs
WHERE owner = $1
ORDER BY created_at DESC
`

type GetUserPacksByOwnerRow struct {
	Owner      string             `db:"owner" json:"owner"`
	Name       string             `db:"name" json:"name"`
	Short      string             `db:"short" json:"short"`
	Tags       []string           `db:"tags" json:"tags"`
	Url        string             `db:"url" json:"url"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackType   string             `db:"pack_type" json:"pack_type"`
	Bots       []string           `db:"bots" json:"bots"`
	Servers    []string           `db:"servers" json:"servers"`
	VoteBanned bool               `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetUserPacksByOwner(ctx context.Context, owner string) ([]GetUserPacksByOwnerRow, error) {
	rows, err := q.db.Query(ctx, getUserPacksByOwner, owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserPacksByOwnerRow
	for rows.Next() {
		var i GetUserPacksByOwnerRow
		if err := rows.Scan(
			&i.Owner,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Url,
			&i.CreatedAt,
			&i.PackType,
			&i.Bots,
			&i.Servers,
			&i.VoteBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertPack = `-- name: InsertPack :exec
INSERT INTO packs (name, url, short, tags, bots, servers, owner, pack_type) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
`

type InsertPackParams struct {
	Name     string   `db:"name" json:"name"`
	Url      string   `db:"url" json:"url"`
	Short    string   `db:"short" json:"short"`
	Tags     []string `db:"tags" json:"tags"`
	Bots     []string `db:"bots" json:"bots"`
	Servers  []string `db:"servers" json:"servers"`
	Owner    string   `db:"owner" json:"owner"`
	PackType string   `db:"pack_type" json:"pack_type"`
}

func (q *Queries) InsertPack(ctx context.Context, arg InsertPackParams) error {
	_, err := q.db.Exec(ctx, insertPack,
		arg.Name,
		arg.Url,
		arg.Short,
		arg.Tags,
		arg.Bots,
		arg.Servers,
		arg.Owner,
		arg.PackType,
	)
	return err
}

const insertPackEmoji = `-- name: InsertPackEmoji :exec
INSERT INTO pack_emojis (id, pack_url, name, animated, position) VALUES ($1, $2, $3, $4, $5)
`

type InsertPackEmojiParams struct {
	ID       string `db:"id" json:"id"`
	PackUrl  string `db:"pack_url" json:"pack_url"`
	Name     string `db:"name" json:"name"`
	Animated bool   `db:"animated" json:"animated"`
	Position int32  `db:"position" json:"position"`
}

func (q *Queries) InsertPackEmoji(ctx context.Context, arg InsertPackEmojiParams) error {
	_, err := q.db.Exec(ctx, insertPackEmoji,
		arg.ID,
		arg.PackUrl,
		arg.Name,
		arg.Animated,
		arg.Position,
	)
	return err
}

const searchPacksQueue = `-- name: SearchPacksQueue :many
SELECT url, name, short, pack_type, owner, tags, vote_banned
FROM packs WHERE url = $1::text OR name ILIKE $2::text ORDER BY created_at
`

type SearchPacksQueueParams struct {
	Query   string `db:"query" json:"query"`
	Pattern string `db:"pattern" json:"pattern"`
}

type SearchPacksQueueRow struct {
	Url        string   `db:"url" json:"url"`
	Name       string   `db:"name" json:"name"`
	Short      string   `db:"short" json:"short"`
	PackType   string   `db:"pack_type" json:"pack_type"`
	Owner      string   `db:"owner" json:"owner"`
	Tags       []string `db:"tags" json:"tags"`
	VoteBanned bool     `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SearchPacksQueue(ctx context.Context, arg SearchPacksQueueParams) ([]SearchPacksQueueRow, error) {
	rows, err := q.db.Query(ctx, searchPacksQueue, arg.Query, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchPacksQueueRow
	for rows.Next() {
		var i SearchPacksQueueRow
		if err := rows.Scan(
			&i.Url,
			&i.Name,
			&i.Short,
			&i.PackType,
			&i.Owner,
			&i.Tags,
			&i.VoteBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setPackVoteBanned = `-- name: SetPackVoteBanned :exec
UPDATE packs SET vote_banned = $2 WHERE url = $1
`

type SetPackVoteBannedParams struct {
	Url        string `db:"url" json:"url"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SetPackVoteBanned(ctx context.Context, arg SetPackVoteBannedParams) error {
	_, err := q.db.Exec(ctx, setPackVoteBanned, arg.Url, arg.VoteBanned)
	return err
}

const updatePack = `-- name: UpdatePack :exec
UPDATE packs SET name = $1, short = $2, tags = $3, bots = $4, servers = $5 WHERE url = $6
`

type UpdatePackParams struct {
	Name    string   `db:"name" json:"name"`
	Short   string   `db:"short" json:"short"`
	Tags    []string `db:"tags" json:"tags"`
	Bots    []string `db:"bots" json:"bots"`
	Servers []string `db:"servers" json:"servers"`
	Url     string   `db:"url" json:"url"`
}

func (q *Queries) UpdatePack(ctx context.Context, arg UpdatePackParams) error {
	_, err := q.db.Exec(ctx, updatePack,
		arg.Name,
		arg.Short,
		arg.Tags,
		arg.Bots,
		arg.Servers,
		arg.Url,
	)
	return err
}
