// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: packstickers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPackStickers = `-- name: CountPackStickers :one
SELECT COUNT(*) FROM pack_stickers
`

func (q *Queries) CountPackStickers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countPackStickers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deletePackStickers = `-- name: DeletePackStickers :exec
DELETE FROM pack_stickers WHERE pack_url = $1
`

func (q *Queries) DeletePackStickers(ctx context.Context, packUrl string) error {
	_, err := q.db.Exec(ctx, deletePackStickers, packUrl)
	return err
}

const getAllPackStickersPaged = `-- name: GetAllPackStickersPaged :many
SELECT s.id, s.name, s.animated, s.downloads, s.created_at, s.pack_url, p.name AS pack_name
FROM pack_stickers s
JOIN packs p ON p.url = s.pack_url
ORDER BY s.created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllPackStickersPagedParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetAllPackStickersPagedRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Animated  bool               `db:"animated" json:"animated"`
	Downloads int32              `db:"downloads" json:"downloads"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	PackUrl   string             `db:"pack_url" json:"pack_url"`
	PackName  string             `db:"pack_name" json:"pack_name"`
}

func (q *Queries) GetAllPackStickersPaged(ctx context.Context, arg GetAllPackStickersPagedParams) ([]GetAllPackStickersPagedRow, error) {
	rows, err := q.db.Query(ctx, getAllPackStickersPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAllPackStickersPagedRow
	for rows.Next() {
		var i GetAllPackStickersPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Animated,
			&i.Downloads,
			&i.CreatedAt,
			&i.PackUrl,
			&i.PackName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackStickerByID = `-- name: GetPackStickerByID :one
SELECT id, pack_url, name, animated, position, downloads, created_at FROM pack_stickers WHERE id = $1
`

// Backs the standalone /stickers/{id} page -- see GetPackEmojiByID's own
// comment, same reasoning.
func (q *Queries) GetPackStickerByID(ctx context.Context, id string) (PackSticker, error) {
	row := q.db.QueryRow(ctx, getPackStickerByID, id)
	var i PackSticker
	err := row.Scan(
		&i.ID,
		&i.PackUrl,
		&i.Name,
		&i.Animated,
		&i.Position,
		&i.Downloads,
		&i.CreatedAt,
	)
	return i, err
}

const getPackStickers = `-- name: GetPackStickers :many

SELECT id, name, animated, position, downloads, created_at FROM pack_stickers WHERE pack_url = $1 ORDER BY position ASC
`

type GetPackStickersRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Animated  bool               `db:"animated" json:"animated"`
	Position  int32              `db:"position" json:"position"`
	Downloads int32              `db:"downloads" json:"downloads"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// Sticker packs' counterpart to the pack_emojis queries in packs.sql --
// kept in their own file rather than folded into packs.sql, since this is
// a whole second set of CRUD + standalone-lookup queries, not one or two
// additions.
func (q *Queries) GetPackStickers(ctx context.Context, packUrl string) ([]GetPackStickersRow, error) {
	rows, err := q.db.Query(ctx, getPackStickers, packUrl)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPackStickersRow
	for rows.Next() {
		var i GetPackStickersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Animated,
			&i.Position,
			&i.Downloads,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const incrementPackStickerDownloads = `-- name: IncrementPackStickerDownloads :one
UPDATE pack_stickers SET downloads = downloads + 1 WHERE id = $1 RETURNING downloads
`

func (q *Queries) IncrementPackStickerDownloads(ctx context.Context, id string) (int32, error) {
	row := q.db.QueryRow(ctx, incrementPackStickerDownloads, id)
	var downloads int32
	err := row.Scan(&downloads)
	return downloads, err
}

const insertPackSticker = `-- name: InsertPackSticker :exec
INSERT INTO pack_stickers (id, pack_url, name, animated, position, downloads, created_at)
VALUES ($1, $2, $3, $4, $5, COALESCE($6::integer, 0), COALESCE($7::timestamptz, now()))
`

type InsertPackStickerParams struct {
	ID        string             `db:"id" json:"id"`
	PackUrl   string             `db:"pack_url" json:"pack_url"`
	Name      string             `db:"name" json:"name"`
	Animated  bool               `db:"animated" json:"animated"`
	Position  int32              `db:"position" json:"position"`
	Downloads pgtype.Int4        `db:"downloads" json:"downloads"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

// downloads/created_at are optional -- see InsertPackEmoji's own comment
// in packs.sql, same reasoning.
func (q *Queries) InsertPackSticker(ctx context.Context, arg InsertPackStickerParams) error {
	_, err := q.db.Exec(ctx, insertPackSticker,
		arg.ID,
		arg.PackUrl,
		arg.Name,
		arg.Animated,
		arg.Position,
		arg.Downloads,
		arg.CreatedAt,
	)
	return err
}
