// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: panel.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPartnerByID = `-- name: CountPartnerByID :one
SELECT EXISTS(SELECT 1 FROM partners WHERE id = $1)
`

func (q *Queries) CountPartnerByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countPartnerByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countPartnerTypeByID = `-- name: CountPartnerTypeByID :one

SELECT EXISTS(SELECT 1 FROM partner_types WHERE id = $1)
`

// Panel-only queries with no other natural home (arcadia/panel ops_content.go).
func (q *Queries) CountPartnerTypeByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countPartnerTypeByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const deletePartner = `-- name: DeletePartner :exec
DELETE FROM partners WHERE id = $1
`

func (q *Queries) DeletePartner(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deletePartner, id)
	return err
}

const insertPartner = `-- name: InsertPartner :exec
INSERT INTO partners (id, name, short, links, type, user_id, bot_id) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertPartnerParams struct {
	ID     string      `db:"id" json:"id"`
	Name   string      `db:"name" json:"name"`
	Short  string      `db:"short" json:"short"`
	Links  []byte      `db:"links" json:"links"`
	Type   string      `db:"type" json:"type"`
	UserID string      `db:"user_id" json:"user_id"`
	BotID  pgtype.Text `db:"bot_id" json:"bot_id"`
}

func (q *Queries) InsertPartner(ctx context.Context, arg InsertPartnerParams) error {
	_, err := q.db.Exec(ctx, insertPartner,
		arg.ID,
		arg.Name,
		arg.Short,
		arg.Links,
		arg.Type,
		arg.UserID,
		arg.BotID,
	)
	return err
}

const listPartnerTypes = `-- name: ListPartnerTypes :many
SELECT id, name, short, icon, created_at FROM partner_types
`

func (q *Queries) ListPartnerTypes(ctx context.Context) ([]PartnerType, error) {
	rows, err := q.db.Query(ctx, listPartnerTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PartnerType
	for rows.Next() {
		var i PartnerType
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Short,
			&i.Icon,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPartners = `-- name: ListPartners :many
SELECT id, name, short, links, type, created_at, user_id, bot_id FROM partners
`

type ListPartnersRow struct {
	ID        string             `db:"id" json:"id"`
	Name      string             `db:"name" json:"name"`
	Short     string             `db:"short" json:"short"`
	Links     []byte             `db:"links" json:"links"`
	Type      string             `db:"type" json:"type"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UserID    string             `db:"user_id" json:"user_id"`
	BotID     pgtype.Text        `db:"bot_id" json:"bot_id"`
}

func (q *Queries) ListPartners(ctx context.Context) ([]ListPartnersRow, error) {
	rows, err := q.db.Query(ctx, listPartners)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPartnersRow
	for rows.Next() {
		var i ListPartnersRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Short,
			&i.Links,
			&i.Type,
			&i.CreatedAt,
			&i.UserID,
			&i.BotID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updatePartner = `-- name: UpdatePartner :exec
UPDATE partners SET name = $2, short = $3, links = $4, type = $5, user_id = $6, bot_id = $7 WHERE id = $1
`

type UpdatePartnerParams struct {
	ID     string      `db:"id" json:"id"`
	Name   string      `db:"name" json:"name"`
	Short  string      `db:"short" json:"short"`
	Links  []byte      `db:"links" json:"links"`
	Type   string      `db:"type" json:"type"`
	UserID string      `db:"user_id" json:"user_id"`
	BotID  pgtype.Text `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdatePartner(ctx context.Context, arg UpdatePartnerParams) error {
	_, err := q.db.Exec(ctx, updatePartner,
		arg.ID,
		arg.Name,
		arg.Short,
		arg.Links,
		arg.Type,
		arg.UserID,
		arg.BotID,
	)
	return err
}
