// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: payments.sql

package db

import (
	"context"
)

const countBotByID = `-- name: CountBotByID :one

SELECT COUNT(*) FROM bots WHERE bot_id = $1
`

// The target of a premium purchase is always either a bot or a server
// (validated up front by entityTarget in routes/payments/assets/give_perks.go),
// never an unvalidated table name -- but sqlc needs a static table per query,
// so this is one explicit pair per entity type rather than one
// dynamically-templated query.
func (q *Queries) CountBotByID(ctx context.Context, botID string) (int64, error) {
	row := q.db.QueryRow(ctx, countBotByID, botID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServerByID = `-- name: CountServerByID :one
SELECT COUNT(*) FROM servers WHERE server_id = $1
`

func (q *Queries) CountServerByID(ctx context.Context, serverID string) (int64, error) {
	row := q.db.QueryRow(ctx, countServerByID, serverID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBotTypePremium = `-- name: GetBotTypePremium :one
SELECT type, premium FROM bots WHERE bot_id = $1
`

type GetBotTypePremiumRow struct {
	Type    string `db:"type" json:"type"`
	Premium bool   `db:"premium" json:"premium"`
}

func (q *Queries) GetBotTypePremium(ctx context.Context, botID string) (GetBotTypePremiumRow, error) {
	row := q.db.QueryRow(ctx, getBotTypePremium, botID)
	var i GetBotTypePremiumRow
	err := row.Scan(&i.Type, &i.Premium)
	return i, err
}

const getServerTypePremium = `-- name: GetServerTypePremium :one
SELECT type, premium FROM servers WHERE server_id = $1
`

type GetServerTypePremiumRow struct {
	Type    string `db:"type" json:"type"`
	Premium bool   `db:"premium" json:"premium"`
}

func (q *Queries) GetServerTypePremium(ctx context.Context, serverID string) (GetServerTypePremiumRow, error) {
	row := q.db.QueryRow(ctx, getServerTypePremium, serverID)
	var i GetServerTypePremiumRow
	err := row.Scan(&i.Type, &i.Premium)
	return i, err
}
