// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reminders.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countUserReminder = `-- name: CountUserReminder :one
SELECT COUNT(*) FROM user_reminders WHERE user_id = $1 AND target_id = $2 AND target_type = $3
`

type CountUserReminderParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) CountUserReminder(ctx context.Context, arg CountUserReminderParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserReminder, arg.UserID, arg.TargetID, arg.TargetType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserReminder = `-- name: DeleteUserReminder :exec
DELETE FROM user_reminders WHERE user_id = $1 AND target_id = $2 AND target_type = $3
`

type DeleteUserReminderParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) DeleteUserReminder(ctx context.Context, arg DeleteUserReminderParams) error {
	_, err := q.db.Exec(ctx, deleteUserReminder, arg.UserID, arg.TargetID, arg.TargetType)
	return err
}

const getStaleUserReminders = `-- name: GetStaleUserReminders :many
SELECT user_id, target_id, target_type
FROM user_reminders
WHERE NOW() - last_acked > interval '4 hours'
`

type GetStaleUserRemindersRow struct {
	UserID     string `db:"user_id" json:"user_id"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) GetStaleUserReminders(ctx context.Context) ([]GetStaleUserRemindersRow, error) {
	rows, err := q.db.Query(ctx, getStaleUserReminders)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaleUserRemindersRow
	for rows.Next() {
		var i GetStaleUserRemindersRow
		if err := rows.Scan(&i.UserID, &i.TargetID, &i.TargetType); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserReminders = `-- name: GetUserReminders :many
SELECT user_id, target_type, target_id, created_at, last_acked
FROM user_reminders
WHERE user_id = $1
`

type GetUserRemindersRow struct {
	UserID     string             `db:"user_id" json:"user_id"`
	TargetType string             `db:"target_type" json:"target_type"`
	TargetID   string             `db:"target_id" json:"target_id"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	LastAcked  pgtype.Timestamptz `db:"last_acked" json:"last_acked"`
}

func (q *Queries) GetUserReminders(ctx context.Context, userID string) ([]GetUserRemindersRow, error) {
	rows, err := q.db.Query(ctx, getUserReminders, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserRemindersRow
	for rows.Next() {
		var i GetUserRemindersRow
		if err := rows.Scan(
			&i.UserID,
			&i.TargetType,
			&i.TargetID,
			&i.CreatedAt,
			&i.LastAcked,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertUserReminder = `-- name: InsertUserReminder :exec
INSERT INTO user_reminders (user_id, target_id, target_type) VALUES ($1, $2, $3)
`

type InsertUserReminderParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) InsertUserReminder(ctx context.Context, arg InsertUserReminderParams) error {
	_, err := q.db.Exec(ctx, insertUserReminder, arg.UserID, arg.TargetID, arg.TargetType)
	return err
}

const touchUserReminder = `-- name: TouchUserReminder :exec
UPDATE user_reminders SET last_acked = NOW() WHERE user_id = $1 AND target_id = $2 AND target_type = $3
`

type TouchUserReminderParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) TouchUserReminder(ctx context.Context, arg TouchUserReminderParams) error {
	_, err := q.db.Exec(ctx, touchUserReminder, arg.UserID, arg.TargetID, arg.TargetType)
	return err
}
