// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: reports.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const botExists = `-- name: BotExists :one

SELECT EXISTS(SELECT 1 FROM bots WHERE bot_id = $1)
`

// Report-target existence/name lookups, one per reportable entity type
// (popplio/reports.GetTargetInfo dispatches to the right one -- sqlc needs
// a static table per query, same reasoning as db/queries/payments.sql).
func (q *Queries) BotExists(ctx context.Context, botID string) (bool, error) {
	row := q.db.QueryRow(ctx, botExists, botID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countDailyReports = `-- name: CountDailyReports :one
SELECT COUNT(*) FROM reports WHERE reporter_id = $1 AND created_at > NOW() - INTERVAL '24 hours'
`

func (q *Queries) CountDailyReports(ctx context.Context, reporterID string) (int64, error) {
	row := q.db.QueryRow(ctx, countDailyReports, reporterID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPackName = `-- name: GetPackName :one
SELECT name FROM packs WHERE url = $1
`

func (q *Queries) GetPackName(ctx context.Context, url string) (string, error) {
	row := q.db.QueryRow(ctx, getPackName, url)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getReportStats = `-- name: GetReportStats :many
SELECT reason, status, COUNT(*) AS count FROM reports GROUP BY reason, status ORDER BY reason, status
`

type GetReportStatsRow struct {
	Reason string `db:"reason" json:"reason"`
	Status string `db:"status" json:"status"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) GetReportStats(ctx context.Context) ([]GetReportStatsRow, error) {
	rows, err := q.db.Query(ctx, getReportStats)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetReportStatsRow
	for rows.Next() {
		var i GetReportStatsRow
		if err := rows.Scan(&i.Reason, &i.Status, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerName = `-- name: GetServerName :one
SELECT name FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerName(ctx context.Context, serverID string) (string, error) {
	row := q.db.QueryRow(ctx, getServerName, serverID)
	var name string
	err := row.Scan(&name)
	return name, err
}

const getTeamName = `-- name: GetTeamName :one
SELECT name FROM teams WHERE id = $1
`

func (q *Queries) GetTeamName(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTeamName, id)
	var name string
	err := row.Scan(&name)
	return name, err
}

const insertAutoReport = `-- name: InsertAutoReport :exec
INSERT INTO reports (target_type, target_id, reporter_id, reason, description) VALUES ($1, $2, $3, 'tos_violation', $4) ON CONFLICT DO NOTHING
`

type InsertAutoReportParams struct {
	TargetType  string `db:"target_type" json:"target_type"`
	TargetID    string `db:"target_id" json:"target_id"`
	ReporterID  string `db:"reporter_id" json:"reporter_id"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) InsertAutoReport(ctx context.Context, arg InsertAutoReportParams) error {
	_, err := q.db.Exec(ctx, insertAutoReport,
		arg.TargetType,
		arg.TargetID,
		arg.ReporterID,
		arg.Description,
	)
	return err
}

const insertReport = `-- name: InsertReport :exec
INSERT INTO reports (target_type, target_id, reporter_id, reason, description) VALUES ($1, $2, $3, $4, $5)
`

type InsertReportParams struct {
	TargetType  string `db:"target_type" json:"target_type"`
	TargetID    string `db:"target_id" json:"target_id"`
	ReporterID  string `db:"reporter_id" json:"reporter_id"`
	Reason      string `db:"reason" json:"reason"`
	Description string `db:"description" json:"description"`
}

func (q *Queries) InsertReport(ctx context.Context, arg InsertReportParams) error {
	_, err := q.db.Exec(ctx, insertReport,
		arg.TargetType,
		arg.TargetID,
		arg.ReporterID,
		arg.Reason,
		arg.Description,
	)
	return err
}

const listReports = `-- name: ListReports :many
SELECT id, target_type, target_id, reporter_id, reason, description, status, resolved_by, resolution_note, created_at, resolved_at
FROM reports
WHERE $1::text IS NULL OR status = $1
ORDER BY created_at DESC
`

func (q *Queries) ListReports(ctx context.Context, status pgtype.Text) ([]Report, error) {
	rows, err := q.db.Query(ctx, listReports, status)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Report
	for rows.Next() {
		var i Report
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.ReporterID,
			&i.Reason,
			&i.Description,
			&i.Status,
			&i.ResolvedBy,
			&i.ResolutionNote,
			&i.CreatedAt,
			&i.ResolvedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveReportReturningReporter = `-- name: ResolveReportReturningReporter :one
UPDATE reports SET status = $1, resolved_by = $2, resolution_note = $3, resolved_at = NOW()
WHERE id = $4 AND status IN ('open', 'under_review')
RETURNING reporter_id
`

type ResolveReportReturningReporterParams struct {
	Status         string      `db:"status" json:"status"`
	ResolvedBy     pgtype.Text `db:"resolved_by" json:"resolved_by"`
	ResolutionNote pgtype.Text `db:"resolution_note" json:"resolution_note"`
	ID             pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) ResolveReportReturningReporter(ctx context.Context, arg ResolveReportReturningReporterParams) (string, error) {
	row := q.db.QueryRow(ctx, resolveReportReturningReporter,
		arg.Status,
		arg.ResolvedBy,
		arg.ResolutionNote,
		arg.ID,
	)
	var reporter_id string
	err := row.Scan(&reporter_id)
	return reporter_id, err
}
