// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: servertemplatereactions.sql

package db

import (
	"context"
)

const deleteServerTemplateReaction = `-- name: DeleteServerTemplateReaction :exec
DELETE FROM server_template_reactions WHERE template_id = $1 AND user_id = $2
`

type DeleteServerTemplateReactionParams struct {
	TemplateID string `db:"template_id" json:"template_id"`
	UserID     string `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteServerTemplateReaction(ctx context.Context, arg DeleteServerTemplateReactionParams) error {
	_, err := q.db.Exec(ctx, deleteServerTemplateReaction, arg.TemplateID, arg.UserID)
	return err
}

const getServerTemplateReactionCounts = `-- name: GetServerTemplateReactionCounts :one
SELECT
    COUNT(*) FILTER (WHERE liked) AS likes,
    COUNT(*) FILTER (WHERE NOT liked) AS dislikes
FROM server_template_reactions
WHERE template_id = $1
`

type GetServerTemplateReactionCountsRow struct {
	Likes    int64 `db:"likes" json:"likes"`
	Dislikes int64 `db:"dislikes" json:"dislikes"`
}

func (q *Queries) GetServerTemplateReactionCounts(ctx context.Context, templateID string) (GetServerTemplateReactionCountsRow, error) {
	row := q.db.QueryRow(ctx, getServerTemplateReactionCounts, templateID)
	var i GetServerTemplateReactionCountsRow
	err := row.Scan(&i.Likes, &i.Dislikes)
	return i, err
}

const getUserServerTemplateReaction = `-- name: GetUserServerTemplateReaction :one
SELECT liked FROM server_template_reactions WHERE template_id = $1 AND user_id = $2
`

type GetUserServerTemplateReactionParams struct {
	TemplateID string `db:"template_id" json:"template_id"`
	UserID     string `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserServerTemplateReaction(ctx context.Context, arg GetUserServerTemplateReactionParams) (bool, error) {
	row := q.db.QueryRow(ctx, getUserServerTemplateReaction, arg.TemplateID, arg.UserID)
	var liked bool
	err := row.Scan(&liked)
	return liked, err
}

const upsertServerTemplateReaction = `-- name: UpsertServerTemplateReaction :exec
INSERT INTO server_template_reactions (template_id, user_id, liked)
VALUES ($1, $2, $3)
ON CONFLICT (template_id, user_id) DO UPDATE SET liked = $3
`

type UpsertServerTemplateReactionParams struct {
	TemplateID string `db:"template_id" json:"template_id"`
	UserID     string `db:"user_id" json:"user_id"`
	Liked      bool   `db:"liked" json:"liked"`
}

func (q *Queries) UpsertServerTemplateReaction(ctx context.Context, arg UpsertServerTemplateReactionParams) error {
	_, err := q.db.Exec(ctx, upsertServerTemplateReaction, arg.TemplateID, arg.UserID, arg.Liked)
	return err
}
