// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: servertemplates.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countServerTemplateByCode = `-- name: CountServerTemplateByCode :one
SELECT EXISTS(SELECT 1 FROM server_templates WHERE code = $1)
`

func (q *Queries) CountServerTemplateByCode(ctx context.Context, code string) (bool, error) {
	row := q.db.QueryRow(ctx, countServerTemplateByCode, code)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countServerTemplateByID = `-- name: CountServerTemplateByID :one
SELECT EXISTS(SELECT 1 FROM server_templates WHERE id = $1)
`

func (q *Queries) CountServerTemplateByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countServerTemplateByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countServerTemplatesFiltered = `-- name: CountServerTemplatesFiltered :one
SELECT COUNT(*) FROM server_templates
WHERE (cardinality($1::text[]) = 0 OR tags && $1::text[])
AND ($2::text = '' OR owner = $2)
`

type CountServerTemplatesFilteredParams struct {
	Tags  []string `db:"tags" json:"tags"`
	Owner string   `db:"owner" json:"owner"`
}

func (q *Queries) CountServerTemplatesFiltered(ctx context.Context, arg CountServerTemplatesFilteredParams) (int64, error) {
	row := q.db.QueryRow(ctx, countServerTemplatesFiltered, arg.Tags, arg.Owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteServerTemplate = `-- name: DeleteServerTemplate :exec
DELETE FROM server_templates WHERE id = $1
`

func (q *Queries) DeleteServerTemplate(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteServerTemplate, id)
	return err
}

const getServerTemplateByID = `-- name: GetServerTemplateByID :one
SELECT id, code, name, short, tags, nsfw, owner, usage_count, created_at, updated_at, channels, roles
FROM server_templates WHERE id = $1
`

// The single-fetch (detail page) query only -- channels/roles are a
// meaningful chunk of JSON per row, so the list query below deliberately
// doesn't select them; a browse grid has no use for them.
func (q *Queries) GetServerTemplateByID(ctx context.Context, id string) (ServerTemplate, error) {
	row := q.db.QueryRow(ctx, getServerTemplateByID, id)
	var i ServerTemplate
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Short,
		&i.Tags,
		&i.Nsfw,
		&i.Owner,
		&i.UsageCount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.Channels,
		&i.Roles,
	)
	return i, err
}

const getServerTemplateOwner = `-- name: GetServerTemplateOwner :one
SELECT owner FROM server_templates WHERE id = $1
`

func (q *Queries) GetServerTemplateOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getServerTemplateOwner, id)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const getServerTemplatesPaged = `-- name: GetServerTemplatesPaged :many
SELECT id, code, name, short, tags, nsfw, owner, usage_count, created_at, updated_at
FROM server_templates
WHERE (cardinality($3::text[]) = 0 OR tags && $3::text[])
AND ($4::text = '' OR owner = $4)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetServerTemplatesPagedParams struct {
	Limit  int32    `db:"limit" json:"limit"`
	Offset int32    `db:"offset" json:"offset"`
	Tags   []string `db:"tags" json:"tags"`
	Owner  string   `db:"owner" json:"owner"`
}

type GetServerTemplatesPagedRow struct {
	ID         string             `db:"id" json:"id"`
	Code       string             `db:"code" json:"code"`
	Name       string             `db:"name" json:"name"`
	Short      string             `db:"short" json:"short"`
	Tags       []string           `db:"tags" json:"tags"`
	Nsfw       bool               `db:"nsfw" json:"nsfw"`
	Owner      string             `db:"owner" json:"owner"`
	UsageCount int32              `db:"usage_count" json:"usage_count"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt  pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetServerTemplatesPaged(ctx context.Context, arg GetServerTemplatesPagedParams) ([]GetServerTemplatesPagedRow, error) {
	rows, err := q.db.Query(ctx, getServerTemplatesPaged,
		arg.Limit,
		arg.Offset,
		arg.Tags,
		arg.Owner,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServerTemplatesPagedRow
	for rows.Next() {
		var i GetServerTemplatesPagedRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Nsfw,
			&i.Owner,
			&i.UsageCount,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertServerTemplate = `-- name: InsertServerTemplate :one
INSERT INTO server_templates (code, name, short, tags, nsfw, owner, usage_count, channels, roles)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING id
`

type InsertServerTemplateParams struct {
	Code       string   `db:"code" json:"code"`
	Name       string   `db:"name" json:"name"`
	Short      string   `db:"short" json:"short"`
	Tags       []string `db:"tags" json:"tags"`
	Nsfw       bool     `db:"nsfw" json:"nsfw"`
	Owner      string   `db:"owner" json:"owner"`
	UsageCount int32    `db:"usage_count" json:"usage_count"`
	Channels   []byte   `db:"channels" json:"channels"`
	Roles      []byte   `db:"roles" json:"roles"`
}

func (q *Queries) InsertServerTemplate(ctx context.Context, arg InsertServerTemplateParams) (string, error) {
	row := q.db.QueryRow(ctx, insertServerTemplate,
		arg.Code,
		arg.Name,
		arg.Short,
		arg.Tags,
		arg.Nsfw,
		arg.Owner,
		arg.UsageCount,
		arg.Channels,
		arg.Roles,
	)
	var id string
	err := row.Scan(&id)
	return id, err
}

const updateServerTemplate = `-- name: UpdateServerTemplate :exec
UPDATE server_templates
SET short = $2, tags = $3, nsfw = $4, updated_at = now()
WHERE id = $1
`

type UpdateServerTemplateParams struct {
	ID    string   `db:"id" json:"id"`
	Short string   `db:"short" json:"short"`
	Tags  []string `db:"tags" json:"tags"`
	Nsfw  bool     `db:"nsfw" json:"nsfw"`
}

// Deliberately omits name -- it's pulled from Discord's own template
// metadata at submission time (see add_server_template), not
// independently settable, so it isn't part of what an owner can edit
// here. channels/roles are excluded too; re-syncing those from Discord
// is a separate, larger feature.
func (q *Queries) UpdateServerTemplate(ctx context.Context, arg UpdateServerTemplateParams) error {
	_, err := q.db.Exec(ctx, updateServerTemplate,
		arg.ID,
		arg.Short,
		arg.Tags,
		arg.Nsfw,
	)
	return err
}
