// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: servers.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
	"popplio/types"
	"time"
)

const appendServerUniqueClick = `-- name: AppendServerUniqueClick :exec
UPDATE servers SET unique_clicks = array_append(unique_clicks, $1) WHERE server_id = $2
`

type AppendServerUniqueClickParams struct {
	ArrayAppend interface{} `db:"array_append" json:"array_append"`
	ServerID    string      `db:"server_id" json:"server_id"`
}

func (q *Queries) AppendServerUniqueClick(ctx context.Context, arg AppendServerUniqueClickParams) error {
	_, err := q.db.Exec(ctx, appendServerUniqueClick, arg.ArrayAppend, arg.ServerID)
	return err
}

const approveServer = `-- name: ApproveServer :exec
UPDATE servers SET type = 'approved', claimed_by = NULL WHERE server_id = $1
`

func (q *Queries) ApproveServer(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, approveServer, serverID)
	return err
}

const certifyServer = `-- name: CertifyServer :exec
UPDATE servers SET type = 'certified' WHERE server_id = $1
`

func (q *Queries) CertifyServer(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, certifyServer, serverID)
	return err
}

const checkServerHasUniqueClick = `-- name: CheckServerHasUniqueClick :one
SELECT $1::text = ANY(unique_clicks) FROM servers WHERE server_id = $2::text
`

type CheckServerHasUniqueClickParams struct {
	HashedIp string `db:"hashed_ip" json:"hashed_ip"`
	ServerID string `db:"server_id" json:"server_id"`
}

func (q *Queries) CheckServerHasUniqueClick(ctx context.Context, arg CheckServerHasUniqueClickParams) (bool, error) {
	row := q.db.QueryRow(ctx, checkServerHasUniqueClick, arg.HashedIp, arg.ServerID)
	var column_1 bool
	err := row.Scan(&column_1)
	return column_1, err
}

const clearServerFeaturedUntil = `-- name: ClearServerFeaturedUntil :exec
UPDATE servers SET featured_until = NULL WHERE server_id = $1
`

func (q *Queries) ClearServerFeaturedUntil(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, clearServerFeaturedUntil, serverID)
	return err
}

const clearServerSpotlightedUntil = `-- name: ClearServerSpotlightedUntil :exec
UPDATE servers SET spotlighted_until = NULL WHERE server_id = $1
`

func (q *Queries) ClearServerSpotlightedUntil(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, clearServerSpotlightedUntil, serverID)
	return err
}

const countFlatEmojis = `-- name: CountFlatEmojis :one
SELECT coalesce(SUM(jsonb_array_length(s.emojis)), 0)::bigint
FROM servers s
WHERE s.show_emojis = true AND (s.type = 'approved' OR s.type = 'certified') AND s.state = 'public'
`

func (q *Queries) CountFlatEmojis(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFlatEmojis)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countFlatStickers = `-- name: CountFlatStickers :one
SELECT coalesce(SUM(jsonb_array_length(s.stickers)), 0)::bigint
FROM servers s
WHERE s.show_emojis = true AND (s.type = 'approved' OR s.type = 'certified') AND s.state = 'public'
`

func (q *Queries) CountFlatStickers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countFlatStickers)
	var column_1 int64
	err := row.Scan(&column_1)
	return column_1, err
}

const countServerEmojiPreviews = `-- name: CountServerEmojiPreviews :one
SELECT COUNT(*) FROM servers WHERE show_emojis = true AND (type = 'approved' OR type = 'certified') AND state = 'public'
`

func (q *Queries) CountServerEmojiPreviews(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServerEmojiPreviews)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServers = `-- name: CountServers :one
SELECT COUNT(*) FROM servers
`

func (q *Queries) CountServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServersByType = `-- name: CountServersByType :many
SELECT type AS method, COUNT(*) FROM servers GROUP BY type
`

type CountServersByTypeRow struct {
	Method string `db:"method" json:"method"`
	Count  int64  `db:"count" json:"count"`
}

func (q *Queries) CountServersByType(ctx context.Context) ([]CountServersByTypeRow, error) {
	rows, err := q.db.Query(ctx, countServersByType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountServersByTypeRow
	for rows.Next() {
		var i CountServersByTypeRow
		if err := rows.Scan(&i.Method, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const countTrendingServers = `-- name: CountTrendingServers :one
SELECT COUNT(*) FROM servers
WHERE (type = 'approved' OR type = 'certified') AND state = 'public' AND server_id IN (
	SELECT target_id FROM entity_votes
	WHERE target_type = 'server' AND void = false AND created_at > now() - interval '7 days'
	GROUP BY target_id
)
`

func (q *Queries) CountTrendingServers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countTrendingServers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteServerByID = `-- name: DeleteServerByID :exec
DELETE FROM servers WHERE server_id = $1
`

func (q *Queries) DeleteServerByID(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, deleteServerByID, serverID)
	return err
}

const denyServer = `-- name: DenyServer :exec
UPDATE servers SET type = 'denied', claimed_by = NULL WHERE server_id = $1
`

func (q *Queries) DenyServer(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, denyServer, serverID)
	return err
}

const getCertifiedIndexServers = `-- name: GetCertifiedIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND type = 'certified' ORDER BY approximate_votes DESC LIMIT 9
`

type GetCertifiedIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetCertifiedIndexServers(ctx context.Context) ([]GetCertifiedIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getCertifiedIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetCertifiedIndexServersRow
	for rows.Next() {
		var i GetCertifiedIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFeaturedIndexServers = `-- name: GetFeaturedIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND (type = 'approved' OR type = 'certified') AND featured_until IS NOT NULL AND featured_until > NOW() ORDER BY featured_until DESC LIMIT 9
`

type GetFeaturedIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetFeaturedIndexServers(ctx context.Context) ([]GetFeaturedIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getFeaturedIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFeaturedIndexServersRow
	for rows.Next() {
		var i GetFeaturedIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlatEmojis = `-- name: GetFlatEmojis :many
SELECT s.server_id AS server_id, s.name AS server_name, s.avatar AS server_avatar,
	(e->>'id')::text AS id, (e->>'name')::text AS name, coalesce((e->>'animated')::boolean, false)::boolean AS animated, (e->>'url')::text AS url
FROM servers s
CROSS JOIN LATERAL jsonb_array_elements(s.emojis) AS e
WHERE s.show_emojis = true AND (s.type = 'approved' OR s.type = 'certified') AND s.state = 'public'
ORDER BY e->>'name' ASC
LIMIT $1 OFFSET $2
`

type GetFlatEmojisParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetFlatEmojisRow struct {
	ServerID     string `db:"server_id" json:"server_id"`
	ServerName   string `db:"server_name" json:"server_name"`
	ServerAvatar string `db:"server_avatar" json:"server_avatar"`
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Animated     bool   `db:"animated" json:"animated"`
	Url          string `db:"url" json:"url"`
}

func (q *Queries) GetFlatEmojis(ctx context.Context, arg GetFlatEmojisParams) ([]GetFlatEmojisRow, error) {
	rows, err := q.db.Query(ctx, getFlatEmojis, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlatEmojisRow
	for rows.Next() {
		var i GetFlatEmojisRow
		if err := rows.Scan(
			&i.ServerID,
			&i.ServerName,
			&i.ServerAvatar,
			&i.ID,
			&i.Name,
			&i.Animated,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFlatStickers = `-- name: GetFlatStickers :many
SELECT s.server_id AS server_id, s.name AS server_name, s.avatar AS server_avatar,
	(e->>'id')::text AS id, (e->>'name')::text AS name, (e->>'format')::text AS format, (e->>'url')::text AS url
FROM servers s
CROSS JOIN LATERAL jsonb_array_elements(s.stickers) AS e
WHERE s.show_emojis = true AND (s.type = 'approved' OR s.type = 'certified') AND s.state = 'public'
ORDER BY e->>'name' ASC
LIMIT $1 OFFSET $2
`

type GetFlatStickersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetFlatStickersRow struct {
	ServerID     string `db:"server_id" json:"server_id"`
	ServerName   string `db:"server_name" json:"server_name"`
	ServerAvatar string `db:"server_avatar" json:"server_avatar"`
	ID           string `db:"id" json:"id"`
	Name         string `db:"name" json:"name"`
	Format       string `db:"format" json:"format"`
	Url          string `db:"url" json:"url"`
}

func (q *Queries) GetFlatStickers(ctx context.Context, arg GetFlatStickersParams) ([]GetFlatStickersRow, error) {
	rows, err := q.db.Query(ctx, getFlatStickers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetFlatStickersRow
	for rows.Next() {
		var i GetFlatStickersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.ServerName,
			&i.ServerAvatar,
			&i.ID,
			&i.Name,
			&i.Format,
			&i.Url,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexServerByID = `-- name: GetIndexServerByID :one

SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE server_id = $1
`

type GetIndexServerByIDRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

// IndexServer is the reduced projection used for listings, search results,
// and embedding a server inside other entities (packs, etc.) -- shared
// across several packages, hence its own file even though "servers" the
// full package hasn't been converted yet.
func (q *Queries) GetIndexServerByID(ctx context.Context, serverID string) (GetIndexServerByIDRow, error) {
	row := q.db.QueryRow(ctx, getIndexServerByID, serverID)
	var i GetIndexServerByIDRow
	err := row.Scan(
		&i.ServerID,
		&i.Name,
		&i.Avatar,
		&i.TotalMembers,
		&i.OnlineMembers,
		&i.Short,
		&i.Type,
		&i.State,
		&i.VanityRef,
		&i.ApproximateVotes,
		&i.InviteClicks,
		&i.Clicks,
		&i.Nsfw,
		&i.Tags,
		&i.Premium,
		&i.SupporterBadge,
		&i.BoostedUntil,
		&i.FeaturedUntil,
		&i.SpotlightedUntil,
	)
	return i, err
}

const getIndexServersByTeamMembership = `-- name: GetIndexServersByTeamMembership :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE team_owner IN (SELECT team_id FROM team_members WHERE user_id = $1)
`

type GetIndexServersByTeamMembershipRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetIndexServersByTeamMembership(ctx context.Context, userID string) ([]GetIndexServersByTeamMembershipRow, error) {
	rows, err := q.db.Query(ctx, getIndexServersByTeamMembership, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexServersByTeamMembershipRow
	for rows.Next() {
		var i GetIndexServersByTeamMembershipRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexServersByTeamOwner = `-- name: GetIndexServersByTeamOwner :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE team_owner = $1
`

type GetIndexServersByTeamOwnerRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetIndexServersByTeamOwner(ctx context.Context, teamOwner pgtype.UUID) ([]GetIndexServersByTeamOwnerRow, error) {
	rows, err := q.db.Query(ctx, getIndexServersByTeamOwner, teamOwner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexServersByTeamOwnerRow
	for rows.Next() {
		var i GetIndexServersByTeamOwnerRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getIndexServersPaged = `-- name: GetIndexServersPaged :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE (type = 'approved' OR type = 'certified') AND state = 'public'
ORDER BY (boosted_until IS NOT NULL AND boosted_until > NOW()) DESC, created_at DESC
LIMIT $1 OFFSET $2
`

type GetIndexServersPagedParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetIndexServersPagedRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetIndexServersPaged(ctx context.Context, arg GetIndexServersPagedParams) ([]GetIndexServersPagedRow, error) {
	rows, err := q.db.Query(ctx, getIndexServersPaged, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetIndexServersPagedRow
	for rows.Next() {
		var i GetIndexServersPagedRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getMostViewedIndexServers = `-- name: GetMostViewedIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND (type = 'approved' OR type = 'certified') ORDER BY clicks DESC LIMIT 9
`

type GetMostViewedIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetMostViewedIndexServers(ctx context.Context) ([]GetMostViewedIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getMostViewedIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetMostViewedIndexServersRow
	for rows.Next() {
		var i GetMostViewedIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPremiumIndexServers = `-- name: GetPremiumIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND premium = true ORDER BY approximate_votes DESC LIMIT 9
`

type GetPremiumIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetPremiumIndexServers(ctx context.Context) ([]GetPremiumIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getPremiumIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetPremiumIndexServersRow
	for rows.Next() {
		var i GetPremiumIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRandomIndexServers = `-- name: GetRandomIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE (type = 'approved' OR type = 'certified') AND state = 'public'
ORDER BY RANDOM()
LIMIT 3
`

type GetRandomIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetRandomIndexServers(ctx context.Context) ([]GetRandomIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getRandomIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRandomIndexServersRow
	for rows.Next() {
		var i GetRandomIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRecentlyAddedIndexServers = `-- name: GetRecentlyAddedIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND type = 'approved' ORDER BY created_at DESC LIMIT 9
`

type GetRecentlyAddedIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetRecentlyAddedIndexServers(ctx context.Context) ([]GetRecentlyAddedIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getRecentlyAddedIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRecentlyAddedIndexServersRow
	for rows.Next() {
		var i GetRecentlyAddedIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerByID = `-- name: GetServerByID :one
SELECT server_id, name, avatar, total_members, online_members, short, type, approval_note, state, tags, vanity_ref, extra_links, team_owner, invite_clicks, clicks, nsfw, approximate_votes, vote_banned, premium, start_premium_period, premium_period_length, captcha_opt_out, created_at, claimed_by, last_claimed, login_required_for_invite, show_emojis, emojis, stickers, emojis_synced_at, supporter_badge, boosted_until, featured_until, spotlighted_until, vote_blitz_until, discord_nsfw_level, nsfw_channel_count, moderation_flagged, moderation_categories
FROM servers
WHERE server_id = $1
`

type GetServerByIDRow struct {
	ServerID               string             `db:"server_id" json:"server_id"`
	Name                   string             `db:"name" json:"name"`
	Avatar                 string             `db:"avatar" json:"avatar"`
	TotalMembers           int32              `db:"total_members" json:"total_members"`
	OnlineMembers          int32              `db:"online_members" json:"online_members"`
	Short                  string             `db:"short" json:"short"`
	Type                   string             `db:"type" json:"type"`
	ApprovalNote           string             `db:"approval_note" json:"approval_note"`
	State                  string             `db:"state" json:"state"`
	Tags                   []string           `db:"tags" json:"tags"`
	VanityRef              pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ExtraLinks             []byte             `db:"extra_links" json:"extra_links"`
	TeamOwner              pgtype.UUID        `db:"team_owner" json:"team_owner"`
	InviteClicks           int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks                 int32              `db:"clicks" json:"clicks"`
	Nsfw                   bool               `db:"nsfw" json:"nsfw"`
	ApproximateVotes       int32              `db:"approximate_votes" json:"approximate_votes"`
	VoteBanned             bool               `db:"vote_banned" json:"vote_banned"`
	Premium                bool               `db:"premium" json:"premium"`
	StartPremiumPeriod     pgtype.Timestamptz `db:"start_premium_period" json:"start_premium_period"`
	PremiumPeriodLength    time.Duration      `db:"premium_period_length" json:"premium_period_length"`
	CaptchaOptOut          bool               `db:"captcha_opt_out" json:"captcha_opt_out"`
	CreatedAt              pgtype.Timestamptz `db:"created_at" json:"created_at"`
	ClaimedBy              pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	LastClaimed            pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
	LoginRequiredForInvite bool               `db:"login_required_for_invite" json:"login_required_for_invite"`
	ShowEmojis             bool               `db:"show_emojis" json:"show_emojis"`
	Emojis                 []types.Emoji      `db:"emojis" json:"emojis"`
	Stickers               []types.Sticker    `db:"stickers" json:"stickers"`
	EmojisSyncedAt         pgtype.Timestamptz `db:"emojis_synced_at" json:"emojis_synced_at"`
	SupporterBadge         bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil           pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil          pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil       pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
	VoteBlitzUntil         pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
	DiscordNsfwLevel       int16              `db:"discord_nsfw_level" json:"discord_nsfw_level"`
	NsfwChannelCount       int32              `db:"nsfw_channel_count" json:"nsfw_channel_count"`
	ModerationFlagged      bool               `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories   []string           `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) GetServerByID(ctx context.Context, serverID string) (GetServerByIDRow, error) {
	row := q.db.QueryRow(ctx, getServerByID, serverID)
	var i GetServerByIDRow
	err := row.Scan(
		&i.ServerID,
		&i.Name,
		&i.Avatar,
		&i.TotalMembers,
		&i.OnlineMembers,
		&i.Short,
		&i.Type,
		&i.ApprovalNote,
		&i.State,
		&i.Tags,
		&i.VanityRef,
		&i.ExtraLinks,
		&i.TeamOwner,
		&i.InviteClicks,
		&i.Clicks,
		&i.Nsfw,
		&i.ApproximateVotes,
		&i.VoteBanned,
		&i.Premium,
		&i.StartPremiumPeriod,
		&i.PremiumPeriodLength,
		&i.CaptchaOptOut,
		&i.CreatedAt,
		&i.ClaimedBy,
		&i.LastClaimed,
		&i.LoginRequiredForInvite,
		&i.ShowEmojis,
		&i.Emojis,
		&i.Stickers,
		&i.EmojisSyncedAt,
		&i.SupporterBadge,
		&i.BoostedUntil,
		&i.FeaturedUntil,
		&i.SpotlightedUntil,
		&i.VoteBlitzUntil,
		&i.DiscordNsfwLevel,
		&i.NsfwChannelCount,
		&i.ModerationFlagged,
		&i.ModerationCategories,
	)
	return i, err
}

const getServerCaptchaOptOut = `-- name: GetServerCaptchaOptOut :one
SELECT captcha_opt_out FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerCaptchaOptOut(ctx context.Context, serverID string) (bool, error) {
	row := q.db.QueryRow(ctx, getServerCaptchaOptOut, serverID)
	var captcha_opt_out bool
	err := row.Scan(&captcha_opt_out)
	return captcha_opt_out, err
}

const getServerCertStats = `-- name: GetServerCertStats :one
SELECT type, total_members, cardinality(unique_clicks) AS unique_clicks, approximate_votes, created_at
FROM servers
WHERE server_id = $1
`

type GetServerCertStatsRow struct {
	Type             string             `db:"type" json:"type"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	UniqueClicks     int32              `db:"unique_clicks" json:"unique_clicks"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetServerCertStats(ctx context.Context, serverID string) (GetServerCertStatsRow, error) {
	row := q.db.QueryRow(ctx, getServerCertStats, serverID)
	var i GetServerCertStatsRow
	err := row.Scan(
		&i.Type,
		&i.TotalMembers,
		&i.UniqueClicks,
		&i.ApproximateVotes,
		&i.CreatedAt,
	)
	return i, err
}

const getServerEmojiPreviews = `-- name: GetServerEmojiPreviews :many
SELECT server_id, name, avatar, emojis, stickers
FROM servers
WHERE show_emojis = true AND (type = 'approved' OR type = 'certified') AND state = 'public'
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetServerEmojiPreviewsParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetServerEmojiPreviewsRow struct {
	ServerID string          `db:"server_id" json:"server_id"`
	Name     string          `db:"name" json:"name"`
	Avatar   string          `db:"avatar" json:"avatar"`
	Emojis   []types.Emoji   `db:"emojis" json:"emojis"`
	Stickers []types.Sticker `db:"stickers" json:"stickers"`
}

func (q *Queries) GetServerEmojiPreviews(ctx context.Context, arg GetServerEmojiPreviewsParams) ([]GetServerEmojiPreviewsRow, error) {
	rows, err := q.db.Query(ctx, getServerEmojiPreviews, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServerEmojiPreviewsRow
	for rows.Next() {
		var i GetServerEmojiPreviewsRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.Emojis,
			&i.Stickers,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerIDsAndStatsSelfManaged = `-- name: GetServerIDsAndStatsSelfManaged :many
SELECT server_id, stats_self_managed FROM servers
`

type GetServerIDsAndStatsSelfManagedRow struct {
	ServerID         string `db:"server_id" json:"server_id"`
	StatsSelfManaged bool   `db:"stats_self_managed" json:"stats_self_managed"`
}

func (q *Queries) GetServerIDsAndStatsSelfManaged(ctx context.Context) ([]GetServerIDsAndStatsSelfManagedRow, error) {
	rows, err := q.db.Query(ctx, getServerIDsAndStatsSelfManaged)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServerIDsAndStatsSelfManagedRow
	for rows.Next() {
		var i GetServerIDsAndStatsSelfManagedRow
		if err := rows.Scan(&i.ServerID, &i.StatsSelfManaged); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerInviteEligibility = `-- name: GetServerInviteEligibility :one
SELECT login_required_for_invite, blacklisted_users, invite, type, state FROM servers WHERE server_id = $1
`

type GetServerInviteEligibilityRow struct {
	LoginRequiredForInvite bool     `db:"login_required_for_invite" json:"login_required_for_invite"`
	BlacklistedUsers       []string `db:"blacklisted_users" json:"blacklisted_users"`
	Invite                 string   `db:"invite" json:"invite"`
	Type                   string   `db:"type" json:"type"`
	State                  string   `db:"state" json:"state"`
}

func (q *Queries) GetServerInviteEligibility(ctx context.Context, serverID string) (GetServerInviteEligibilityRow, error) {
	row := q.db.QueryRow(ctx, getServerInviteEligibility, serverID)
	var i GetServerInviteEligibilityRow
	err := row.Scan(
		&i.LoginRequiredForInvite,
		&i.BlacklistedUsers,
		&i.Invite,
		&i.Type,
		&i.State,
	)
	return i, err
}

const getServerLongDescription = `-- name: GetServerLongDescription :one
SELECT long FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerLongDescription(ctx context.Context, serverID string) (string, error) {
	row := q.db.QueryRow(ctx, getServerLongDescription, serverID)
	var long string
	err := row.Scan(&long)
	return long, err
}

const getServerNameAndAvatar = `-- name: GetServerNameAndAvatar :one
SELECT name, avatar FROM servers WHERE server_id = $1
`

type GetServerNameAndAvatarRow struct {
	Name   string `db:"name" json:"name"`
	Avatar string `db:"avatar" json:"avatar"`
}

func (q *Queries) GetServerNameAndAvatar(ctx context.Context, serverID string) (GetServerNameAndAvatarRow, error) {
	row := q.db.QueryRow(ctx, getServerNameAndAvatar, serverID)
	var i GetServerNameAndAvatarRow
	err := row.Scan(&i.Name, &i.Avatar)
	return i, err
}

const getServerNameAndShort = `-- name: GetServerNameAndShort :one
SELECT name, short FROM servers WHERE server_id = $1
`

type GetServerNameAndShortRow struct {
	Name  string `db:"name" json:"name"`
	Short string `db:"short" json:"short"`
}

func (q *Queries) GetServerNameAndShort(ctx context.Context, serverID string) (GetServerNameAndShortRow, error) {
	row := q.db.QueryRow(ctx, getServerNameAndShort, serverID)
	var i GetServerNameAndShortRow
	err := row.Scan(&i.Name, &i.Short)
	return i, err
}

const getServerReviewStatus = `-- name: GetServerReviewStatus :one
SELECT type, claimed_by, last_claimed FROM servers WHERE server_id = $1
`

type GetServerReviewStatusRow struct {
	Type        string             `db:"type" json:"type"`
	ClaimedBy   pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	LastClaimed pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
}

func (q *Queries) GetServerReviewStatus(ctx context.Context, serverID string) (GetServerReviewStatusRow, error) {
	row := q.db.QueryRow(ctx, getServerReviewStatus, serverID)
	var i GetServerReviewStatusRow
	err := row.Scan(&i.Type, &i.ClaimedBy, &i.LastClaimed)
	return i, err
}

const getServerTeamOwner = `-- name: GetServerTeamOwner :one
SELECT team_owner FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerTeamOwner(ctx context.Context, serverID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getServerTeamOwner, serverID)
	var team_owner pgtype.UUID
	err := row.Scan(&team_owner)
	return team_owner, err
}

const getServerType = `-- name: GetServerType :one
SELECT type FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerType(ctx context.Context, serverID string) (string, error) {
	row := q.db.QueryRow(ctx, getServerType, serverID)
	var type_ string
	err := row.Scan(&type_)
	return type_, err
}

const getServerTypeAndClaimedBy = `-- name: GetServerTypeAndClaimedBy :one
SELECT type, claimed_by FROM servers WHERE server_id = $1
`

type GetServerTypeAndClaimedByRow struct {
	Type      string      `db:"type" json:"type"`
	ClaimedBy pgtype.Text `db:"claimed_by" json:"claimed_by"`
}

func (q *Queries) GetServerTypeAndClaimedBy(ctx context.Context, serverID string) (GetServerTypeAndClaimedByRow, error) {
	row := q.db.QueryRow(ctx, getServerTypeAndClaimedBy, serverID)
	var i GetServerTypeAndClaimedByRow
	err := row.Scan(&i.Type, &i.ClaimedBy)
	return i, err
}

const getServerUniqueClicksCount = `-- name: GetServerUniqueClicksCount :one
SELECT cardinality(unique_clicks) FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerUniqueClicksCount(ctx context.Context, serverID string) (int32, error) {
	row := q.db.QueryRow(ctx, getServerUniqueClicksCount, serverID)
	var cardinality int32
	err := row.Scan(&cardinality)
	return cardinality, err
}

const getServerVanityRef = `-- name: GetServerVanityRef :one
SELECT vanity_ref FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerVanityRef(ctx context.Context, serverID string) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getServerVanityRef, serverID)
	var vanity_ref pgtype.UUID
	err := row.Scan(&vanity_ref)
	return vanity_ref, err
}

const getServersDueForModerationScan = `-- name: GetServersDueForModerationScan :many
SELECT server_id, short, long, nsfw
FROM servers
WHERE type IN ('approved', 'certified', 'pending')
AND (moderation_checked_at IS NULL OR moderation_checked_at < NOW() - INTERVAL '7 days')
ORDER BY moderation_checked_at ASC NULLS FIRST
LIMIT $1
`

type GetServersDueForModerationScanRow struct {
	ServerID string `db:"server_id" json:"server_id"`
	Short    string `db:"short" json:"short"`
	Long     string `db:"long" json:"long"`
	Nsfw     bool   `db:"nsfw" json:"nsfw"`
}

func (q *Queries) GetServersDueForModerationScan(ctx context.Context, limit int32) ([]GetServersDueForModerationScanRow, error) {
	rows, err := q.db.Query(ctx, getServersDueForModerationScan, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServersDueForModerationScanRow
	for rows.Next() {
		var i GetServersDueForModerationScanRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Short,
			&i.Long,
			&i.Nsfw,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServersWithEmojisShown = `-- name: GetServersWithEmojisShown :many
SELECT server_id FROM servers WHERE show_emojis = true
`

func (q *Queries) GetServersWithEmojisShown(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getServersWithEmojisShown)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var server_id string
		if err := rows.Scan(&server_id); err != nil {
			return nil, err
		}
		items = append(items, server_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSimilarServers = `-- name: GetSimilarServers :many
WITH source_tags AS (
    SELECT tags FROM servers WHERE server_id = $1
)
SELECT s.server_id, s.name, s.avatar, s.total_members, s.online_members, s.short, s.type, s.state, s.vanity_ref, s.approximate_votes, s.invite_clicks, s.clicks, s.nsfw, s.tags, s.premium, s.supporter_badge, s.boosted_until, s.featured_until, s.spotlighted_until
FROM servers s, source_tags st
WHERE (s.type = 'approved' OR s.type = 'certified')
AND s.state = 'public'
AND s.server_id != $1
AND s.tags && st.tags
ORDER BY cardinality(ARRAY(SELECT unnest(s.tags) INTERSECT SELECT unnest(st.tags))) DESC, s.approximate_votes DESC
LIMIT 6
`

type GetSimilarServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

// Tag-overlap similarity, mirroring GetSimilarBots -- see its comment.
func (q *Queries) GetSimilarServers(ctx context.Context, serverID string) ([]GetSimilarServersRow, error) {
	rows, err := q.db.Query(ctx, getSimilarServers, serverID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSimilarServersRow
	for rows.Next() {
		var i GetSimilarServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getSpotlightIndexServers = `-- name: GetSpotlightIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND (type = 'approved' OR type = 'certified') AND spotlighted_until IS NOT NULL AND spotlighted_until > NOW() ORDER BY spotlighted_until DESC LIMIT 9
`

type GetSpotlightIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetSpotlightIndexServers(ctx context.Context) ([]GetSpotlightIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getSpotlightIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetSpotlightIndexServersRow
	for rows.Next() {
		var i GetSpotlightIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTopVotedIndexServers = `-- name: GetTopVotedIndexServers :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers WHERE state = 'public' AND (type = 'approved' OR type = 'certified') ORDER BY approximate_votes DESC LIMIT 9
`

type GetTopVotedIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetTopVotedIndexServers(ctx context.Context) ([]GetTopVotedIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getTopVotedIndexServers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopVotedIndexServersRow
	for rows.Next() {
		var i GetTopVotedIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTrendingIndexServers = `-- name: GetTrendingIndexServers :many
WITH scored AS (
	SELECT target_id, COUNT(*) FILTER (WHERE upvote) - COUNT(*) FILTER (WHERE NOT upvote) AS score
	FROM entity_votes
	WHERE target_type = 'server' AND void = false AND created_at > now() - interval '7 days'
	GROUP BY target_id
)
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes, invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE (type = 'approved' OR type = 'certified') AND state = 'public' AND server_id IN (SELECT target_id FROM scored)
ORDER BY (SELECT score FROM scored WHERE scored.target_id = servers.server_id) DESC
LIMIT $1 OFFSET $2
`

type GetTrendingIndexServersParams struct {
	Limit  int32 `db:"limit" json:"limit"`
	Offset int32 `db:"offset" json:"offset"`
}

type GetTrendingIndexServersRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

func (q *Queries) GetTrendingIndexServers(ctx context.Context, arg GetTrendingIndexServersParams) ([]GetTrendingIndexServersRow, error) {
	rows, err := q.db.Query(ctx, getTrendingIndexServers, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTrendingIndexServersRow
	for rows.Next() {
		var i GetTrendingIndexServersRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertServer = `-- name: InsertServer :exec
INSERT INTO servers (invite, short, long, extra_links, tags, nsfw, team_owner, server_id, name, avatar, total_members, online_members, vanity_ref)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertServerParams struct {
	Invite        string      `db:"invite" json:"invite"`
	Short         string      `db:"short" json:"short"`
	Long          string      `db:"long" json:"long"`
	ExtraLinks    []byte      `db:"extra_links" json:"extra_links"`
	Tags          []string    `db:"tags" json:"tags"`
	Nsfw          bool        `db:"nsfw" json:"nsfw"`
	TeamOwner     pgtype.UUID `db:"team_owner" json:"team_owner"`
	ServerID      string      `db:"server_id" json:"server_id"`
	Name          string      `db:"name" json:"name"`
	Avatar        string      `db:"avatar" json:"avatar"`
	TotalMembers  int32       `db:"total_members" json:"total_members"`
	OnlineMembers int32       `db:"online_members" json:"online_members"`
	VanityRef     pgtype.UUID `db:"vanity_ref" json:"vanity_ref"`
}

func (q *Queries) InsertServer(ctx context.Context, arg InsertServerParams) error {
	_, err := q.db.Exec(ctx, insertServer,
		arg.Invite,
		arg.Short,
		arg.Long,
		arg.ExtraLinks,
		arg.Tags,
		arg.Nsfw,
		arg.TeamOwner,
		arg.ServerID,
		arg.Name,
		arg.Avatar,
		arg.TotalMembers,
		arg.OnlineMembers,
		arg.VanityRef,
	)
	return err
}

const recordServerModerationScan = `-- name: RecordServerModerationScan :exec
UPDATE servers SET moderation_flagged = $2, moderation_categories = $3, moderation_checked_at = NOW() WHERE server_id = $1
`

type RecordServerModerationScanParams struct {
	ServerID             string   `db:"server_id" json:"server_id"`
	ModerationFlagged    bool     `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) RecordServerModerationScan(ctx context.Context, arg RecordServerModerationScanParams) error {
	_, err := q.db.Exec(ctx, recordServerModerationScan, arg.ServerID, arg.ModerationFlagged, arg.ModerationCategories)
	return err
}

const removeServerPremium = `-- name: RemoveServerPremium :exec
UPDATE servers SET premium = false WHERE server_id = $1
`

func (q *Queries) RemoveServerPremium(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, removeServerPremium, serverID)
	return err
}

const searchServersPublic = `-- name: SearchServersPublic :many
SELECT server_id, name, avatar, total_members, online_members, short, type, state, vanity_ref, approximate_votes,
    invite_clicks, clicks, nsfw, tags, premium, supporter_badge, boosted_until, featured_until, spotlighted_until
FROM servers
WHERE (type = 'approved' OR type = 'certified')
AND state = 'public'
AND ($1::int = 0 OR total_members >= $1::int)
AND ($2::int = 0 OR total_members <= $2::int)
AND ($3::int = 0 OR approximate_votes >= $3::int)
AND ($4::int = 0 OR approximate_votes <= $4::int)
AND (
    cardinality($5::text[]) = 0
    OR ($6::text = '@>' AND tags @> $5::text[])
    OR ($6::text = '&&' AND tags && $5::text[])
)
AND (
    $7::text = ''
    OR name ILIKE $8::text
    OR name @@ $7::text
    OR short @@ $7::text
    OR server_id = $7::text
)
GROUP BY server_id
ORDER BY approximate_votes DESC, type DESC
LIMIT 12
`

type SearchServersPublicParams struct {
	MembersFrom int32    `db:"members_from" json:"members_from"`
	MembersTo   int32    `db:"members_to" json:"members_to"`
	VotesFrom   int32    `db:"votes_from" json:"votes_from"`
	VotesTo     int32    `db:"votes_to" json:"votes_to"`
	Tags        []string `db:"tags" json:"tags"`
	TagMode     string   `db:"tag_mode" json:"tag_mode"`
	Query       string   `db:"query" json:"query"`
	Pattern     string   `db:"pattern" json:"pattern"`
}

type SearchServersPublicRow struct {
	ServerID         string             `db:"server_id" json:"server_id"`
	Name             string             `db:"name" json:"name"`
	Avatar           string             `db:"avatar" json:"avatar"`
	TotalMembers     int32              `db:"total_members" json:"total_members"`
	OnlineMembers    int32              `db:"online_members" json:"online_members"`
	Short            string             `db:"short" json:"short"`
	Type             string             `db:"type" json:"type"`
	State            string             `db:"state" json:"state"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks     int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks           int32              `db:"clicks" json:"clicks"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	Tags             []string           `db:"tags" json:"tags"`
	Premium          bool               `db:"premium" json:"premium"`
	SupporterBadge   bool               `db:"supporter_badge" json:"supporter_badge"`
	BoostedUntil     pgtype.Timestamptz `db:"boosted_until" json:"boosted_until"`
	FeaturedUntil    pgtype.Timestamptz `db:"featured_until" json:"featured_until"`
	SpotlightedUntil pgtype.Timestamptz `db:"spotlighted_until" json:"spotlighted_until"`
}

// Backs POST /list/search's "server" target type.
func (q *Queries) SearchServersPublic(ctx context.Context, arg SearchServersPublicParams) ([]SearchServersPublicRow, error) {
	rows, err := q.db.Query(ctx, searchServersPublic,
		arg.MembersFrom,
		arg.MembersTo,
		arg.VotesFrom,
		arg.VotesTo,
		arg.Tags,
		arg.TagMode,
		arg.Query,
		arg.Pattern,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchServersPublicRow
	for rows.Next() {
		var i SearchServersPublicRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.State,
			&i.VanityRef,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.Tags,
			&i.Premium,
			&i.SupporterBadge,
			&i.BoostedUntil,
			&i.FeaturedUntil,
			&i.SpotlightedUntil,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchServersQueue = `-- name: SearchServersQueue :many
SELECT server_id, name, avatar, total_members, online_members, short, type, approval_note,
       approximate_votes, invite_clicks, clicks, nsfw, discord_nsfw_level, nsfw_channel_count,
       tags, premium, claimed_by, last_claimed, moderation_flagged, moderation_categories
FROM servers WHERE server_id = $1::text OR name ILIKE $2::text ORDER BY created_at
`

type SearchServersQueueParams struct {
	Query   string `db:"query" json:"query"`
	Pattern string `db:"pattern" json:"pattern"`
}

type SearchServersQueueRow struct {
	ServerID             string             `db:"server_id" json:"server_id"`
	Name                 string             `db:"name" json:"name"`
	Avatar               string             `db:"avatar" json:"avatar"`
	TotalMembers         int32              `db:"total_members" json:"total_members"`
	OnlineMembers        int32              `db:"online_members" json:"online_members"`
	Short                string             `db:"short" json:"short"`
	Type                 string             `db:"type" json:"type"`
	ApprovalNote         string             `db:"approval_note" json:"approval_note"`
	ApproximateVotes     int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks         int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks               int32              `db:"clicks" json:"clicks"`
	Nsfw                 bool               `db:"nsfw" json:"nsfw"`
	DiscordNsfwLevel     int16              `db:"discord_nsfw_level" json:"discord_nsfw_level"`
	NsfwChannelCount     int32              `db:"nsfw_channel_count" json:"nsfw_channel_count"`
	Tags                 []string           `db:"tags" json:"tags"`
	Premium              bool               `db:"premium" json:"premium"`
	ClaimedBy            pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	LastClaimed          pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
	ModerationFlagged    bool               `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string           `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) SearchServersQueue(ctx context.Context, arg SearchServersQueueParams) ([]SearchServersQueueRow, error) {
	rows, err := q.db.Query(ctx, searchServersQueue, arg.Query, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchServersQueueRow
	for rows.Next() {
		var i SearchServersQueueRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.ApprovalNote,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.DiscordNsfwLevel,
			&i.NsfwChannelCount,
			&i.Tags,
			&i.Premium,
			&i.ClaimedBy,
			&i.LastClaimed,
			&i.ModerationFlagged,
			&i.ModerationCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const serverQueuePending = `-- name: ServerQueuePending :many

SELECT server_id, name, avatar, total_members, online_members, short, type, approval_note,
       approximate_votes, invite_clicks, clicks, nsfw, discord_nsfw_level, nsfw_channel_count,
       tags, premium, claimed_by, last_claimed, moderation_flagged, moderation_categories
FROM servers WHERE type = 'pending' OR type = 'claimed' ORDER BY created_at
`

type ServerQueuePendingRow struct {
	ServerID             string             `db:"server_id" json:"server_id"`
	Name                 string             `db:"name" json:"name"`
	Avatar               string             `db:"avatar" json:"avatar"`
	TotalMembers         int32              `db:"total_members" json:"total_members"`
	OnlineMembers        int32              `db:"online_members" json:"online_members"`
	Short                string             `db:"short" json:"short"`
	Type                 string             `db:"type" json:"type"`
	ApprovalNote         string             `db:"approval_note" json:"approval_note"`
	ApproximateVotes     int32              `db:"approximate_votes" json:"approximate_votes"`
	InviteClicks         int32              `db:"invite_clicks" json:"invite_clicks"`
	Clicks               int32              `db:"clicks" json:"clicks"`
	Nsfw                 bool               `db:"nsfw" json:"nsfw"`
	DiscordNsfwLevel     int16              `db:"discord_nsfw_level" json:"discord_nsfw_level"`
	NsfwChannelCount     int32              `db:"nsfw_channel_count" json:"nsfw_channel_count"`
	Tags                 []string           `db:"tags" json:"tags"`
	Premium              bool               `db:"premium" json:"premium"`
	ClaimedBy            pgtype.Text        `db:"claimed_by" json:"claimed_by"`
	LastClaimed          pgtype.Timestamptz `db:"last_claimed" json:"last_claimed"`
	ModerationFlagged    bool               `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string           `db:"moderation_categories" json:"moderation_categories"`
}

// Panel server review queue and search (arcadia/panel ops_queue.go, ops_search.go).
func (q *Queries) ServerQueuePending(ctx context.Context) ([]ServerQueuePendingRow, error) {
	rows, err := q.db.Query(ctx, serverQueuePending)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ServerQueuePendingRow
	for rows.Next() {
		var i ServerQueuePendingRow
		if err := rows.Scan(
			&i.ServerID,
			&i.Name,
			&i.Avatar,
			&i.TotalMembers,
			&i.OnlineMembers,
			&i.Short,
			&i.Type,
			&i.ApprovalNote,
			&i.ApproximateVotes,
			&i.InviteClicks,
			&i.Clicks,
			&i.Nsfw,
			&i.DiscordNsfwLevel,
			&i.NsfwChannelCount,
			&i.Tags,
			&i.Premium,
			&i.ClaimedBy,
			&i.LastClaimed,
			&i.ModerationFlagged,
			&i.ModerationCategories,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setServerSpotlightedUntil = `-- name: SetServerSpotlightedUntil :exec
UPDATE servers SET spotlighted_until = GREATEST(COALESCE(spotlighted_until, NOW()), NOW()) + make_interval(hours => $1::int) WHERE server_id = $2::text
`

type SetServerSpotlightedUntilParams struct {
	Hours    int32  `db:"hours" json:"hours"`
	ServerID string `db:"server_id" json:"server_id"`
}

func (q *Queries) SetServerSpotlightedUntil(ctx context.Context, arg SetServerSpotlightedUntilParams) error {
	_, err := q.db.Exec(ctx, setServerSpotlightedUntil, arg.Hours, arg.ServerID)
	return err
}

const setServerVoteBanned = `-- name: SetServerVoteBanned :exec
UPDATE servers SET vote_banned = $2 WHERE server_id = $1
`

type SetServerVoteBannedParams struct {
	ServerID   string `db:"server_id" json:"server_id"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SetServerVoteBanned(ctx context.Context, arg SetServerVoteBannedParams) error {
	_, err := q.db.Exec(ctx, setServerVoteBanned, arg.ServerID, arg.VoteBanned)
	return err
}

const uncertifyServer = `-- name: UncertifyServer :exec
UPDATE servers SET type = 'approved' WHERE server_id = $1
`

func (q *Queries) UncertifyServer(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, uncertifyServer, serverID)
	return err
}

const unverifyServer = `-- name: UnverifyServer :exec
UPDATE servers SET type = 'pending', claimed_by = NULL WHERE server_id = $1
`

func (q *Queries) UnverifyServer(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, unverifyServer, serverID)
	return err
}

const updateServerAvatarAndNsfwStats = `-- name: UpdateServerAvatarAndNsfwStats :exec
UPDATE servers SET avatar = $2, discord_nsfw_level = $3, nsfw_channel_count = $4 WHERE server_id = $1
`

type UpdateServerAvatarAndNsfwStatsParams struct {
	ServerID         string `db:"server_id" json:"server_id"`
	Avatar           string `db:"avatar" json:"avatar"`
	DiscordNsfwLevel int16  `db:"discord_nsfw_level" json:"discord_nsfw_level"`
	NsfwChannelCount int32  `db:"nsfw_channel_count" json:"nsfw_channel_count"`
}

func (q *Queries) UpdateServerAvatarAndNsfwStats(ctx context.Context, arg UpdateServerAvatarAndNsfwStatsParams) error {
	_, err := q.db.Exec(ctx, updateServerAvatarAndNsfwStats,
		arg.ServerID,
		arg.Avatar,
		arg.DiscordNsfwLevel,
		arg.NsfwChannelCount,
	)
	return err
}

const updateServerAvatarMembersAndNsfw = `-- name: UpdateServerAvatarMembersAndNsfw :exec
UPDATE servers SET avatar = $2, total_members = $3, online_members = $4, discord_nsfw_level = $5, nsfw_channel_count = $6 WHERE server_id = $1
`

type UpdateServerAvatarMembersAndNsfwParams struct {
	ServerID         string `db:"server_id" json:"server_id"`
	Avatar           string `db:"avatar" json:"avatar"`
	TotalMembers     int32  `db:"total_members" json:"total_members"`
	OnlineMembers    int32  `db:"online_members" json:"online_members"`
	DiscordNsfwLevel int16  `db:"discord_nsfw_level" json:"discord_nsfw_level"`
	NsfwChannelCount int32  `db:"nsfw_channel_count" json:"nsfw_channel_count"`
}

func (q *Queries) UpdateServerAvatarMembersAndNsfw(ctx context.Context, arg UpdateServerAvatarMembersAndNsfwParams) error {
	_, err := q.db.Exec(ctx, updateServerAvatarMembersAndNsfw,
		arg.ServerID,
		arg.Avatar,
		arg.TotalMembers,
		arg.OnlineMembers,
		arg.DiscordNsfwLevel,
		arg.NsfwChannelCount,
	)
	return err
}

const updateServerClaim = `-- name: UpdateServerClaim :exec
UPDATE servers SET last_claimed = NOW(), claimed_by = $1 WHERE server_id = $2
`

type UpdateServerClaimParams struct {
	ClaimedBy pgtype.Text `db:"claimed_by" json:"claimed_by"`
	ServerID  string      `db:"server_id" json:"server_id"`
}

func (q *Queries) UpdateServerClaim(ctx context.Context, arg UpdateServerClaimParams) error {
	_, err := q.db.Exec(ctx, updateServerClaim, arg.ClaimedBy, arg.ServerID)
	return err
}

const updateServerClicks = `-- name: UpdateServerClicks :exec
UPDATE servers SET clicks = clicks + 1 WHERE server_id = $1
`

func (q *Queries) UpdateServerClicks(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, updateServerClicks, serverID)
	return err
}

const updateServerEmojisStickers = `-- name: UpdateServerEmojisStickers :exec
UPDATE servers SET emojis = $2, stickers = $3, emojis_synced_at = NOW() WHERE server_id = $1
`

type UpdateServerEmojisStickersParams struct {
	ServerID string          `db:"server_id" json:"server_id"`
	Emojis   []types.Emoji   `db:"emojis" json:"emojis"`
	Stickers []types.Sticker `db:"stickers" json:"stickers"`
}

func (q *Queries) UpdateServerEmojisStickers(ctx context.Context, arg UpdateServerEmojisStickersParams) error {
	_, err := q.db.Exec(ctx, updateServerEmojisStickers, arg.ServerID, arg.Emojis, arg.Stickers)
	return err
}

const updateServerInvite = `-- name: UpdateServerInvite :exec
UPDATE servers SET invite = $2 WHERE server_id = $1
`

type UpdateServerInviteParams struct {
	ServerID string `db:"server_id" json:"server_id"`
	Invite   string `db:"invite" json:"invite"`
}

func (q *Queries) UpdateServerInvite(ctx context.Context, arg UpdateServerInviteParams) error {
	_, err := q.db.Exec(ctx, updateServerInvite, arg.ServerID, arg.Invite)
	return err
}

const updateServerInviteClicks = `-- name: UpdateServerInviteClicks :exec
UPDATE servers SET invite_clicks = invite_clicks + 1 WHERE server_id = $1
`

func (q *Queries) UpdateServerInviteClicks(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, updateServerInviteClicks, serverID)
	return err
}

const updateServerModerationResult = `-- name: UpdateServerModerationResult :exec
UPDATE servers SET moderation_flagged = $2, moderation_categories = $3 WHERE server_id = $1
`

type UpdateServerModerationResultParams struct {
	ServerID             string   `db:"server_id" json:"server_id"`
	ModerationFlagged    bool     `db:"moderation_flagged" json:"moderation_flagged"`
	ModerationCategories []string `db:"moderation_categories" json:"moderation_categories"`
}

func (q *Queries) UpdateServerModerationResult(ctx context.Context, arg UpdateServerModerationResultParams) error {
	_, err := q.db.Exec(ctx, updateServerModerationResult, arg.ServerID, arg.ModerationFlagged, arg.ModerationCategories)
	return err
}

const updateServerOnlineMembers = `-- name: UpdateServerOnlineMembers :exec
UPDATE servers SET online_members = $1 WHERE server_id = $2
`

type UpdateServerOnlineMembersParams struct {
	OnlineMembers int32  `db:"online_members" json:"online_members"`
	ServerID      string `db:"server_id" json:"server_id"`
}

func (q *Queries) UpdateServerOnlineMembers(ctx context.Context, arg UpdateServerOnlineMembersParams) error {
	_, err := q.db.Exec(ctx, updateServerOnlineMembers, arg.OnlineMembers, arg.ServerID)
	return err
}

const updateServerSettings = `-- name: UpdateServerSettings :exec
UPDATE servers SET short = $1, long = $2, extra_links = $3, state = $4, tags = $5, nsfw = $6, captcha_opt_out = $7, login_required_for_invite = $8, show_emojis = $9
WHERE server_id = $10
`

type UpdateServerSettingsParams struct {
	Short                  string   `db:"short" json:"short"`
	Long                   string   `db:"long" json:"long"`
	ExtraLinks             []byte   `db:"extra_links" json:"extra_links"`
	State                  string   `db:"state" json:"state"`
	Tags                   []string `db:"tags" json:"tags"`
	Nsfw                   bool     `db:"nsfw" json:"nsfw"`
	CaptchaOptOut          bool     `db:"captcha_opt_out" json:"captcha_opt_out"`
	LoginRequiredForInvite bool     `db:"login_required_for_invite" json:"login_required_for_invite"`
	ShowEmojis             bool     `db:"show_emojis" json:"show_emojis"`
	ServerID               string   `db:"server_id" json:"server_id"`
}

func (q *Queries) UpdateServerSettings(ctx context.Context, arg UpdateServerSettingsParams) error {
	_, err := q.db.Exec(ctx, updateServerSettings,
		arg.Short,
		arg.Long,
		arg.ExtraLinks,
		arg.State,
		arg.Tags,
		arg.Nsfw,
		arg.CaptchaOptOut,
		arg.LoginRequiredForInvite,
		arg.ShowEmojis,
		arg.ServerID,
	)
	return err
}

const updateServerShortLong = `-- name: UpdateServerShortLong :exec
UPDATE servers SET short = $2, long = $3 WHERE server_id = $1
`

type UpdateServerShortLongParams struct {
	ServerID string `db:"server_id" json:"server_id"`
	Short    string `db:"short" json:"short"`
	Long     string `db:"long" json:"long"`
}

func (q *Queries) UpdateServerShortLong(ctx context.Context, arg UpdateServerShortLongParams) error {
	_, err := q.db.Exec(ctx, updateServerShortLong, arg.ServerID, arg.Short, arg.Long)
	return err
}

const updateServerStatsMeta = `-- name: UpdateServerStatsMeta :exec
UPDATE servers SET last_stats_post = NOW(), stats_self_managed = true WHERE server_id = $1
`

func (q *Queries) UpdateServerStatsMeta(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, updateServerStatsMeta, serverID)
	return err
}

const updateServerTotalMembers = `-- name: UpdateServerTotalMembers :exec
UPDATE servers SET total_members = $1 WHERE server_id = $2
`

type UpdateServerTotalMembersParams struct {
	TotalMembers int32  `db:"total_members" json:"total_members"`
	ServerID     string `db:"server_id" json:"server_id"`
}

func (q *Queries) UpdateServerTotalMembers(ctx context.Context, arg UpdateServerTotalMembersParams) error {
	_, err := q.db.Exec(ctx, updateServerTotalMembers, arg.TotalMembers, arg.ServerID)
	return err
}
