// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: shop.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const applyBotFeaturedSlot = `-- name: ApplyBotFeaturedSlot :exec
UPDATE bots SET featured_until = GREATEST(COALESCE(featured_until, NOW()), NOW()) + make_interval(hours => $1) WHERE bot_id = $2
`

type ApplyBotFeaturedSlotParams struct {
	Hours int32  `db:"hours" json:"hours"`
	BotID string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) ApplyBotFeaturedSlot(ctx context.Context, arg ApplyBotFeaturedSlotParams) error {
	_, err := q.db.Exec(ctx, applyBotFeaturedSlot, arg.Hours, arg.BotID)
	return err
}

const applyBotPremiumDays = `-- name: ApplyBotPremiumDays :exec

UPDATE bots SET start_premium_period = NOW(), premium_period_length = make_interval(hours => $1), premium = true WHERE bot_id = $2
`

type ApplyBotPremiumDaysParams struct {
	Hours int32  `db:"hours" json:"hours"`
	BotID string `db:"bot_id" json:"bot_id"`
}

// ApplyBenefit (popplio/routes/shop/assets/benefits.go) dispatches on a
// fixed, never-user-controlled (targetType, benefitID) pair -- one explicit
// query per combination, same reasoning as db/queries/payments.sql.
func (q *Queries) ApplyBotPremiumDays(ctx context.Context, arg ApplyBotPremiumDaysParams) error {
	_, err := q.db.Exec(ctx, applyBotPremiumDays, arg.Hours, arg.BotID)
	return err
}

const applyBotPriorityBoost = `-- name: ApplyBotPriorityBoost :exec
UPDATE bots SET boosted_until = GREATEST(COALESCE(boosted_until, NOW()), NOW()) + make_interval(hours => $1) WHERE bot_id = $2
`

type ApplyBotPriorityBoostParams struct {
	Hours int32  `db:"hours" json:"hours"`
	BotID string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) ApplyBotPriorityBoost(ctx context.Context, arg ApplyBotPriorityBoostParams) error {
	_, err := q.db.Exec(ctx, applyBotPriorityBoost, arg.Hours, arg.BotID)
	return err
}

const applyBotSupporterBadge = `-- name: ApplyBotSupporterBadge :exec
UPDATE bots SET supporter_badge = true WHERE bot_id = $1
`

func (q *Queries) ApplyBotSupporterBadge(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, applyBotSupporterBadge, botID)
	return err
}

const applyBotVoteBlitz = `-- name: ApplyBotVoteBlitz :exec
UPDATE bots SET vote_blitz_until = GREATEST(COALESCE(vote_blitz_until, NOW()), NOW()) + make_interval(hours => $1) WHERE bot_id = $2
`

type ApplyBotVoteBlitzParams struct {
	Hours int32  `db:"hours" json:"hours"`
	BotID string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) ApplyBotVoteBlitz(ctx context.Context, arg ApplyBotVoteBlitzParams) error {
	_, err := q.db.Exec(ctx, applyBotVoteBlitz, arg.Hours, arg.BotID)
	return err
}

const applyServerFeaturedSlot = `-- name: ApplyServerFeaturedSlot :exec
UPDATE servers SET featured_until = GREATEST(COALESCE(featured_until, NOW()), NOW()) + make_interval(hours => $1) WHERE server_id = $2
`

type ApplyServerFeaturedSlotParams struct {
	Hours    int32  `db:"hours" json:"hours"`
	ServerID string `db:"server_id" json:"server_id"`
}

func (q *Queries) ApplyServerFeaturedSlot(ctx context.Context, arg ApplyServerFeaturedSlotParams) error {
	_, err := q.db.Exec(ctx, applyServerFeaturedSlot, arg.Hours, arg.ServerID)
	return err
}

const applyServerPremiumDays = `-- name: ApplyServerPremiumDays :exec
UPDATE servers SET start_premium_period = NOW(), premium_period_length = make_interval(hours => $1), premium = true WHERE server_id = $2
`

type ApplyServerPremiumDaysParams struct {
	Hours    int32  `db:"hours" json:"hours"`
	ServerID string `db:"server_id" json:"server_id"`
}

func (q *Queries) ApplyServerPremiumDays(ctx context.Context, arg ApplyServerPremiumDaysParams) error {
	_, err := q.db.Exec(ctx, applyServerPremiumDays, arg.Hours, arg.ServerID)
	return err
}

const applyServerPriorityBoost = `-- name: ApplyServerPriorityBoost :exec
UPDATE servers SET boosted_until = GREATEST(COALESCE(boosted_until, NOW()), NOW()) + make_interval(hours => $1) WHERE server_id = $2
`

type ApplyServerPriorityBoostParams struct {
	Hours    int32  `db:"hours" json:"hours"`
	ServerID string `db:"server_id" json:"server_id"`
}

func (q *Queries) ApplyServerPriorityBoost(ctx context.Context, arg ApplyServerPriorityBoostParams) error {
	_, err := q.db.Exec(ctx, applyServerPriorityBoost, arg.Hours, arg.ServerID)
	return err
}

const applyServerSupporterBadge = `-- name: ApplyServerSupporterBadge :exec
UPDATE servers SET supporter_badge = true WHERE server_id = $1
`

func (q *Queries) ApplyServerSupporterBadge(ctx context.Context, serverID string) error {
	_, err := q.db.Exec(ctx, applyServerSupporterBadge, serverID)
	return err
}

const applyServerVoteBlitz = `-- name: ApplyServerVoteBlitz :exec
UPDATE servers SET vote_blitz_until = GREATEST(COALESCE(vote_blitz_until, NOW()), NOW()) + make_interval(hours => $1) WHERE server_id = $2
`

type ApplyServerVoteBlitzParams struct {
	Hours    int32  `db:"hours" json:"hours"`
	ServerID string `db:"server_id" json:"server_id"`
}

func (q *Queries) ApplyServerVoteBlitz(ctx context.Context, arg ApplyServerVoteBlitzParams) error {
	_, err := q.db.Exec(ctx, applyServerVoteBlitz, arg.Hours, arg.ServerID)
	return err
}

const countBotWhitelistByBotID = `-- name: CountBotWhitelistByBotID :one
SELECT EXISTS(SELECT 1 FROM bot_whitelist WHERE bot_id = $1)
`

func (q *Queries) CountBotWhitelistByBotID(ctx context.Context, botID string) (bool, error) {
	row := q.db.QueryRow(ctx, countBotWhitelistByBotID, botID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countShopCouponByID = `-- name: CountShopCouponByID :one
SELECT EXISTS(SELECT 1 FROM shop_coupons WHERE id = $1)
`

func (q *Queries) CountShopCouponByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countShopCouponByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countShopCouponRedemptions = `-- name: CountShopCouponRedemptions :one
SELECT COUNT(*) FROM shop_coupon_redemptions WHERE coupon_id = $1
`

func (q *Queries) CountShopCouponRedemptions(ctx context.Context, couponID string) (int64, error) {
	row := q.db.QueryRow(ctx, countShopCouponRedemptions, couponID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countShopItemBenefitByID = `-- name: CountShopItemBenefitByID :one
SELECT EXISTS(SELECT 1 FROM shop_item_benefits WHERE id = $1)
`

func (q *Queries) CountShopItemBenefitByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countShopItemBenefitByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countShopItemByID = `-- name: CountShopItemByID :one

SELECT EXISTS(SELECT 1 FROM shop_items WHERE id = $1)
`

// Panel shop-item CRUD (db/queries/shop.sql's GetShopItems/GetShopItemByID
// are reused for the panel's own list/existence checks where the columns match).
func (q *Queries) CountShopItemByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countShopItemByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countShopItemsUsingBenefit = `-- name: CountShopItemsUsingBenefit :one
SELECT EXISTS(SELECT 1 FROM shop_items WHERE $1::text = ANY(benefits))
`

func (q *Queries) CountShopItemsUsingBenefit(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countShopItemsUsingBenefit, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const countVoteCreditTierByID = `-- name: CountVoteCreditTierByID :one
SELECT EXISTS(SELECT 1 FROM vote_credit_tiers WHERE id = $1)
`

func (q *Queries) CountVoteCreditTierByID(ctx context.Context, id string) (bool, error) {
	row := q.db.QueryRow(ctx, countVoteCreditTierByID, id)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const dedupTierPositions = `-- name: DedupTierPositions :exec
UPDATE vote_credit_tiers SET position = position + 1 WHERE position >= $1 AND id != $2
`

type DedupTierPositionsParams struct {
	Position int32  `db:"position" json:"position"`
	ID       string `db:"id" json:"id"`
}

func (q *Queries) DedupTierPositions(ctx context.Context, arg DedupTierPositionsParams) error {
	_, err := q.db.Exec(ctx, dedupTierPositions, arg.Position, arg.ID)
	return err
}

const deleteBotWhitelist = `-- name: DeleteBotWhitelist :exec
DELETE FROM bot_whitelist WHERE bot_id = $1
`

func (q *Queries) DeleteBotWhitelist(ctx context.Context, botID string) error {
	_, err := q.db.Exec(ctx, deleteBotWhitelist, botID)
	return err
}

const deleteShopCoupon = `-- name: DeleteShopCoupon :exec
DELETE FROM shop_coupons WHERE id = $1
`

func (q *Queries) DeleteShopCoupon(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteShopCoupon, id)
	return err
}

const deleteShopItem = `-- name: DeleteShopItem :exec
DELETE FROM shop_items WHERE id = $1
`

func (q *Queries) DeleteShopItem(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteShopItem, id)
	return err
}

const deleteShopItemBenefit = `-- name: DeleteShopItemBenefit :exec
DELETE FROM shop_item_benefits WHERE id = $1
`

func (q *Queries) DeleteShopItemBenefit(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteShopItemBenefit, id)
	return err
}

const deleteVoteCreditTier = `-- name: DeleteVoteCreditTier :exec
DELETE FROM vote_credit_tiers WHERE id = $1
`

func (q *Queries) DeleteVoteCreditTier(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteVoteCreditTier, id)
	return err
}

const getLastShopCouponRedemptionForTarget = `-- name: GetLastShopCouponRedemptionForTarget :one
SELECT created_at FROM shop_coupon_redemptions
WHERE coupon_id = $1 AND target_type = $2 AND target_id = $3
ORDER BY created_at DESC LIMIT 1
`

type GetLastShopCouponRedemptionForTargetParams struct {
	CouponID   string `db:"coupon_id" json:"coupon_id"`
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

func (q *Queries) GetLastShopCouponRedemptionForTarget(ctx context.Context, arg GetLastShopCouponRedemptionForTargetParams) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getLastShopCouponRedemptionForTarget, arg.CouponID, arg.TargetType, arg.TargetID)
	var created_at pgtype.Timestamptz
	err := row.Scan(&created_at)
	return created_at, err
}

const getPublicShopCoupons = `-- name: GetPublicShopCoupons :many
SELECT id, code, public, max_uses, created_at, created_by, last_updated, updated_by, reuse_wait_duration, expiry, applicable_items, requirements, allowed_users, usable, target_types, cents
FROM shop_coupons
WHERE public = true
AND usable = true
AND (expiry IS NULL OR created_at + make_interval(hours => expiry) > NOW())
AND (max_uses IS NULL OR (SELECT COUNT(*) FROM shop_coupon_redemptions WHERE coupon_id = shop_coupons.id) < max_uses)
ORDER BY created_at DESC
`

// Only coupons someone could actually redeem right now -- a disabled or
// expired coupon showing up in a public "available offers" list would be
// actively misleading, not just harmlessly stale.
func (q *Queries) GetPublicShopCoupons(ctx context.Context) ([]ShopCoupon, error) {
	rows, err := q.db.Query(ctx, getPublicShopCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopCoupon
	for rows.Next() {
		var i ShopCoupon
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Public,
			&i.MaxUses,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.LastUpdated,
			&i.UpdatedBy,
			&i.ReuseWaitDuration,
			&i.Expiry,
			&i.ApplicableItems,
			&i.Requirements,
			&i.AllowedUsers,
			&i.Usable,
			&i.TargetTypes,
			&i.Cents,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getRedeemableCreditBatches = `-- name: GetRedeemableCreditBatches :many
SELECT id, credits, redeemed_credits FROM entity_vote_redeem_logs WHERE target_id = $1 AND target_type = $2 AND redeemed_credits < credits ORDER BY created_at ASC FOR UPDATE
`

type GetRedeemableCreditBatchesParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

type GetRedeemableCreditBatchesRow struct {
	ID              pgtype.UUID `db:"id" json:"id"`
	Credits         int32       `db:"credits" json:"credits"`
	RedeemedCredits int32       `db:"redeemed_credits" json:"redeemed_credits"`
}

func (q *Queries) GetRedeemableCreditBatches(ctx context.Context, arg GetRedeemableCreditBatchesParams) ([]GetRedeemableCreditBatchesRow, error) {
	rows, err := q.db.Query(ctx, getRedeemableCreditBatches, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetRedeemableCreditBatchesRow
	for rows.Next() {
		var i GetRedeemableCreditBatchesRow
		if err := rows.Scan(&i.ID, &i.Credits, &i.RedeemedCredits); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShopCouponByCode = `-- name: GetShopCouponByCode :one

SELECT id, code, public, max_uses, created_at, created_by, last_updated, updated_by, reuse_wait_duration, expiry, applicable_items, requirements, allowed_users, usable, target_types, cents
FROM shop_coupons
WHERE code = $1
`

// Coupon redemption (purchase_shop_item route) -----------------------------
func (q *Queries) GetShopCouponByCode(ctx context.Context, code string) (ShopCoupon, error) {
	row := q.db.QueryRow(ctx, getShopCouponByCode, code)
	var i ShopCoupon
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Public,
		&i.MaxUses,
		&i.CreatedAt,
		&i.CreatedBy,
		&i.LastUpdated,
		&i.UpdatedBy,
		&i.ReuseWaitDuration,
		&i.Expiry,
		&i.ApplicableItems,
		&i.Requirements,
		&i.AllowedUsers,
		&i.Usable,
		&i.TargetTypes,
		&i.Cents,
	)
	return i, err
}

const getShopItemBenefits = `-- name: GetShopItemBenefits :many
SELECT id, name, description, created_at, last_updated, created_by, updated_by, target_types
FROM shop_item_benefits
ORDER BY created_at DESC
`

func (q *Queries) GetShopItemBenefits(ctx context.Context) ([]ShopItemBenefit, error) {
	rows, err := q.db.Query(ctx, getShopItemBenefits)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopItemBenefit
	for rows.Next() {
		var i ShopItemBenefit
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.LastUpdated,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.TargetTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShopItemByID = `-- name: GetShopItemByID :one
SELECT id, name, cents, target_types, benefits, created_at, last_updated, created_by, updated_by, duration, description
FROM shop_items
WHERE id = $1
`

func (q *Queries) GetShopItemByID(ctx context.Context, id string) (ShopItem, error) {
	row := q.db.QueryRow(ctx, getShopItemByID, id)
	var i ShopItem
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Cents,
		&i.TargetTypes,
		&i.Benefits,
		&i.CreatedAt,
		&i.LastUpdated,
		&i.CreatedBy,
		&i.UpdatedBy,
		&i.Duration,
		&i.Description,
	)
	return i, err
}

const getShopItems = `-- name: GetShopItems :many
SELECT id, name, cents, target_types, benefits, created_at, last_updated, created_by, updated_by, duration, description
FROM shop_items
ORDER BY created_at DESC
`

func (q *Queries) GetShopItems(ctx context.Context) ([]ShopItem, error) {
	rows, err := q.db.Query(ctx, getShopItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopItem
	for rows.Next() {
		var i ShopItem
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Cents,
			&i.TargetTypes,
			&i.Benefits,
			&i.CreatedAt,
			&i.LastUpdated,
			&i.CreatedBy,
			&i.UpdatedBy,
			&i.Duration,
			&i.Description,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getShopPurchasesByTarget = `-- name: GetShopPurchasesByTarget :many
SELECT id, target_type, target_id, item_id, cents, created_at
FROM shop_purchases
WHERE target_id = $1 AND target_type = $2
ORDER BY created_at DESC
`

type GetShopPurchasesByTargetParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) GetShopPurchasesByTarget(ctx context.Context, arg GetShopPurchasesByTargetParams) ([]ShopPurchase, error) {
	rows, err := q.db.Query(ctx, getShopPurchasesByTarget, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ShopPurchase
	for rows.Next() {
		var i ShopPurchase
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.TargetID,
			&i.ItemID,
			&i.Cents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertBotWhitelist = `-- name: InsertBotWhitelist :exec
INSERT INTO bot_whitelist (user_id, bot_id, reason) VALUES ($1, $2, $3)
`

type InsertBotWhitelistParams struct {
	UserID string `db:"user_id" json:"user_id"`
	BotID  string `db:"bot_id" json:"bot_id"`
	Reason string `db:"reason" json:"reason"`
}

func (q *Queries) InsertBotWhitelist(ctx context.Context, arg InsertBotWhitelistParams) error {
	_, err := q.db.Exec(ctx, insertBotWhitelist, arg.UserID, arg.BotID, arg.Reason)
	return err
}

const insertShopCoupon = `-- name: InsertShopCoupon :exec
INSERT INTO shop_coupons (id, code, public, max_uses, created_by, updated_by, reuse_wait_duration, expiry, applicable_items, cents, requirements, allowed_users, usable, target_types)
VALUES ($1, $2, $3, $4, $5, $5, $6, $7, $8, $9, $10, $11, $12, $13)
`

type InsertShopCouponParams struct {
	ID                string        `db:"id" json:"id"`
	Code              string        `db:"code" json:"code"`
	Public            bool          `db:"public" json:"public"`
	MaxUses           pgtype.Int4   `db:"max_uses" json:"max_uses"`
	CreatedBy         string        `db:"created_by" json:"created_by"`
	ReuseWaitDuration pgtype.Int4   `db:"reuse_wait_duration" json:"reuse_wait_duration"`
	Expiry            pgtype.Int4   `db:"expiry" json:"expiry"`
	ApplicableItems   []string      `db:"applicable_items" json:"applicable_items"`
	Cents             pgtype.Float8 `db:"cents" json:"cents"`
	Requirements      []string      `db:"requirements" json:"requirements"`
	AllowedUsers      []string      `db:"allowed_users" json:"allowed_users"`
	Usable            bool          `db:"usable" json:"usable"`
	TargetTypes       []string      `db:"target_types" json:"target_types"`
}

func (q *Queries) InsertShopCoupon(ctx context.Context, arg InsertShopCouponParams) error {
	_, err := q.db.Exec(ctx, insertShopCoupon,
		arg.ID,
		arg.Code,
		arg.Public,
		arg.MaxUses,
		arg.CreatedBy,
		arg.ReuseWaitDuration,
		arg.Expiry,
		arg.ApplicableItems,
		arg.Cents,
		arg.Requirements,
		arg.AllowedUsers,
		arg.Usable,
		arg.TargetTypes,
	)
	return err
}

const insertShopCouponRedemption = `-- name: InsertShopCouponRedemption :exec
INSERT INTO shop_coupon_redemptions (coupon_id, target_type, target_id, redeemed_by)
VALUES ($1, $2, $3, $4)
`

type InsertShopCouponRedemptionParams struct {
	CouponID   string `db:"coupon_id" json:"coupon_id"`
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
	RedeemedBy string `db:"redeemed_by" json:"redeemed_by"`
}

func (q *Queries) InsertShopCouponRedemption(ctx context.Context, arg InsertShopCouponRedemptionParams) error {
	_, err := q.db.Exec(ctx, insertShopCouponRedemption,
		arg.CouponID,
		arg.TargetType,
		arg.TargetID,
		arg.RedeemedBy,
	)
	return err
}

const insertShopItem = `-- name: InsertShopItem :exec
INSERT INTO shop_items (id, name, cents, target_types, benefits, created_by, updated_by, duration, description)
VALUES ($1, $2, $3, $4, $5, $6, $6, $7, $8)
`

type InsertShopItemParams struct {
	ID          string   `db:"id" json:"id"`
	Name        string   `db:"name" json:"name"`
	Cents       float64  `db:"cents" json:"cents"`
	TargetTypes []string `db:"target_types" json:"target_types"`
	Benefits    []string `db:"benefits" json:"benefits"`
	CreatedBy   string   `db:"created_by" json:"created_by"`
	Duration    int64    `db:"duration" json:"duration"`
	Description string   `db:"description" json:"description"`
}

func (q *Queries) InsertShopItem(ctx context.Context, arg InsertShopItemParams) error {
	_, err := q.db.Exec(ctx, insertShopItem,
		arg.ID,
		arg.Name,
		arg.Cents,
		arg.TargetTypes,
		arg.Benefits,
		arg.CreatedBy,
		arg.Duration,
		arg.Description,
	)
	return err
}

const insertShopItemBenefit = `-- name: InsertShopItemBenefit :exec
INSERT INTO shop_item_benefits (id, name, description, target_types, created_by, updated_by) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertShopItemBenefitParams struct {
	ID          string   `db:"id" json:"id"`
	Name        string   `db:"name" json:"name"`
	Description string   `db:"description" json:"description"`
	TargetTypes []string `db:"target_types" json:"target_types"`
	CreatedBy   string   `db:"created_by" json:"created_by"`
	UpdatedBy   string   `db:"updated_by" json:"updated_by"`
}

func (q *Queries) InsertShopItemBenefit(ctx context.Context, arg InsertShopItemBenefitParams) error {
	_, err := q.db.Exec(ctx, insertShopItemBenefit,
		arg.ID,
		arg.Name,
		arg.Description,
		arg.TargetTypes,
		arg.CreatedBy,
		arg.UpdatedBy,
	)
	return err
}

const insertShopPurchase = `-- name: InsertShopPurchase :exec
INSERT INTO shop_purchases (target_type, target_id, item_id, cents) VALUES ($1, $2, $3, $4)
`

type InsertShopPurchaseParams struct {
	TargetType string  `db:"target_type" json:"target_type"`
	TargetID   string  `db:"target_id" json:"target_id"`
	ItemID     string  `db:"item_id" json:"item_id"`
	Cents      float64 `db:"cents" json:"cents"`
}

func (q *Queries) InsertShopPurchase(ctx context.Context, arg InsertShopPurchaseParams) error {
	_, err := q.db.Exec(ctx, insertShopPurchase,
		arg.TargetType,
		arg.TargetID,
		arg.ItemID,
		arg.Cents,
	)
	return err
}

const insertVoteCreditTier = `-- name: InsertVoteCreditTier :exec
INSERT INTO vote_credit_tiers (id, target_type, position, cents, votes) VALUES ($1, $2, $3, $4, $5)
`

type InsertVoteCreditTierParams struct {
	ID         string `db:"id" json:"id"`
	TargetType string `db:"target_type" json:"target_type"`
	Position   int32  `db:"position" json:"position"`
	Cents      int32  `db:"cents" json:"cents"`
	Votes      int32  `db:"votes" json:"votes"`
}

func (q *Queries) InsertVoteCreditTier(ctx context.Context, arg InsertVoteCreditTierParams) error {
	_, err := q.db.Exec(ctx, insertVoteCreditTier,
		arg.ID,
		arg.TargetType,
		arg.Position,
		arg.Cents,
		arg.Votes,
	)
	return err
}

const listBotWhitelist = `-- name: ListBotWhitelist :many
SELECT bot_id, user_id, reason, created_at FROM bot_whitelist ORDER BY created_at DESC
`

type ListBotWhitelistRow struct {
	BotID     string             `db:"bot_id" json:"bot_id"`
	UserID    string             `db:"user_id" json:"user_id"`
	Reason    string             `db:"reason" json:"reason"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListBotWhitelist(ctx context.Context) ([]ListBotWhitelistRow, error) {
	rows, err := q.db.Query(ctx, listBotWhitelist)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBotWhitelistRow
	for rows.Next() {
		var i ListBotWhitelistRow
		if err := rows.Scan(
			&i.BotID,
			&i.UserID,
			&i.Reason,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listShopCoupons = `-- name: ListShopCoupons :many
SELECT id, code, public, max_uses, created_at, created_by, last_updated, updated_by, reuse_wait_duration, expiry, applicable_items, cents, requirements, allowed_users, usable, target_types
FROM shop_coupons ORDER BY created_at DESC
`

type ListShopCouponsRow struct {
	ID                string             `db:"id" json:"id"`
	Code              string             `db:"code" json:"code"`
	Public            bool               `db:"public" json:"public"`
	MaxUses           pgtype.Int4        `db:"max_uses" json:"max_uses"`
	CreatedAt         pgtype.Timestamptz `db:"created_at" json:"created_at"`
	CreatedBy         string             `db:"created_by" json:"created_by"`
	LastUpdated       pgtype.Timestamptz `db:"last_updated" json:"last_updated"`
	UpdatedBy         string             `db:"updated_by" json:"updated_by"`
	ReuseWaitDuration pgtype.Int4        `db:"reuse_wait_duration" json:"reuse_wait_duration"`
	Expiry            pgtype.Int4        `db:"expiry" json:"expiry"`
	ApplicableItems   []string           `db:"applicable_items" json:"applicable_items"`
	Cents             pgtype.Float8      `db:"cents" json:"cents"`
	Requirements      []string           `db:"requirements" json:"requirements"`
	AllowedUsers      []string           `db:"allowed_users" json:"allowed_users"`
	Usable            bool               `db:"usable" json:"usable"`
	TargetTypes       []string           `db:"target_types" json:"target_types"`
}

func (q *Queries) ListShopCoupons(ctx context.Context) ([]ListShopCouponsRow, error) {
	rows, err := q.db.Query(ctx, listShopCoupons)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListShopCouponsRow
	for rows.Next() {
		var i ListShopCouponsRow
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Public,
			&i.MaxUses,
			&i.CreatedAt,
			&i.CreatedBy,
			&i.LastUpdated,
			&i.UpdatedBy,
			&i.ReuseWaitDuration,
			&i.Expiry,
			&i.ApplicableItems,
			&i.Cents,
			&i.Requirements,
			&i.AllowedUsers,
			&i.Usable,
			&i.TargetTypes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVoteCreditTiers = `-- name: ListVoteCreditTiers :many
SELECT id, target_type, position, cents, votes, created_at FROM vote_credit_tiers ORDER BY position ASC
`

type ListVoteCreditTiersRow struct {
	ID         string             `db:"id" json:"id"`
	TargetType string             `db:"target_type" json:"target_type"`
	Position   int32              `db:"position" json:"position"`
	Cents      int32              `db:"cents" json:"cents"`
	Votes      int32              `db:"votes" json:"votes"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) ListVoteCreditTiers(ctx context.Context) ([]ListVoteCreditTiersRow, error) {
	rows, err := q.db.Query(ctx, listVoteCreditTiers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListVoteCreditTiersRow
	for rows.Next() {
		var i ListVoteCreditTiersRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.Position,
			&i.Cents,
			&i.Votes,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const spendCreditBatch = `-- name: SpendCreditBatch :exec
UPDATE entity_vote_redeem_logs SET redeemed_credits = redeemed_credits + $1, redeemed_at = NOW() WHERE id = $2
`

type SpendCreditBatchParams struct {
	RedeemedCredits int32       `db:"redeemed_credits" json:"redeemed_credits"`
	ID              pgtype.UUID `db:"id" json:"id"`
}

func (q *Queries) SpendCreditBatch(ctx context.Context, arg SpendCreditBatchParams) error {
	_, err := q.db.Exec(ctx, spendCreditBatch, arg.RedeemedCredits, arg.ID)
	return err
}

const updateBotWhitelistReason = `-- name: UpdateBotWhitelistReason :exec
UPDATE bot_whitelist SET reason = $1 WHERE bot_id = $2
`

type UpdateBotWhitelistReasonParams struct {
	Reason string `db:"reason" json:"reason"`
	BotID  string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotWhitelistReason(ctx context.Context, arg UpdateBotWhitelistReasonParams) error {
	_, err := q.db.Exec(ctx, updateBotWhitelistReason, arg.Reason, arg.BotID)
	return err
}

const updateShopCoupon = `-- name: UpdateShopCoupon :exec
UPDATE shop_coupons SET code = $1, public = $2, max_uses = $3, reuse_wait_duration = $4, expiry = $5, applicable_items = $6, cents = $7, requirements = $8, updated_by = $9, last_updated = NOW(), allowed_users = $10, usable = $11, target_types = $12 WHERE id = $13
`

type UpdateShopCouponParams struct {
	Code              string        `db:"code" json:"code"`
	Public            bool          `db:"public" json:"public"`
	MaxUses           pgtype.Int4   `db:"max_uses" json:"max_uses"`
	ReuseWaitDuration pgtype.Int4   `db:"reuse_wait_duration" json:"reuse_wait_duration"`
	Expiry            pgtype.Int4   `db:"expiry" json:"expiry"`
	ApplicableItems   []string      `db:"applicable_items" json:"applicable_items"`
	Cents             pgtype.Float8 `db:"cents" json:"cents"`
	Requirements      []string      `db:"requirements" json:"requirements"`
	UpdatedBy         string        `db:"updated_by" json:"updated_by"`
	AllowedUsers      []string      `db:"allowed_users" json:"allowed_users"`
	Usable            bool          `db:"usable" json:"usable"`
	TargetTypes       []string      `db:"target_types" json:"target_types"`
	ID                string        `db:"id" json:"id"`
}

func (q *Queries) UpdateShopCoupon(ctx context.Context, arg UpdateShopCouponParams) error {
	_, err := q.db.Exec(ctx, updateShopCoupon,
		arg.Code,
		arg.Public,
		arg.MaxUses,
		arg.ReuseWaitDuration,
		arg.Expiry,
		arg.ApplicableItems,
		arg.Cents,
		arg.Requirements,
		arg.UpdatedBy,
		arg.AllowedUsers,
		arg.Usable,
		arg.TargetTypes,
		arg.ID,
	)
	return err
}

const updateShopItem = `-- name: UpdateShopItem :exec
UPDATE shop_items SET name = $1, cents = $2, target_types = $3, benefits = $4, last_updated = NOW(), updated_by = $5, duration = $6, description = $7 WHERE id = $8
`

type UpdateShopItemParams struct {
	Name        string   `db:"name" json:"name"`
	Cents       float64  `db:"cents" json:"cents"`
	TargetTypes []string `db:"target_types" json:"target_types"`
	Benefits    []string `db:"benefits" json:"benefits"`
	UpdatedBy   string   `db:"updated_by" json:"updated_by"`
	Duration    int64    `db:"duration" json:"duration"`
	Description string   `db:"description" json:"description"`
	ID          string   `db:"id" json:"id"`
}

func (q *Queries) UpdateShopItem(ctx context.Context, arg UpdateShopItemParams) error {
	_, err := q.db.Exec(ctx, updateShopItem,
		arg.Name,
		arg.Cents,
		arg.TargetTypes,
		arg.Benefits,
		arg.UpdatedBy,
		arg.Duration,
		arg.Description,
		arg.ID,
	)
	return err
}

const updateShopItemBenefit = `-- name: UpdateShopItemBenefit :exec
UPDATE shop_item_benefits SET name = $1, description = $2, last_updated = NOW(), updated_by = $3, target_types = $4 WHERE id = $5
`

type UpdateShopItemBenefitParams struct {
	Name        string   `db:"name" json:"name"`
	Description string   `db:"description" json:"description"`
	UpdatedBy   string   `db:"updated_by" json:"updated_by"`
	TargetTypes []string `db:"target_types" json:"target_types"`
	ID          string   `db:"id" json:"id"`
}

func (q *Queries) UpdateShopItemBenefit(ctx context.Context, arg UpdateShopItemBenefitParams) error {
	_, err := q.db.Exec(ctx, updateShopItemBenefit,
		arg.Name,
		arg.Description,
		arg.UpdatedBy,
		arg.TargetTypes,
		arg.ID,
	)
	return err
}

const updateVoteCreditTier = `-- name: UpdateVoteCreditTier :exec
UPDATE vote_credit_tiers SET position = $1, target_type = $2, cents = $3, votes = $4 WHERE id = $5
`

type UpdateVoteCreditTierParams struct {
	Position   int32  `db:"position" json:"position"`
	TargetType string `db:"target_type" json:"target_type"`
	Cents      int32  `db:"cents" json:"cents"`
	Votes      int32  `db:"votes" json:"votes"`
	ID         string `db:"id" json:"id"`
}

func (q *Queries) UpdateVoteCreditTier(ctx context.Context, arg UpdateVoteCreditTierParams) error {
	_, err := q.db.Exec(ctx, updateVoteCreditTier,
		arg.Position,
		arg.TargetType,
		arg.Cents,
		arg.Votes,
		arg.ID,
	)
	return err
}
