// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tasks.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTaskStatus = `-- name: AppendTaskStatus :exec
UPDATE tasks SET statuses = array_append(statuses, $1) WHERE task_id = $2
`

type AppendTaskStatusParams struct {
	ArrayAppend interface{} `db:"array_append" json:"array_append"`
	TaskID      string      `db:"task_id" json:"task_id"`
}

func (q *Queries) AppendTaskStatus(ctx context.Context, arg AppendTaskStatusParams) error {
	_, err := q.db.Exec(ctx, appendTaskStatus, arg.ArrayAppend, arg.TaskID)
	return err
}

const deleteExpiredTasks = `-- name: DeleteExpiredTasks :exec
DELETE FROM tasks WHERE created_at + expiry < NOW()
`

func (q *Queries) DeleteExpiredTasks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteExpiredTasks)
	return err
}

const deleteOldDataTasks = `-- name: DeleteOldDataTasks :exec
DELETE FROM tasks WHERE task_name = $1 AND task_id != $2 AND for_user = $3
`

type DeleteOldDataTasksParams struct {
	TaskName string      `db:"task_name" json:"task_name"`
	TaskID   string      `db:"task_id" json:"task_id"`
	ForUser  pgtype.Text `db:"for_user" json:"for_user"`
}

func (q *Queries) DeleteOldDataTasks(ctx context.Context, arg DeleteOldDataTasksParams) error {
	_, err := q.db.Exec(ctx, deleteOldDataTasks, arg.TaskName, arg.TaskID, arg.ForUser)
	return err
}

const getTask = `-- name: GetTask :one
SELECT task_id, task_key, allow_unauthenticated, task_name, output, statuses, for_user, expiry, state, created_at
FROM tasks
WHERE task_id = $1
`

type GetTaskRow struct {
	TaskID               string           `db:"task_id" json:"task_id"`
	TaskKey              pgtype.Text      `db:"task_key" json:"task_key"`
	AllowUnauthenticated bool             `db:"allow_unauthenticated" json:"allow_unauthenticated"`
	TaskName             string           `db:"task_name" json:"task_name"`
	Output               map[string]any   `db:"output" json:"output"`
	Statuses             []map[string]any `db:"statuses" json:"statuses"`
	ForUser              pgtype.Text      `db:"for_user" json:"for_user"`
	Expiry               pgtype.Interval  `db:"expiry" json:"expiry"`
	State                string           `db:"state" json:"state"`
	CreatedAt            pgtype.Timestamp `db:"created_at" json:"created_at"`
}

func (q *Queries) GetTask(ctx context.Context, taskID string) (GetTaskRow, error) {
	row := q.db.QueryRow(ctx, getTask, taskID)
	var i GetTaskRow
	err := row.Scan(
		&i.TaskID,
		&i.TaskKey,
		&i.AllowUnauthenticated,
		&i.TaskName,
		&i.Output,
		&i.Statuses,
		&i.ForUser,
		&i.Expiry,
		&i.State,
		&i.CreatedAt,
	)
	return i, err
}

const insertTask = `-- name: InsertTask :one
INSERT INTO tasks (task_name, task_key, for_user, expiry, output, allow_unauthenticated)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING task_id
`

type InsertTaskParams struct {
	TaskName             string          `db:"task_name" json:"task_name"`
	TaskKey              pgtype.Text     `db:"task_key" json:"task_key"`
	ForUser              pgtype.Text     `db:"for_user" json:"for_user"`
	Expiry               pgtype.Interval `db:"expiry" json:"expiry"`
	Output               map[string]any  `db:"output" json:"output"`
	AllowUnauthenticated bool            `db:"allow_unauthenticated" json:"allow_unauthenticated"`
}

func (q *Queries) InsertTask(ctx context.Context, arg InsertTaskParams) (string, error) {
	row := q.db.QueryRow(ctx, insertTask,
		arg.TaskName,
		arg.TaskKey,
		arg.ForUser,
		arg.Expiry,
		arg.Output,
		arg.AllowUnauthenticated,
	)
	var task_id string
	err := row.Scan(&task_id)
	return task_id, err
}

const updateTaskOutputAndState = `-- name: UpdateTaskOutputAndState :exec
UPDATE tasks SET output = $1, state = $2 WHERE task_id = $3
`

type UpdateTaskOutputAndStateParams struct {
	Output map[string]any `db:"output" json:"output"`
	State  string         `db:"state" json:"state"`
	TaskID string         `db:"task_id" json:"task_id"`
}

func (q *Queries) UpdateTaskOutputAndState(ctx context.Context, arg UpdateTaskOutputAndStateParams) error {
	_, err := q.db.Exec(ctx, updateTaskOutputAndState, arg.Output, arg.State, arg.TaskID)
	return err
}

const updateTaskState = `-- name: UpdateTaskState :exec
UPDATE tasks SET state = $1 WHERE task_id = $2
`

type UpdateTaskStateParams struct {
	State  string `db:"state" json:"state"`
	TaskID string `db:"task_id" json:"task_id"`
}

func (q *Queries) UpdateTaskState(ctx context.Context, arg UpdateTaskStateParams) error {
	_, err := q.db.Exec(ctx, updateTaskState, arg.State, arg.TaskID)
	return err
}
