// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: teams.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countBotsByTeamOwner = `-- name: CountBotsByTeamOwner :one
SELECT COUNT(*) FROM bots WHERE team_owner = $1
`

func (q *Queries) CountBotsByTeamOwner(ctx context.Context, teamOwner pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countBotsByTeamOwner, teamOwner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countServersByTeamOwner = `-- name: CountServersByTeamOwner :one
SELECT COUNT(*) FROM servers WHERE team_owner = $1
`

func (q *Queries) CountServersByTeamOwner(ctx context.Context, teamOwner pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countServersByTeamOwner, teamOwner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamDataHolders = `-- name: CountTeamDataHolders :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1 AND data_holder = $2 AND user_id != $3
`

type CountTeamDataHoldersParams struct {
	TeamID     pgtype.UUID `db:"team_id" json:"team_id"`
	DataHolder bool        `db:"data_holder" json:"data_holder"`
	UserID     string      `db:"user_id" json:"user_id"`
}

func (q *Queries) CountTeamDataHolders(ctx context.Context, arg CountTeamDataHoldersParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamDataHolders, arg.TeamID, arg.DataHolder, arg.UserID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamDataHoldersForTeam = `-- name: CountTeamDataHoldersForTeam :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1 AND data_holder = true
`

func (q *Queries) CountTeamDataHoldersForTeam(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamDataHoldersForTeam, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMembers = `-- name: CountTeamMembers :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1
`

func (q *Queries) CountTeamMembers(ctx context.Context, teamID pgtype.UUID) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembers, teamID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamMembership = `-- name: CountTeamMembership :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1 AND (user_id = $2 OR user_id = $3)
`

type CountTeamMembershipParams struct {
	TeamID   pgtype.UUID `db:"team_id" json:"team_id"`
	UserID   string      `db:"user_id" json:"user_id"`
	UserID_2 string      `db:"user_id_2" json:"user_id_2"`
}

func (q *Queries) CountTeamMembership(ctx context.Context, arg CountTeamMembershipParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamMembership, arg.TeamID, arg.UserID, arg.UserID_2)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countTeamOwnersWithFlag = `-- name: CountTeamOwnersWithFlag :one
SELECT COUNT(*) FROM team_members WHERE team_id = $1 AND flags && $2::text[]
`

type CountTeamOwnersWithFlagParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	Flags  []string    `db:"flags" json:"flags"`
}

func (q *Queries) CountTeamOwnersWithFlag(ctx context.Context, arg CountTeamOwnersWithFlagParams) (int64, error) {
	row := q.db.QueryRow(ctx, countTeamOwnersWithFlag, arg.TeamID, arg.Flags)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteInfernoplexTeamMember = `-- name: DeleteInfernoplexTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2 AND service = 'infernoplex'
`

type DeleteInfernoplexTeamMemberParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteInfernoplexTeamMember(ctx context.Context, arg DeleteInfernoplexTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteInfernoplexTeamMember, arg.TeamID, arg.UserID)
	return err
}

const deleteTeam = `-- name: DeleteTeam :exec
DELETE FROM teams WHERE id = $1
`

func (q *Queries) DeleteTeam(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTeam, id)
	return err
}

const deleteTeamMember = `-- name: DeleteTeamMember :exec
DELETE FROM team_members WHERE team_id = $1 AND user_id = $2
`

type DeleteTeamMemberParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) DeleteTeamMember(ctx context.Context, arg DeleteTeamMemberParams) error {
	_, err := q.db.Exec(ctx, deleteTeamMember, arg.TeamID, arg.UserID)
	return err
}

const deleteTeamMembers = `-- name: DeleteTeamMembers :exec
DELETE FROM team_members WHERE team_id = $1
`

func (q *Queries) DeleteTeamMembers(ctx context.Context, teamID pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteTeamMembers, teamID)
	return err
}

const deleteVanityByItag = `-- name: DeleteVanityByItag :exec
DELETE FROM vanity WHERE itag = $1
`

func (q *Queries) DeleteVanityByItag(ctx context.Context, itag pgtype.UUID) error {
	_, err := q.db.Exec(ctx, deleteVanityByItag, itag)
	return err
}

const getAllTeamIDs = `-- name: GetAllTeamIDs :many
SELECT id FROM teams
`

func (q *Queries) GetAllTeamIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getAllTeamIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getFirstTeamMemberUserID = `-- name: GetFirstTeamMemberUserID :one
SELECT user_id FROM team_members WHERE team_id = $1 LIMIT 1
`

func (q *Queries) GetFirstTeamMemberUserID(ctx context.Context, teamID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getFirstTeamMemberUserID, teamID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getInfernoplexTeamServerMembers = `-- name: GetInfernoplexTeamServerMembers :many
SELECT tm.team_id, tm.user_id, s.server_id
FROM team_members tm
JOIN servers s ON s.team_owner = tm.team_id
WHERE tm.service = 'infernoplex'
`

type GetInfernoplexTeamServerMembersRow struct {
	TeamID   pgtype.UUID `db:"team_id" json:"team_id"`
	UserID   string      `db:"user_id" json:"user_id"`
	ServerID string      `db:"server_id" json:"server_id"`
}

func (q *Queries) GetInfernoplexTeamServerMembers(ctx context.Context) ([]GetInfernoplexTeamServerMembersRow, error) {
	rows, err := q.db.Query(ctx, getInfernoplexTeamServerMembers)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetInfernoplexTeamServerMembersRow
	for rows.Next() {
		var i GetInfernoplexTeamServerMembersRow
		if err := rows.Scan(&i.TeamID, &i.UserID, &i.ServerID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamByID = `-- name: GetTeamByID :one
SELECT id, name, short, tags, vote_banned, approximate_votes, extra_links, nsfw, vanity_ref, service, created_at, updated_at
FROM teams
WHERE id = $1
`

type GetTeamByIDRow struct {
	ID               string             `db:"id" json:"id"`
	Name             string             `db:"name" json:"name"`
	Short            pgtype.Text        `db:"short" json:"short"`
	Tags             []string           `db:"tags" json:"tags"`
	VoteBanned       bool               `db:"vote_banned" json:"vote_banned"`
	ApproximateVotes int32              `db:"approximate_votes" json:"approximate_votes"`
	ExtraLinks       []byte             `db:"extra_links" json:"extra_links"`
	Nsfw             bool               `db:"nsfw" json:"nsfw"`
	VanityRef        pgtype.UUID        `db:"vanity_ref" json:"vanity_ref"`
	Service          string             `db:"service" json:"service"`
	CreatedAt        pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTeamByID(ctx context.Context, id string) (GetTeamByIDRow, error) {
	row := q.db.QueryRow(ctx, getTeamByID, id)
	var i GetTeamByIDRow
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.Short,
		&i.Tags,
		&i.VoteBanned,
		&i.ApproximateVotes,
		&i.ExtraLinks,
		&i.Nsfw,
		&i.VanityRef,
		&i.Service,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getTeamDataHolderUserID = `-- name: GetTeamDataHolderUserID :one
SELECT user_id FROM team_members WHERE team_id = $1 AND data_holder = true LIMIT 1
`

func (q *Queries) GetTeamDataHolderUserID(ctx context.Context, teamID pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getTeamDataHolderUserID, teamID)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getTeamInfoForEdit = `-- name: GetTeamInfoForEdit :one
SELECT name, short, tags, extra_links, nsfw FROM teams WHERE id = $1
`

type GetTeamInfoForEditRow struct {
	Name       string      `db:"name" json:"name"`
	Short      pgtype.Text `db:"short" json:"short"`
	Tags       []string    `db:"tags" json:"tags"`
	ExtraLinks []byte      `db:"extra_links" json:"extra_links"`
	Nsfw       bool        `db:"nsfw" json:"nsfw"`
}

func (q *Queries) GetTeamInfoForEdit(ctx context.Context, id string) (GetTeamInfoForEditRow, error) {
	row := q.db.QueryRow(ctx, getTeamInfoForEdit, id)
	var i GetTeamInfoForEditRow
	err := row.Scan(
		&i.Name,
		&i.Short,
		&i.Tags,
		&i.ExtraLinks,
		&i.Nsfw,
	)
	return i, err
}

const getTeamMemberFlags = `-- name: GetTeamMemberFlags :one
SELECT flags FROM team_members WHERE team_id = $1 AND user_id = $2
`

type GetTeamMemberFlagsParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) GetTeamMemberFlags(ctx context.Context, arg GetTeamMemberFlagsParams) ([]string, error) {
	row := q.db.QueryRow(ctx, getTeamMemberFlags, arg.TeamID, arg.UserID)
	var flags []string
	err := row.Scan(&flags)
	return flags, err
}

const getTeamMemberUserIDs = `-- name: GetTeamMemberUserIDs :many
SELECT user_id FROM team_members WHERE team_id = $1
`

func (q *Queries) GetTeamMemberUserIDs(ctx context.Context, teamID pgtype.UUID) ([]string, error) {
	rows, err := q.db.Query(ctx, getTeamMemberUserIDs, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembersByTeamID = `-- name: GetTeamMembersByTeamID :many
SELECT itag, team_id, user_id, flags, service, created_at, mentionable, data_holder
FROM team_members
WHERE team_id = $1
`

type GetTeamMembersByTeamIDRow struct {
	Itag        pgtype.UUID        `db:"itag" json:"itag"`
	TeamID      pgtype.UUID        `db:"team_id" json:"team_id"`
	UserID      string             `db:"user_id" json:"user_id"`
	Flags       []string           `db:"flags" json:"flags"`
	Service     string             `db:"service" json:"service"`
	CreatedAt   pgtype.Timestamptz `db:"created_at" json:"created_at"`
	Mentionable bool               `db:"mentionable" json:"mentionable"`
	DataHolder  bool               `db:"data_holder" json:"data_holder"`
}

func (q *Queries) GetTeamMembersByTeamID(ctx context.Context, teamID pgtype.UUID) ([]GetTeamMembersByTeamIDRow, error) {
	rows, err := q.db.Query(ctx, getTeamMembersByTeamID, teamID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTeamMembersByTeamIDRow
	for rows.Next() {
		var i GetTeamMembersByTeamIDRow
		if err := rows.Scan(
			&i.Itag,
			&i.TeamID,
			&i.UserID,
			&i.Flags,
			&i.Service,
			&i.CreatedAt,
			&i.Mentionable,
			&i.DataHolder,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamMembersWithFlag = `-- name: GetTeamMembersWithFlag :many
SELECT user_id FROM team_members WHERE team_id = $1 AND flags @> ARRAY[$2::text]
`

type GetTeamMembersWithFlagParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	Flag   string      `db:"flag" json:"flag"`
}

func (q *Queries) GetTeamMembersWithFlag(ctx context.Context, arg GetTeamMembersWithFlagParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getTeamMembersWithFlag, arg.TeamID, arg.Flag)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTeamSEO = `-- name: GetTeamSEO :one
SELECT id, name, short FROM teams WHERE id = $1
`

type GetTeamSEORow struct {
	ID    string      `db:"id" json:"id"`
	Name  string      `db:"name" json:"name"`
	Short pgtype.Text `db:"short" json:"short"`
}

func (q *Queries) GetTeamSEO(ctx context.Context, id string) (GetTeamSEORow, error) {
	row := q.db.QueryRow(ctx, getTeamSEO, id)
	var i GetTeamSEORow
	err := row.Scan(&i.ID, &i.Name, &i.Short)
	return i, err
}

const getTeamSEOFields = `-- name: GetTeamSEOFields :one
SELECT name, short, created_at, updated_at FROM teams WHERE id = $1
`

type GetTeamSEOFieldsRow struct {
	Name      string             `db:"name" json:"name"`
	Short     pgtype.Text        `db:"short" json:"short"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetTeamSEOFields(ctx context.Context, id string) (GetTeamSEOFieldsRow, error) {
	row := q.db.QueryRow(ctx, getTeamSEOFields, id)
	var i GetTeamSEOFieldsRow
	err := row.Scan(
		&i.Name,
		&i.Short,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserTeamIDs = `-- name: GetUserTeamIDs :many
SELECT team_id FROM team_members WHERE user_id = $1
`

func (q *Queries) GetUserTeamIDs(ctx context.Context, userID string) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getUserTeamIDs, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var team_id pgtype.UUID
		if err := rows.Scan(&team_id); err != nil {
			return nil, err
		}
		items = append(items, team_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserTeamMembershipsForDataTask = `-- name: GetUserTeamMembershipsForDataTask :many
SELECT team_id, flags, data_holder FROM team_members WHERE user_id = $1
`

type GetUserTeamMembershipsForDataTaskRow struct {
	TeamID     pgtype.UUID `db:"team_id" json:"team_id"`
	Flags      []string    `db:"flags" json:"flags"`
	DataHolder bool        `db:"data_holder" json:"data_holder"`
}

func (q *Queries) GetUserTeamMembershipsForDataTask(ctx context.Context, userID string) ([]GetUserTeamMembershipsForDataTaskRow, error) {
	rows, err := q.db.Query(ctx, getUserTeamMembershipsForDataTask, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTeamMembershipsForDataTaskRow
	for rows.Next() {
		var i GetUserTeamMembershipsForDataTaskRow
		if err := rows.Scan(&i.TeamID, &i.Flags, &i.DataHolder); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVanityCodeByItag = `-- name: GetVanityCodeByItag :one
SELECT code FROM vanity WHERE itag = $1
`

func (q *Queries) GetVanityCodeByItag(ctx context.Context, itag pgtype.UUID) (string, error) {
	row := q.db.QueryRow(ctx, getVanityCodeByItag, itag)
	var code string
	err := row.Scan(&code)
	return code, err
}

const insertTeam = `-- name: InsertTeam :exec
INSERT INTO teams (id, name, short, tags, extra_links, nsfw, vanity_ref) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertTeamParams struct {
	ID         string      `db:"id" json:"id"`
	Name       string      `db:"name" json:"name"`
	Short      pgtype.Text `db:"short" json:"short"`
	Tags       []string    `db:"tags" json:"tags"`
	ExtraLinks []byte      `db:"extra_links" json:"extra_links"`
	Nsfw       bool        `db:"nsfw" json:"nsfw"`
	VanityRef  pgtype.UUID `db:"vanity_ref" json:"vanity_ref"`
}

func (q *Queries) InsertTeam(ctx context.Context, arg InsertTeamParams) error {
	_, err := q.db.Exec(ctx, insertTeam,
		arg.ID,
		arg.Name,
		arg.Short,
		arg.Tags,
		arg.ExtraLinks,
		arg.Nsfw,
		arg.VanityRef,
	)
	return err
}

const insertTeamForAddBot = `-- name: InsertTeamForAddBot :exec
INSERT INTO teams (id, name, vanity_ref, service) VALUES ($1, $2, $3, 'api/add_bot')
`

type InsertTeamForAddBotParams struct {
	ID        string      `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	VanityRef pgtype.UUID `db:"vanity_ref" json:"vanity_ref"`
}

func (q *Queries) InsertTeamForAddBot(ctx context.Context, arg InsertTeamForAddBotParams) error {
	_, err := q.db.Exec(ctx, insertTeamForAddBot, arg.ID, arg.Name, arg.VanityRef)
	return err
}

const insertTeamForAddServer = `-- name: InsertTeamForAddServer :exec
INSERT INTO teams (id, name, vanity_ref, service) VALUES ($1, $2, $3, 'api/add_server')
`

type InsertTeamForAddServerParams struct {
	ID        string      `db:"id" json:"id"`
	Name      string      `db:"name" json:"name"`
	VanityRef pgtype.UUID `db:"vanity_ref" json:"vanity_ref"`
}

func (q *Queries) InsertTeamForAddServer(ctx context.Context, arg InsertTeamForAddServerParams) error {
	_, err := q.db.Exec(ctx, insertTeamForAddServer, arg.ID, arg.Name, arg.VanityRef)
	return err
}

const insertTeamMember = `-- name: InsertTeamMember :exec
INSERT INTO team_members (team_id, user_id, flags) VALUES ($1, $2, $3)
`

type InsertTeamMemberParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
	Flags  []string    `db:"flags" json:"flags"`
}

func (q *Queries) InsertTeamMember(ctx context.Context, arg InsertTeamMemberParams) error {
	_, err := q.db.Exec(ctx, insertTeamMember, arg.TeamID, arg.UserID, arg.Flags)
	return err
}

const insertTeamMemberForAddBot = `-- name: InsertTeamMemberForAddBot :exec
INSERT INTO team_members (team_id, user_id, flags, service) VALUES ($1, $2, $3, 'api/add_bot')
`

type InsertTeamMemberForAddBotParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
	Flags  []string    `db:"flags" json:"flags"`
}

func (q *Queries) InsertTeamMemberForAddBot(ctx context.Context, arg InsertTeamMemberForAddBotParams) error {
	_, err := q.db.Exec(ctx, insertTeamMemberForAddBot, arg.TeamID, arg.UserID, arg.Flags)
	return err
}

const insertTeamMemberForAddServer = `-- name: InsertTeamMemberForAddServer :exec
INSERT INTO team_members (team_id, user_id, flags, service) VALUES ($1, $2, $3, 'api/add_server')
`

type InsertTeamMemberForAddServerParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
	Flags  []string    `db:"flags" json:"flags"`
}

func (q *Queries) InsertTeamMemberForAddServer(ctx context.Context, arg InsertTeamMemberForAddServerParams) error {
	_, err := q.db.Exec(ctx, insertTeamMemberForAddServer, arg.TeamID, arg.UserID, arg.Flags)
	return err
}

const insertTeamMemberOwner = `-- name: InsertTeamMemberOwner :exec
INSERT INTO team_members (team_id, user_id, flags, data_holder) VALUES ($1, $2, $3, true)
`

type InsertTeamMemberOwnerParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
	Flags  []string    `db:"flags" json:"flags"`
}

func (q *Queries) InsertTeamMemberOwner(ctx context.Context, arg InsertTeamMemberOwnerParams) error {
	_, err := q.db.Exec(ctx, insertTeamMemberOwner, arg.TeamID, arg.UserID, arg.Flags)
	return err
}

const insertVanityReturningItag = `-- name: InsertVanityReturningItag :one
INSERT INTO vanity (code, target_id, target_type) VALUES ($1, $2, $3) RETURNING itag
`

type InsertVanityReturningItagParams struct {
	Code       string `db:"code" json:"code"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) InsertVanityReturningItag(ctx context.Context, arg InsertVanityReturningItagParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertVanityReturningItag, arg.Code, arg.TargetID, arg.TargetType)
	var itag pgtype.UUID
	err := row.Scan(&itag)
	return itag, err
}

const promoteTeamMemberToOwner = `-- name: PromoteTeamMemberToOwner :exec
UPDATE team_members SET flags = $1, data_holder = $2 WHERE team_id = $3 AND user_id = $4
`

type PromoteTeamMemberToOwnerParams struct {
	Flags      []string    `db:"flags" json:"flags"`
	DataHolder bool        `db:"data_holder" json:"data_holder"`
	TeamID     pgtype.UUID `db:"team_id" json:"team_id"`
	UserID     string      `db:"user_id" json:"user_id"`
}

func (q *Queries) PromoteTeamMemberToOwner(ctx context.Context, arg PromoteTeamMemberToOwnerParams) error {
	_, err := q.db.Exec(ctx, promoteTeamMemberToOwner,
		arg.Flags,
		arg.DataHolder,
		arg.TeamID,
		arg.UserID,
	)
	return err
}

const searchTeamsPublic = `-- name: SearchTeamsPublic :many
SELECT id, name, COALESCE(short, '') AS short, tags, nsfw, vote_banned, approximate_votes
FROM teams
WHERE ($1::text = '' OR id::text = $1::text OR name ILIKE $2::text)
AND (
    cardinality($3::text[]) = 0
    OR ($4::text = '@>' AND tags @> $3::text[])
    OR ($4::text = '&&' AND tags && $3::text[])
)
AND ($5::int = 0 OR approximate_votes >= $5::int)
AND ($6::int = 0 OR approximate_votes <= $6::int)
ORDER BY approximate_votes DESC, created_at DESC
LIMIT 12
`

type SearchTeamsPublicParams struct {
	Query     string   `db:"query" json:"query"`
	Pattern   string   `db:"pattern" json:"pattern"`
	Tags      []string `db:"tags" json:"tags"`
	TagMode   string   `db:"tag_mode" json:"tag_mode"`
	VotesFrom int32    `db:"votes_from" json:"votes_from"`
	VotesTo   int32    `db:"votes_to" json:"votes_to"`
}

type SearchTeamsPublicRow struct {
	ID               string   `db:"id" json:"id"`
	Name             string   `db:"name" json:"name"`
	Short            string   `db:"short" json:"short"`
	Tags             []string `db:"tags" json:"tags"`
	Nsfw             bool     `db:"nsfw" json:"nsfw"`
	VoteBanned       bool     `db:"vote_banned" json:"vote_banned"`
	ApproximateVotes int32    `db:"approximate_votes" json:"approximate_votes"`
}

func (q *Queries) SearchTeamsPublic(ctx context.Context, arg SearchTeamsPublicParams) ([]SearchTeamsPublicRow, error) {
	rows, err := q.db.Query(ctx, searchTeamsPublic,
		arg.Query,
		arg.Pattern,
		arg.Tags,
		arg.TagMode,
		arg.VotesFrom,
		arg.VotesTo,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTeamsPublicRow
	for rows.Next() {
		var i SearchTeamsPublicRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Nsfw,
			&i.VoteBanned,
			&i.ApproximateVotes,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchTeamsQueue = `-- name: SearchTeamsQueue :many
SELECT id, name, COALESCE(short, '') AS short, tags, nsfw, vote_banned
FROM teams WHERE id::text = $1::text OR name ILIKE $2::text ORDER BY created_at
`

type SearchTeamsQueueParams struct {
	Query   string `db:"query" json:"query"`
	Pattern string `db:"pattern" json:"pattern"`
}

type SearchTeamsQueueRow struct {
	ID         string   `db:"id" json:"id"`
	Name       string   `db:"name" json:"name"`
	Short      string   `db:"short" json:"short"`
	Tags       []string `db:"tags" json:"tags"`
	Nsfw       bool     `db:"nsfw" json:"nsfw"`
	VoteBanned bool     `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SearchTeamsQueue(ctx context.Context, arg SearchTeamsQueueParams) ([]SearchTeamsQueueRow, error) {
	rows, err := q.db.Query(ctx, searchTeamsQueue, arg.Query, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchTeamsQueueRow
	for rows.Next() {
		var i SearchTeamsQueueRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Short,
			&i.Tags,
			&i.Nsfw,
			&i.VoteBanned,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTeamMemberDataHolder = `-- name: SetTeamMemberDataHolder :exec
UPDATE team_members SET data_holder = true WHERE team_id = $1 AND user_id = $2
`

type SetTeamMemberDataHolderParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) SetTeamMemberDataHolder(ctx context.Context, arg SetTeamMemberDataHolderParams) error {
	_, err := q.db.Exec(ctx, setTeamMemberDataHolder, arg.TeamID, arg.UserID)
	return err
}

const setTeamVoteBanned = `-- name: SetTeamVoteBanned :exec
UPDATE teams SET vote_banned = $2 WHERE id = $1
`

type SetTeamVoteBannedParams struct {
	ID         string `db:"id" json:"id"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SetTeamVoteBanned(ctx context.Context, arg SetTeamVoteBannedParams) error {
	_, err := q.db.Exec(ctx, setTeamVoteBanned, arg.ID, arg.VoteBanned)
	return err
}

const teamMemberExists = `-- name: TeamMemberExists :one
SELECT EXISTS(SELECT 1 FROM team_members WHERE team_id = $1 AND user_id = $2)
`

type TeamMemberExistsParams struct {
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) TeamMemberExists(ctx context.Context, arg TeamMemberExistsParams) (bool, error) {
	row := q.db.QueryRow(ctx, teamMemberExists, arg.TeamID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const touchTeamUpdatedAt = `-- name: TouchTeamUpdatedAt :exec
UPDATE teams SET updated_at = NOW() WHERE id = $1
`

func (q *Queries) TouchTeamUpdatedAt(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, touchTeamUpdatedAt, id)
	return err
}

const updateTeamExtraLinks = `-- name: UpdateTeamExtraLinks :exec
UPDATE teams SET extra_links = $1 WHERE id = $2
`

type UpdateTeamExtraLinksParams struct {
	ExtraLinks []byte `db:"extra_links" json:"extra_links"`
	ID         string `db:"id" json:"id"`
}

func (q *Queries) UpdateTeamExtraLinks(ctx context.Context, arg UpdateTeamExtraLinksParams) error {
	_, err := q.db.Exec(ctx, updateTeamExtraLinks, arg.ExtraLinks, arg.ID)
	return err
}

const updateTeamMemberDataHolder = `-- name: UpdateTeamMemberDataHolder :exec
UPDATE team_members SET data_holder = $1 WHERE team_id = $2 AND user_id = $3
`

type UpdateTeamMemberDataHolderParams struct {
	DataHolder bool        `db:"data_holder" json:"data_holder"`
	TeamID     pgtype.UUID `db:"team_id" json:"team_id"`
	UserID     string      `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateTeamMemberDataHolder(ctx context.Context, arg UpdateTeamMemberDataHolderParams) error {
	_, err := q.db.Exec(ctx, updateTeamMemberDataHolder, arg.DataHolder, arg.TeamID, arg.UserID)
	return err
}

const updateTeamMemberFlags = `-- name: UpdateTeamMemberFlags :exec
UPDATE team_members SET flags = $1 WHERE team_id = $2 AND user_id = $3
`

type UpdateTeamMemberFlagsParams struct {
	Flags  []string    `db:"flags" json:"flags"`
	TeamID pgtype.UUID `db:"team_id" json:"team_id"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateTeamMemberFlags(ctx context.Context, arg UpdateTeamMemberFlagsParams) error {
	_, err := q.db.Exec(ctx, updateTeamMemberFlags, arg.Flags, arg.TeamID, arg.UserID)
	return err
}

const updateTeamMemberMentionable = `-- name: UpdateTeamMemberMentionable :exec
UPDATE team_members SET mentionable = $1 WHERE team_id = $2 AND user_id = $3
`

type UpdateTeamMemberMentionableParams struct {
	Mentionable bool        `db:"mentionable" json:"mentionable"`
	TeamID      pgtype.UUID `db:"team_id" json:"team_id"`
	UserID      string      `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateTeamMemberMentionable(ctx context.Context, arg UpdateTeamMemberMentionableParams) error {
	_, err := q.db.Exec(ctx, updateTeamMemberMentionable, arg.Mentionable, arg.TeamID, arg.UserID)
	return err
}

const updateTeamName = `-- name: UpdateTeamName :exec
UPDATE teams SET name = $1 WHERE id = $2
`

type UpdateTeamNameParams struct {
	Name string `db:"name" json:"name"`
	ID   string `db:"id" json:"id"`
}

func (q *Queries) UpdateTeamName(ctx context.Context, arg UpdateTeamNameParams) error {
	_, err := q.db.Exec(ctx, updateTeamName, arg.Name, arg.ID)
	return err
}

const updateTeamNsfw = `-- name: UpdateTeamNsfw :exec
UPDATE teams SET nsfw = $1 WHERE id = $2
`

type UpdateTeamNsfwParams struct {
	Nsfw bool   `db:"nsfw" json:"nsfw"`
	ID   string `db:"id" json:"id"`
}

func (q *Queries) UpdateTeamNsfw(ctx context.Context, arg UpdateTeamNsfwParams) error {
	_, err := q.db.Exec(ctx, updateTeamNsfw, arg.Nsfw, arg.ID)
	return err
}

const updateTeamShort = `-- name: UpdateTeamShort :exec
UPDATE teams SET short = $1 WHERE id = $2
`

type UpdateTeamShortParams struct {
	Short pgtype.Text `db:"short" json:"short"`
	ID    string      `db:"id" json:"id"`
}

func (q *Queries) UpdateTeamShort(ctx context.Context, arg UpdateTeamShortParams) error {
	_, err := q.db.Exec(ctx, updateTeamShort, arg.Short, arg.ID)
	return err
}

const updateTeamTags = `-- name: UpdateTeamTags :exec
UPDATE teams SET tags = $1 WHERE id = $2
`

type UpdateTeamTagsParams struct {
	Tags []string `db:"tags" json:"tags"`
	ID   string   `db:"id" json:"id"`
}

func (q *Queries) UpdateTeamTags(ctx context.Context, arg UpdateTeamTagsParams) error {
	_, err := q.db.Exec(ctx, updateTeamTags, arg.Tags, arg.ID)
	return err
}

const userExistsCheck = `-- name: UserExistsCheck :one
SELECT EXISTS(SELECT 1 FROM users WHERE user_id = $1)
`

func (q *Queries) UserExistsCheck(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, userExistsCheck, userID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}
