// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: themes.sql

package db

import (
	"context"
)

const countThemes = `-- name: CountThemes :one
SELECT COUNT(*) FROM themes
WHERE ($1::text = '' OR owner = $1)
`

func (q *Queries) CountThemes(ctx context.Context, owner string) (int64, error) {
	row := q.db.QueryRow(ctx, countThemes, owner)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteTheme = `-- name: DeleteTheme :exec
DELETE FROM themes WHERE id = $1
`

func (q *Queries) DeleteTheme(ctx context.Context, id string) error {
	_, err := q.db.Exec(ctx, deleteTheme, id)
	return err
}

const getAllThemesPaged = `-- name: GetAllThemesPaged :many
SELECT id, owner, name, primary_color, secondary_color, tags, created_at
FROM themes
WHERE ($3::text = '' OR owner = $3)
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetAllThemesPagedParams struct {
	Limit  int32  `db:"limit" json:"limit"`
	Offset int32  `db:"offset" json:"offset"`
	Owner  string `db:"owner" json:"owner"`
}

func (q *Queries) GetAllThemesPaged(ctx context.Context, arg GetAllThemesPagedParams) ([]Theme, error) {
	rows, err := q.db.Query(ctx, getAllThemesPaged, arg.Limit, arg.Offset, arg.Owner)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Theme
	for rows.Next() {
		var i Theme
		if err := rows.Scan(
			&i.ID,
			&i.Owner,
			&i.Name,
			&i.PrimaryColor,
			&i.SecondaryColor,
			&i.Tags,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getThemeByID = `-- name: GetThemeByID :one
SELECT id, owner, name, primary_color, secondary_color, tags, created_at
FROM themes WHERE id = $1
`

func (q *Queries) GetThemeByID(ctx context.Context, id string) (Theme, error) {
	row := q.db.QueryRow(ctx, getThemeByID, id)
	var i Theme
	err := row.Scan(
		&i.ID,
		&i.Owner,
		&i.Name,
		&i.PrimaryColor,
		&i.SecondaryColor,
		&i.Tags,
		&i.CreatedAt,
	)
	return i, err
}

const getThemeOwner = `-- name: GetThemeOwner :one
SELECT owner FROM themes WHERE id = $1
`

func (q *Queries) GetThemeOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getThemeOwner, id)
	var owner string
	err := row.Scan(&owner)
	return owner, err
}

const insertTheme = `-- name: InsertTheme :exec
INSERT INTO themes (id, name, primary_color, secondary_color, tags, owner)
VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertThemeParams struct {
	ID             string   `db:"id" json:"id"`
	Name           string   `db:"name" json:"name"`
	PrimaryColor   string   `db:"primary_color" json:"primary_color"`
	SecondaryColor string   `db:"secondary_color" json:"secondary_color"`
	Tags           []string `db:"tags" json:"tags"`
	Owner          string   `db:"owner" json:"owner"`
}

func (q *Queries) InsertTheme(ctx context.Context, arg InsertThemeParams) error {
	_, err := q.db.Exec(ctx, insertTheme,
		arg.ID,
		arg.Name,
		arg.PrimaryColor,
		arg.SecondaryColor,
		arg.Tags,
		arg.Owner,
	)
	return err
}
