// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: tickets.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const appendTicketMessage = `-- name: AppendTicketMessage :exec
UPDATE tickets SET messages = messages || $1 WHERE id = $2
`

type AppendTicketMessageParams struct {
	Messages []byte `db:"messages" json:"messages"`
	ID       string `db:"id" json:"id"`
}

func (q *Queries) AppendTicketMessage(ctx context.Context, arg AppendTicketMessageParams) error {
	_, err := q.db.Exec(ctx, appendTicketMessage, arg.Messages, arg.ID)
	return err
}

const countTicketsByOpen = `-- name: CountTicketsByOpen :many
SELECT open, COUNT(*) FROM tickets GROUP BY open
`

type CountTicketsByOpenRow struct {
	Open  bool  `db:"open" json:"open"`
	Count int64 `db:"count" json:"count"`
}

func (q *Queries) CountTicketsByOpen(ctx context.Context) ([]CountTicketsByOpenRow, error) {
	rows, err := q.db.Query(ctx, countTicketsByOpen)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CountTicketsByOpenRow
	for rows.Next() {
		var i CountTicketsByOpenRow
		if err := rows.Scan(&i.Open, &i.Count); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getStaffTicketsPage = `-- name: GetStaffTicketsPage :many
SELECT id, channel_id, topic_id, issue, ticket_context, messages, user_id, close_user_id, open, created_at, enc_key
FROM tickets
WHERE $3::boolean IS NULL OR open = $3
ORDER BY created_at DESC
LIMIT $1 OFFSET $2
`

type GetStaffTicketsPageParams struct {
	Limit  int32       `db:"limit" json:"limit"`
	Offset int32       `db:"offset" json:"offset"`
	Open   pgtype.Bool `db:"open" json:"open"`
}

type GetStaffTicketsPageRow struct {
	ID            string             `db:"id" json:"id"`
	ChannelID     string             `db:"channel_id" json:"channel_id"`
	TopicID       string             `db:"topic_id" json:"topic_id"`
	Issue         string             `db:"issue" json:"issue"`
	TicketContext []byte             `db:"ticket_context" json:"ticket_context"`
	Messages      []byte             `db:"messages" json:"messages"`
	UserID        string             `db:"user_id" json:"user_id"`
	CloseUserID   pgtype.Text        `db:"close_user_id" json:"close_user_id"`
	Open          bool               `db:"open" json:"open"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EncKey        pgtype.Text        `db:"enc_key" json:"enc_key"`
}

func (q *Queries) GetStaffTicketsPage(ctx context.Context, arg GetStaffTicketsPageParams) ([]GetStaffTicketsPageRow, error) {
	rows, err := q.db.Query(ctx, getStaffTicketsPage, arg.Limit, arg.Offset, arg.Open)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetStaffTicketsPageRow
	for rows.Next() {
		var i GetStaffTicketsPageRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.TopicID,
			&i.Issue,
			&i.TicketContext,
			&i.Messages,
			&i.UserID,
			&i.CloseUserID,
			&i.Open,
			&i.CreatedAt,
			&i.EncKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getTicket = `-- name: GetTicket :one
SELECT id, channel_id, topic_id, issue, ticket_context, messages, user_id, close_user_id, open, created_at, enc_key
FROM tickets
WHERE id = $1
`

type GetTicketRow struct {
	ID            string             `db:"id" json:"id"`
	ChannelID     string             `db:"channel_id" json:"channel_id"`
	TopicID       string             `db:"topic_id" json:"topic_id"`
	Issue         string             `db:"issue" json:"issue"`
	TicketContext []byte             `db:"ticket_context" json:"ticket_context"`
	Messages      []byte             `db:"messages" json:"messages"`
	UserID        string             `db:"user_id" json:"user_id"`
	CloseUserID   pgtype.Text        `db:"close_user_id" json:"close_user_id"`
	Open          bool               `db:"open" json:"open"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EncKey        pgtype.Text        `db:"enc_key" json:"enc_key"`
}

func (q *Queries) GetTicket(ctx context.Context, id string) (GetTicketRow, error) {
	row := q.db.QueryRow(ctx, getTicket, id)
	var i GetTicketRow
	err := row.Scan(
		&i.ID,
		&i.ChannelID,
		&i.TopicID,
		&i.Issue,
		&i.TicketContext,
		&i.Messages,
		&i.UserID,
		&i.CloseUserID,
		&i.Open,
		&i.CreatedAt,
		&i.EncKey,
	)
	return i, err
}

const getTicketOwner = `-- name: GetTicketOwner :one
SELECT user_id FROM tickets WHERE id = $1
`

func (q *Queries) GetTicketOwner(ctx context.Context, id string) (string, error) {
	row := q.db.QueryRow(ctx, getTicketOwner, id)
	var user_id string
	err := row.Scan(&user_id)
	return user_id, err
}

const getTicketOwnerAndOpen = `-- name: GetTicketOwnerAndOpen :one
SELECT user_id, open FROM tickets WHERE id = $1
`

type GetTicketOwnerAndOpenRow struct {
	UserID string `db:"user_id" json:"user_id"`
	Open   bool   `db:"open" json:"open"`
}

func (q *Queries) GetTicketOwnerAndOpen(ctx context.Context, id string) (GetTicketOwnerAndOpenRow, error) {
	row := q.db.QueryRow(ctx, getTicketOwnerAndOpen, id)
	var i GetTicketOwnerAndOpenRow
	err := row.Scan(&i.UserID, &i.Open)
	return i, err
}

const getUserTickets = `-- name: GetUserTickets :many
SELECT id, channel_id, topic_id, issue, ticket_context, messages, user_id, close_user_id, open, created_at, enc_key
FROM tickets
WHERE user_id = $1
ORDER BY created_at DESC
`

type GetUserTicketsRow struct {
	ID            string             `db:"id" json:"id"`
	ChannelID     string             `db:"channel_id" json:"channel_id"`
	TopicID       string             `db:"topic_id" json:"topic_id"`
	Issue         string             `db:"issue" json:"issue"`
	TicketContext []byte             `db:"ticket_context" json:"ticket_context"`
	Messages      []byte             `db:"messages" json:"messages"`
	UserID        string             `db:"user_id" json:"user_id"`
	CloseUserID   pgtype.Text        `db:"close_user_id" json:"close_user_id"`
	Open          bool               `db:"open" json:"open"`
	CreatedAt     pgtype.Timestamptz `db:"created_at" json:"created_at"`
	EncKey        pgtype.Text        `db:"enc_key" json:"enc_key"`
}

func (q *Queries) GetUserTickets(ctx context.Context, userID string) ([]GetUserTicketsRow, error) {
	rows, err := q.db.Query(ctx, getUserTickets, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserTicketsRow
	for rows.Next() {
		var i GetUserTicketsRow
		if err := rows.Scan(
			&i.ID,
			&i.ChannelID,
			&i.TopicID,
			&i.Issue,
			&i.TicketContext,
			&i.Messages,
			&i.UserID,
			&i.CloseUserID,
			&i.Open,
			&i.CreatedAt,
			&i.EncKey,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertTicket = `-- name: InsertTicket :exec
INSERT INTO tickets (id, channel_id, topic_id, issue, messages, user_id) VALUES ($1, $2, $3, $4, $5, $6)
`

type InsertTicketParams struct {
	ID        string `db:"id" json:"id"`
	ChannelID string `db:"channel_id" json:"channel_id"`
	TopicID   string `db:"topic_id" json:"topic_id"`
	Issue     string `db:"issue" json:"issue"`
	Messages  []byte `db:"messages" json:"messages"`
	UserID    string `db:"user_id" json:"user_id"`
}

func (q *Queries) InsertTicket(ctx context.Context, arg InsertTicketParams) error {
	_, err := q.db.Exec(ctx, insertTicket,
		arg.ID,
		arg.ChannelID,
		arg.TopicID,
		arg.Issue,
		arg.Messages,
		arg.UserID,
	)
	return err
}

const updateTicketOpenState = `-- name: UpdateTicketOpenState :exec
UPDATE tickets SET open = $1, close_user_id = $2 WHERE id = $3
`

type UpdateTicketOpenStateParams struct {
	Open        bool        `db:"open" json:"open"`
	CloseUserID pgtype.Text `db:"close_user_id" json:"close_user_id"`
	ID          string      `db:"id" json:"id"`
}

func (q *Queries) UpdateTicketOpenState(ctx context.Context, arg UpdateTicketOpenStateParams) error {
	_, err := q.db.Exec(ctx, updateTicketOpenState, arg.Open, arg.CloseUserID, arg.ID)
	return err
}
