// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: users.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const clearAllBugHunters = `-- name: ClearAllBugHunters :exec
UPDATE users SET bug_hunters = false
`

func (q *Queries) ClearAllBugHunters(ctx context.Context) error {
	_, err := q.db.Exec(ctx, clearAllBugHunters)
	return err
}

const countUsers = `-- name: CountUsers :one
SELECT COUNT(*) FROM users
`

func (q *Queries) CountUsers(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUsers)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserByID = `-- name: DeleteUserByID :exec
DELETE FROM users WHERE user_id = $1
`

func (q *Queries) DeleteUserByID(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, deleteUserByID, userID)
	return err
}

const getBannedUserIDs = `-- name: GetBannedUserIDs :many
SELECT user_id FROM users WHERE banned = true
`

func (q *Queries) GetBannedUserIDs(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, getBannedUserIDs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var user_id string
		if err := rows.Scan(&user_id); err != nil {
			return nil, err
		}
		items = append(items, user_id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserAboutAndID = `-- name: GetUserAboutAndID :one
SELECT about, user_id FROM users WHERE user_id = $1
`

type GetUserAboutAndIDRow struct {
	About  pgtype.Text `db:"about" json:"about"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) GetUserAboutAndID(ctx context.Context, userID string) (GetUserAboutAndIDRow, error) {
	row := q.db.QueryRow(ctx, getUserAboutAndID, userID)
	var i GetUserAboutAndIDRow
	err := row.Scan(&i.About, &i.UserID)
	return i, err
}

const getUserAboutAndTimestamps = `-- name: GetUserAboutAndTimestamps :one
SELECT about, created_at, updated_at FROM users WHERE user_id = $1
`

type GetUserAboutAndTimestampsRow struct {
	About     pgtype.Text        `db:"about" json:"about"`
	CreatedAt pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
}

func (q *Queries) GetUserAboutAndTimestamps(ctx context.Context, userID string) (GetUserAboutAndTimestampsRow, error) {
	row := q.db.QueryRow(ctx, getUserAboutAndTimestamps, userID)
	var i GetUserAboutAndTimestampsRow
	err := row.Scan(&i.About, &i.CreatedAt, &i.UpdatedAt)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT itag, user_id, experiments, certified, developer, bug_hunters, captcha_sponsor_enabled, extra_links, about, vote_banned, banned, created_at, updated_at, last_booster_claim
FROM users
WHERE user_id = $1
`

type GetUserByIDRow struct {
	Itag                  pgtype.UUID        `db:"itag" json:"itag"`
	UserID                string             `db:"user_id" json:"user_id"`
	Experiments           []string           `db:"experiments" json:"experiments"`
	Certified             bool               `db:"certified" json:"certified"`
	Developer             bool               `db:"developer" json:"developer"`
	BugHunters            bool               `db:"bug_hunters" json:"bug_hunters"`
	CaptchaSponsorEnabled bool               `db:"captcha_sponsor_enabled" json:"captcha_sponsor_enabled"`
	ExtraLinks            []byte             `db:"extra_links" json:"extra_links"`
	About                 pgtype.Text        `db:"about" json:"about"`
	VoteBanned            bool               `db:"vote_banned" json:"vote_banned"`
	Banned                bool               `db:"banned" json:"banned"`
	CreatedAt             pgtype.Timestamptz `db:"created_at" json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `db:"updated_at" json:"updated_at"`
	LastBoosterClaim      pgtype.Timestamptz `db:"last_booster_claim" json:"last_booster_claim"`
}

func (q *Queries) GetUserByID(ctx context.Context, userID string) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, userID)
	var i GetUserByIDRow
	err := row.Scan(
		&i.Itag,
		&i.UserID,
		&i.Experiments,
		&i.Certified,
		&i.Developer,
		&i.BugHunters,
		&i.CaptchaSponsorEnabled,
		&i.ExtraLinks,
		&i.About,
		&i.VoteBanned,
		&i.Banned,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.LastBoosterClaim,
	)
	return i, err
}

const getUserLastBoosterClaim = `-- name: GetUserLastBoosterClaim :one
SELECT last_booster_claim FROM users WHERE user_id = $1
`

func (q *Queries) GetUserLastBoosterClaim(ctx context.Context, userID string) (pgtype.Timestamptz, error) {
	row := q.db.QueryRow(ctx, getUserLastBoosterClaim, userID)
	var last_booster_claim pgtype.Timestamptz
	err := row.Scan(&last_booster_claim)
	return last_booster_claim, err
}

const getUserPerm = `-- name: GetUserPerm :one
SELECT experiments, banned, captcha_sponsor_enabled, vote_banned FROM users WHERE user_id = $1
`

type GetUserPermRow struct {
	Experiments           []string `db:"experiments" json:"experiments"`
	Banned                bool     `db:"banned" json:"banned"`
	CaptchaSponsorEnabled bool     `db:"captcha_sponsor_enabled" json:"captcha_sponsor_enabled"`
	VoteBanned            bool     `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetUserPerm(ctx context.Context, userID string) (GetUserPermRow, error) {
	row := q.db.QueryRow(ctx, getUserPerm, userID)
	var i GetUserPermRow
	err := row.Scan(
		&i.Experiments,
		&i.Banned,
		&i.CaptchaSponsorEnabled,
		&i.VoteBanned,
	)
	return i, err
}

const insertBannedUser = `-- name: InsertBannedUser :exec
INSERT INTO users (user_id, banned, api_token) VALUES ($1, $2, $3)
`

type InsertBannedUserParams struct {
	UserID   string `db:"user_id" json:"user_id"`
	Banned   bool   `db:"banned" json:"banned"`
	ApiToken string `db:"api_token" json:"api_token"`
}

func (q *Queries) InsertBannedUser(ctx context.Context, arg InsertBannedUserParams) error {
	_, err := q.db.Exec(ctx, insertBannedUser, arg.UserID, arg.Banned, arg.ApiToken)
	return err
}

const searchUsersQueue = `-- name: SearchUsersQueue :many
SELECT users.user_id, users.banned, users.vote_banned
FROM users
INNER JOIN internal_user_cache__discord discord_users ON users.user_id = discord_users.id
WHERE users.user_id = $1::text OR discord_users.username ILIKE $2::text
ORDER BY users.created_at
`

type SearchUsersQueueParams struct {
	Query   string `db:"query" json:"query"`
	Pattern string `db:"pattern" json:"pattern"`
}

type SearchUsersQueueRow struct {
	UserID     string `db:"user_id" json:"user_id"`
	Banned     bool   `db:"banned" json:"banned"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) SearchUsersQueue(ctx context.Context, arg SearchUsersQueueParams) ([]SearchUsersQueueRow, error) {
	rows, err := q.db.Query(ctx, searchUsersQueue, arg.Query, arg.Pattern)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchUsersQueueRow
	for rows.Next() {
		var i SearchUsersQueueRow
		if err := rows.Scan(&i.UserID, &i.Banned, &i.VoteBanned); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setUserBugHunter = `-- name: SetUserBugHunter :exec
UPDATE users SET bug_hunters = true WHERE user_id = $1
`

func (q *Queries) SetUserBugHunter(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, setUserBugHunter, userID)
	return err
}

const updateUserAbout = `-- name: UpdateUserAbout :exec
UPDATE users SET about = $1 WHERE user_id = $2
`

type UpdateUserAboutParams struct {
	About  pgtype.Text `db:"about" json:"about"`
	UserID string      `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserAbout(ctx context.Context, arg UpdateUserAboutParams) error {
	_, err := q.db.Exec(ctx, updateUserAbout, arg.About, arg.UserID)
	return err
}

const updateUserAppBanned = `-- name: UpdateUserAppBanned :exec
UPDATE users SET app_banned = $2 WHERE user_id = $1
`

type UpdateUserAppBannedParams struct {
	UserID    string `db:"user_id" json:"user_id"`
	AppBanned bool   `db:"app_banned" json:"app_banned"`
}

func (q *Queries) UpdateUserAppBanned(ctx context.Context, arg UpdateUserAppBannedParams) error {
	_, err := q.db.Exec(ctx, updateUserAppBanned, arg.UserID, arg.AppBanned)
	return err
}

const updateUserBanned = `-- name: UpdateUserBanned :execrows
UPDATE users SET banned = $2 WHERE user_id = $1
`

type UpdateUserBannedParams struct {
	UserID string `db:"user_id" json:"user_id"`
	Banned bool   `db:"banned" json:"banned"`
}

func (q *Queries) UpdateUserBanned(ctx context.Context, arg UpdateUserBannedParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateUserBanned, arg.UserID, arg.Banned)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateUserCaptchaSponsorEnabled = `-- name: UpdateUserCaptchaSponsorEnabled :exec
UPDATE users SET captcha_sponsor_enabled = $1 WHERE user_id = $2
`

type UpdateUserCaptchaSponsorEnabledParams struct {
	CaptchaSponsorEnabled bool   `db:"captcha_sponsor_enabled" json:"captcha_sponsor_enabled"`
	UserID                string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserCaptchaSponsorEnabled(ctx context.Context, arg UpdateUserCaptchaSponsorEnabledParams) error {
	_, err := q.db.Exec(ctx, updateUserCaptchaSponsorEnabled, arg.CaptchaSponsorEnabled, arg.UserID)
	return err
}

const updateUserExtraLinks = `-- name: UpdateUserExtraLinks :exec
UPDATE users SET extra_links = $1 WHERE user_id = $2
`

type UpdateUserExtraLinksParams struct {
	ExtraLinks []byte `db:"extra_links" json:"extra_links"`
	UserID     string `db:"user_id" json:"user_id"`
}

func (q *Queries) UpdateUserExtraLinks(ctx context.Context, arg UpdateUserExtraLinksParams) error {
	_, err := q.db.Exec(ctx, updateUserExtraLinks, arg.ExtraLinks, arg.UserID)
	return err
}

const updateUserLastBoosterClaim = `-- name: UpdateUserLastBoosterClaim :exec
UPDATE users SET last_booster_claim = NOW() WHERE user_id = $1
`

func (q *Queries) UpdateUserLastBoosterClaim(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, updateUserLastBoosterClaim, userID)
	return err
}

const updateUsersUpdatedAt = `-- name: UpdateUsersUpdatedAt :exec
UPDATE users SET updated_at = NOW() WHERE user_id = $1
`

func (q *Queries) UpdateUsersUpdatedAt(ctx context.Context, userID string) error {
	_, err := q.db.Exec(ctx, updateUsersUpdatedAt, userID)
	return err
}
