// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: usercache.sql

package db

import (
	"context"
)

const getDiscordUsersDueForRefresh = `-- name: GetDiscordUsersDueForRefresh :many
SELECT iuc.id FROM internal_user_cache__discord iuc
WHERE iuc.last_updated < NOW() - make_interval(secs => $1::double precision)
ORDER BY
    CASE
        WHEN EXISTS (SELECT 1 FROM bots b WHERE b.bot_id = iuc.id) THEN 0
        WHEN EXISTS (SELECT 1 FROM bots b WHERE b.owner = iuc.id)
          OR EXISTS (SELECT 1 FROM team_members tm WHERE tm.user_id = iuc.id) THEN 1
        ELSE 2
    END,
    iuc.last_updated ASC
LIMIT $2
`

type GetDiscordUsersDueForRefreshParams struct {
	MinAgeSeconds float64 `db:"min_age_seconds" json:"min_age_seconds"`
	BatchSize     int32   `db:"batch_size" json:"batch_size"`
}

func (q *Queries) GetDiscordUsersDueForRefresh(ctx context.Context, arg GetDiscordUsersDueForRefreshParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getDiscordUsersDueForRefresh, arg.MinAgeSeconds, arg.BatchSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var id string
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
