// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: validators.sql

package db

import (
	"context"
)

const getWordBlacklistSystems = `-- name: GetWordBlacklistSystems :one
SELECT systems FROM blacklisted_words WHERE word = $1
`

func (q *Queries) GetWordBlacklistSystems(ctx context.Context, word string) ([]string, error) {
	row := q.db.QueryRow(ctx, getWordBlacklistSystems, word)
	var systems []string
	err := row.Scan(&systems)
	return systems, err
}
