// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: vanity.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countVanityByCode = `-- name: CountVanityByCode :one
SELECT COUNT(*) FROM vanity WHERE code = $1
`

func (q *Queries) CountVanityByCode(ctx context.Context, code string) (int64, error) {
	row := q.db.QueryRow(ctx, countVanityByCode, code)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countVanityByTarget = `-- name: CountVanityByTarget :one
SELECT COUNT(*) FROM vanity WHERE target_id = $1 AND target_type = $2
`

type CountVanityByTargetParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) CountVanityByTarget(ctx context.Context, arg CountVanityByTargetParams) (int64, error) {
	row := q.db.QueryRow(ctx, countVanityByTarget, arg.TargetID, arg.TargetType)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getBotIDByClientID = `-- name: GetBotIDByClientID :one
SELECT bot_id FROM bots WHERE client_id = $1
`

func (q *Queries) GetBotIDByClientID(ctx context.Context, clientID string) (string, error) {
	row := q.db.QueryRow(ctx, getBotIDByClientID, clientID)
	var bot_id string
	err := row.Scan(&bot_id)
	return bot_id, err
}

const getServerIDByServerID = `-- name: GetServerIDByServerID :one
SELECT server_id FROM servers WHERE server_id = $1
`

func (q *Queries) GetServerIDByServerID(ctx context.Context, serverID string) (string, error) {
	row := q.db.QueryRow(ctx, getServerIDByServerID, serverID)
	var server_id string
	err := row.Scan(&server_id)
	return server_id, err
}

const insertVanity = `-- name: InsertVanity :exec
INSERT INTO vanity (target_id, target_type, code) VALUES ($1, $2, $3)
`

type InsertVanityParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Code       string `db:"code" json:"code"`
}

func (q *Queries) InsertVanity(ctx context.Context, arg InsertVanityParams) error {
	_, err := q.db.Exec(ctx, insertVanity, arg.TargetID, arg.TargetType, arg.Code)
	return err
}

const resolveVanityByCode = `-- name: ResolveVanityByCode :one
SELECT itag, target_id, target_type, code, created_at FROM vanity WHERE code = $1
`

func (q *Queries) ResolveVanityByCode(ctx context.Context, code string) (Vanity, error) {
	row := q.db.QueryRow(ctx, resolveVanityByCode, code)
	var i Vanity
	err := row.Scan(
		&i.Itag,
		&i.TargetID,
		&i.TargetType,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const resolveVanityByItag = `-- name: ResolveVanityByItag :one
SELECT itag, target_id, target_type, code, created_at FROM vanity WHERE itag = $1
`

func (q *Queries) ResolveVanityByItag(ctx context.Context, itag pgtype.UUID) (Vanity, error) {
	row := q.db.QueryRow(ctx, resolveVanityByItag, itag)
	var i Vanity
	err := row.Scan(
		&i.Itag,
		&i.TargetID,
		&i.TargetType,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const resolveVanityByTargetID = `-- name: ResolveVanityByTargetID :one

SELECT itag, target_id, target_type, code, created_at FROM vanity WHERE target_id = $1
`

// resolveImpl (popplio/routes/vanity/assets/resolve.go) picks one of three
// hardcoded, never-user-controlled vanity columns to filter on
// (target_id/code/itag) -- one explicit query per column, same reasoning as
// db/queries/payments.sql and db/queries/reports.sql.
func (q *Queries) ResolveVanityByTargetID(ctx context.Context, targetID string) (Vanity, error) {
	row := q.db.QueryRow(ctx, resolveVanityByTargetID, targetID)
	var i Vanity
	err := row.Scan(
		&i.Itag,
		&i.TargetID,
		&i.TargetType,
		&i.Code,
		&i.CreatedAt,
	)
	return i, err
}

const updateVanityCode = `-- name: UpdateVanityCode :exec
UPDATE vanity SET code = $1 WHERE target_id = $2 AND target_type = $3
`

type UpdateVanityCodeParams struct {
	Code       string `db:"code" json:"code"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) UpdateVanityCode(ctx context.Context, arg UpdateVanityCodeParams) error {
	_, err := q.db.Exec(ctx, updateVanityCode, arg.Code, arg.TargetID, arg.TargetType)
	return err
}
