// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.29.0
// source: votes.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEntityVotes = `-- name: CountEntityVotes :one
SELECT COUNT(*) FILTER (WHERE upvote) AS upvotes, COUNT(*) FILTER (WHERE NOT upvote) AS downvotes
FROM entity_votes
WHERE target_id = $1 AND target_type = $2 AND void = false
`

type CountEntityVotesParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

type CountEntityVotesRow struct {
	Upvotes   int64 `db:"upvotes" json:"upvotes"`
	Downvotes int64 `db:"downvotes" json:"downvotes"`
}

func (q *Queries) CountEntityVotes(ctx context.Context, arg CountEntityVotesParams) (CountEntityVotesRow, error) {
	row := q.db.QueryRow(ctx, countEntityVotes, arg.TargetID, arg.TargetType)
	var i CountEntityVotesRow
	err := row.Scan(&i.Upvotes, &i.Downvotes)
	return i, err
}

const countRedeemableEntityVotes = `-- name: CountRedeemableEntityVotes :one
SELECT COUNT(*) FILTER (WHERE upvote) AS upvotes, COUNT(*) FILTER (WHERE NOT upvote) AS downvotes
FROM entity_votes
WHERE target_id = $1 AND target_type = $2 AND void = false AND credit_redeem IS NULL
`

type CountRedeemableEntityVotesParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

type CountRedeemableEntityVotesRow struct {
	Upvotes   int64 `db:"upvotes" json:"upvotes"`
	Downvotes int64 `db:"downvotes" json:"downvotes"`
}

// Same as CountEntityVotes, but additionally excludes votes that have
// already been cashed in for credits (credit_redeem IS NOT NULL). Used only
// by the vote-credit redemption flow -- an already-redeemed vote must not
// count a second time toward a new redemption's total, even though it still
// counts toward the entity's public vote total (CountEntityVotes).
func (q *Queries) CountRedeemableEntityVotes(ctx context.Context, arg CountRedeemableEntityVotesParams) (CountRedeemableEntityVotesRow, error) {
	row := q.db.QueryRow(ctx, countRedeemableEntityVotes, arg.TargetID, arg.TargetType)
	var i CountRedeemableEntityVotesRow
	err := row.Scan(&i.Upvotes, &i.Downvotes)
	return i, err
}

const countUserEntityVotes = `-- name: CountUserEntityVotes :one
SELECT COUNT(*) FROM entity_votes WHERE target_id = $1 AND target_type = $2 AND author = $3
`

type CountUserEntityVotesParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Author     string `db:"author" json:"author"`
}

func (q *Queries) CountUserEntityVotes(ctx context.Context, arg CountUserEntityVotesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countUserEntityVotes, arg.TargetID, arg.TargetType, arg.Author)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteUserEntityVotes = `-- name: DeleteUserEntityVotes :exec
DELETE FROM entity_votes WHERE author = $1 AND target_id = $2 AND target_type = $3
`

type DeleteUserEntityVotesParams struct {
	Author     string `db:"author" json:"author"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) DeleteUserEntityVotes(ctx context.Context, arg DeleteUserEntityVotesParams) error {
	_, err := q.db.Exec(ctx, deleteUserEntityVotes, arg.Author, arg.TargetID, arg.TargetType)
	return err
}

const getBotVoteInfo = `-- name: GetBotVoteInfo :one
SELECT premium, vote_blitz_until FROM bots WHERE bot_id = $1
`

type GetBotVoteInfoRow struct {
	Premium        bool               `db:"premium" json:"premium"`
	VoteBlitzUntil pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetBotVoteInfo(ctx context.Context, botID string) (GetBotVoteInfoRow, error) {
	row := q.db.QueryRow(ctx, getBotVoteInfo, botID)
	var i GetBotVoteInfoRow
	err := row.Scan(&i.Premium, &i.VoteBlitzUntil)
	return i, err
}

const getBotVoteStatus = `-- name: GetBotVoteStatus :one

SELECT type, vote_banned FROM bots WHERE bot_id = $1
`

type GetBotVoteStatusRow struct {
	Type       string `db:"type" json:"type"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

// Entity-target dispatch queries (popplio/votes.GetEntityInfo, EntityVoteInfo,
// EntityPostVote, RecomputeApproximateVotes each pick one of a fixed,
// never-user-controlled set of tables based on target_type) -- one explicit
// query per table, same reasoning as db/queries/payments.sql.
func (q *Queries) GetBotVoteStatus(ctx context.Context, botID string) (GetBotVoteStatusRow, error) {
	row := q.db.QueryRow(ctx, getBotVoteStatus, botID)
	var i GetBotVoteStatusRow
	err := row.Scan(&i.Type, &i.VoteBanned)
	return i, err
}

const getEntityVotes = `-- name: GetEntityVotes :many
SELECT itag, target_id, target_type, author, upvote, void, void_reason, voided_at, created_at, vote_num, credit_redeem, immutable
FROM entity_votes
WHERE author = $1 AND target_id = $2 AND target_type = $3 AND void = false
ORDER BY created_at DESC
`

type GetEntityVotesParams struct {
	Author     string `db:"author" json:"author"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

type GetEntityVotesRow struct {
	Itag         pgtype.UUID        `db:"itag" json:"itag"`
	TargetID     string             `db:"target_id" json:"target_id"`
	TargetType   string             `db:"target_type" json:"target_type"`
	Author       string             `db:"author" json:"author"`
	Upvote       bool               `db:"upvote" json:"upvote"`
	Void         bool               `db:"void" json:"void"`
	VoidReason   pgtype.Text        `db:"void_reason" json:"void_reason"`
	VoidedAt     pgtype.Timestamptz `db:"voided_at" json:"voided_at"`
	CreatedAt    pgtype.Timestamp   `db:"created_at" json:"created_at"`
	VoteNum      int32              `db:"vote_num" json:"vote_num"`
	CreditRedeem pgtype.UUID        `db:"credit_redeem" json:"credit_redeem"`
	Immutable    bool               `db:"immutable" json:"immutable"`
}

func (q *Queries) GetEntityVotes(ctx context.Context, arg GetEntityVotesParams) ([]GetEntityVotesRow, error) {
	rows, err := q.db.Query(ctx, getEntityVotes, arg.Author, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetEntityVotesRow
	for rows.Next() {
		var i GetEntityVotesRow
		if err := rows.Scan(
			&i.Itag,
			&i.TargetID,
			&i.TargetType,
			&i.Author,
			&i.Upvote,
			&i.Void,
			&i.VoidReason,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.VoteNum,
			&i.CreditRedeem,
			&i.Immutable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPackVoteBanned = `-- name: GetPackVoteBanned :one
SELECT vote_banned FROM packs WHERE url = $1
`

func (q *Queries) GetPackVoteBanned(ctx context.Context, url string) (bool, error) {
	row := q.db.QueryRow(ctx, getPackVoteBanned, url)
	var vote_banned bool
	err := row.Scan(&vote_banned)
	return vote_banned, err
}

const getRecentAutomatedVoteResetForUpdate = `-- name: GetRecentAutomatedVoteResetForUpdate :one
SELECT id FROM automated_vote_resets WHERE created_at > NOW() - INTERVAL '1 month' FOR UPDATE
`

func (q *Queries) GetRecentAutomatedVoteResetForUpdate(ctx context.Context) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, getRecentAutomatedVoteResetForUpdate)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const getRedeemableVoteItags = `-- name: GetRedeemableVoteItags :many
SELECT itag FROM entity_votes WHERE target_id = $1 AND target_type = $2 AND void = false AND credit_redeem IS NULL ORDER BY created_at ASC LIMIT $3
`

type GetRedeemableVoteItagsParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Limit      int32  `db:"limit" json:"limit"`
}

// credit_redeem IS NULL excludes votes some earlier redemption already
// claimed -- without it, a vote stays eligible forever and a repeat
// redemption call would claim (and pay out credits for) the same vote more
// than once.
func (q *Queries) GetRedeemableVoteItags(ctx context.Context, arg GetRedeemableVoteItagsParams) ([]pgtype.UUID, error) {
	rows, err := q.db.Query(ctx, getRedeemableVoteItags, arg.TargetID, arg.TargetType, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []pgtype.UUID
	for rows.Next() {
		var itag pgtype.UUID
		if err := rows.Scan(&itag); err != nil {
			return nil, err
		}
		items = append(items, itag)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerVoteInfo = `-- name: GetServerVoteInfo :one
SELECT premium, vote_blitz_until FROM servers WHERE server_id = $1
`

type GetServerVoteInfoRow struct {
	Premium        bool               `db:"premium" json:"premium"`
	VoteBlitzUntil pgtype.Timestamptz `db:"vote_blitz_until" json:"vote_blitz_until"`
}

func (q *Queries) GetServerVoteInfo(ctx context.Context, serverID string) (GetServerVoteInfoRow, error) {
	row := q.db.QueryRow(ctx, getServerVoteInfo, serverID)
	var i GetServerVoteInfoRow
	err := row.Scan(&i.Premium, &i.VoteBlitzUntil)
	return i, err
}

const getServerVoteLeaderboard = `-- name: GetServerVoteLeaderboard :many
SELECT author,
(SUM(CASE WHEN upvote THEN 1 ELSE 0 END) - SUM(CASE WHEN NOT upvote THEN 1 ELSE 0 END))::bigint AS score
FROM entity_votes
WHERE target_id = $1
AND target_type = 'server'
AND void = false
GROUP BY author
ORDER BY score DESC
`

type GetServerVoteLeaderboardRow struct {
	Author string `db:"author" json:"author"`
	Score  int64  `db:"score" json:"score"`
}

func (q *Queries) GetServerVoteLeaderboard(ctx context.Context, targetID string) ([]GetServerVoteLeaderboardRow, error) {
	rows, err := q.db.Query(ctx, getServerVoteLeaderboard, targetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetServerVoteLeaderboardRow
	for rows.Next() {
		var i GetServerVoteLeaderboardRow
		if err := rows.Scan(&i.Author, &i.Score); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getServerVoteStatus = `-- name: GetServerVoteStatus :one
SELECT name, vote_banned FROM servers WHERE server_id = $1
`

type GetServerVoteStatusRow struct {
	Name       string `db:"name" json:"name"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetServerVoteStatus(ctx context.Context, serverID string) (GetServerVoteStatusRow, error) {
	row := q.db.QueryRow(ctx, getServerVoteStatus, serverID)
	var i GetServerVoteStatusRow
	err := row.Scan(&i.Name, &i.VoteBanned)
	return i, err
}

const getTeamVoteStatus = `-- name: GetTeamVoteStatus :one
SELECT name, vote_banned FROM teams WHERE id = $1
`

type GetTeamVoteStatusRow struct {
	Name       string `db:"name" json:"name"`
	VoteBanned bool   `db:"vote_banned" json:"vote_banned"`
}

func (q *Queries) GetTeamVoteStatus(ctx context.Context, id string) (GetTeamVoteStatusRow, error) {
	row := q.db.QueryRow(ctx, getTeamVoteStatus, id)
	var i GetTeamVoteStatusRow
	err := row.Scan(&i.Name, &i.VoteBanned)
	return i, err
}

const getTopVoters = `-- name: GetTopVoters :many
SELECT author, COUNT(*) AS vote_count
FROM entity_votes
WHERE upvote = true
GROUP BY author
ORDER BY vote_count DESC
LIMIT $1
`

type GetTopVotersRow struct {
	Author    string `db:"author" json:"author"`
	VoteCount int64  `db:"vote_count" json:"vote_count"`
}

// All-time, not scoped to the current post-reset cycle -- deliberately
// counts every upvote a user has ever cast (void or not), same "lifetime
// cumulative, no time window" shape as GetTopReviewers. Filtering to
// void = false would wipe most of the board every time the monthly
// automated reset runs, which defeats the point of recognizing a
// consistently active voter.
func (q *Queries) GetTopVoters(ctx context.Context, limit int32) ([]GetTopVotersRow, error) {
	rows, err := q.db.Query(ctx, getTopVoters, limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetTopVotersRow
	for rows.Next() {
		var i GetTopVotersRow
		if err := rows.Scan(&i.Author, &i.VoteCount); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserEntityVotesPage = `-- name: GetUserEntityVotesPage :many
SELECT itag, target_id, target_type, author, upvote, void, void_reason, voided_at, created_at, vote_num, credit_redeem, immutable
FROM entity_votes
WHERE target_id = $1 AND target_type = $2 AND author = $3
LIMIT $4 OFFSET $5
`

type GetUserEntityVotesPageParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Author     string `db:"author" json:"author"`
	Limit      int32  `db:"limit" json:"limit"`
	Offset     int32  `db:"offset" json:"offset"`
}

type GetUserEntityVotesPageRow struct {
	Itag         pgtype.UUID        `db:"itag" json:"itag"`
	TargetID     string             `db:"target_id" json:"target_id"`
	TargetType   string             `db:"target_type" json:"target_type"`
	Author       string             `db:"author" json:"author"`
	Upvote       bool               `db:"upvote" json:"upvote"`
	Void         bool               `db:"void" json:"void"`
	VoidReason   pgtype.Text        `db:"void_reason" json:"void_reason"`
	VoidedAt     pgtype.Timestamptz `db:"voided_at" json:"voided_at"`
	CreatedAt    pgtype.Timestamp   `db:"created_at" json:"created_at"`
	VoteNum      int32              `db:"vote_num" json:"vote_num"`
	CreditRedeem pgtype.UUID        `db:"credit_redeem" json:"credit_redeem"`
	Immutable    bool               `db:"immutable" json:"immutable"`
}

func (q *Queries) GetUserEntityVotesPage(ctx context.Context, arg GetUserEntityVotesPageParams) ([]GetUserEntityVotesPageRow, error) {
	rows, err := q.db.Query(ctx, getUserEntityVotesPage,
		arg.TargetID,
		arg.TargetType,
		arg.Author,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetUserEntityVotesPageRow
	for rows.Next() {
		var i GetUserEntityVotesPageRow
		if err := rows.Scan(
			&i.Itag,
			&i.TargetID,
			&i.TargetType,
			&i.Author,
			&i.Upvote,
			&i.Void,
			&i.VoidReason,
			&i.VoidedAt,
			&i.CreatedAt,
			&i.VoteNum,
			&i.CreditRedeem,
			&i.Immutable,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getUserVoteBanned = `-- name: GetUserVoteBanned :one
SELECT vote_banned FROM users WHERE user_id = $1
`

func (q *Queries) GetUserVoteBanned(ctx context.Context, userID string) (bool, error) {
	row := q.db.QueryRow(ctx, getUserVoteBanned, userID)
	var vote_banned bool
	err := row.Scan(&vote_banned)
	return vote_banned, err
}

const getVoteAuthors = `-- name: GetVoteAuthors :many
SELECT author FROM entity_votes WHERE target_id = $1 AND target_type = $2 GROUP BY author
`

type GetVoteAuthorsParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) GetVoteAuthors(ctx context.Context, arg GetVoteAuthorsParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getVoteAuthors, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author string
		if err := rows.Scan(&author); err != nil {
			return nil, err
		}
		items = append(items, author)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteAuthorsPage = `-- name: GetVoteAuthorsPage :many
SELECT author FROM entity_votes WHERE target_id = $1 AND target_type = $2 GROUP BY author LIMIT $3 OFFSET $4
`

type GetVoteAuthorsPageParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Limit      int32  `db:"limit" json:"limit"`
	Offset     int32  `db:"offset" json:"offset"`
}

func (q *Queries) GetVoteAuthorsPage(ctx context.Context, arg GetVoteAuthorsPageParams) ([]string, error) {
	rows, err := q.db.Query(ctx, getVoteAuthorsPage,
		arg.TargetID,
		arg.TargetType,
		arg.Limit,
		arg.Offset,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var author string
		if err := rows.Scan(&author); err != nil {
			return nil, err
		}
		items = append(items, author)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteCreditTiers = `-- name: GetVoteCreditTiers :many
SELECT id, target_type, position, votes, cents, created_at FROM vote_credit_tiers WHERE target_type = $1 ORDER BY position ASC
`

type GetVoteCreditTiersRow struct {
	ID         string             `db:"id" json:"id"`
	TargetType string             `db:"target_type" json:"target_type"`
	Position   int32              `db:"position" json:"position"`
	Votes      int32              `db:"votes" json:"votes"`
	Cents      int32              `db:"cents" json:"cents"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetVoteCreditTiers(ctx context.Context, targetType string) ([]GetVoteCreditTiersRow, error) {
	rows, err := q.db.Query(ctx, getVoteCreditTiers, targetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoteCreditTiersRow
	for rows.Next() {
		var i GetVoteCreditTiersRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.Position,
			&i.Votes,
			&i.Cents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteCreditTiersFiltered = `-- name: GetVoteCreditTiersFiltered :many
SELECT id, target_type, position, votes, cents, created_at
FROM vote_credit_tiers
WHERE $1::text IS NULL OR target_type = $1
ORDER BY position ASC
`

type GetVoteCreditTiersFilteredRow struct {
	ID         string             `db:"id" json:"id"`
	TargetType string             `db:"target_type" json:"target_type"`
	Position   int32              `db:"position" json:"position"`
	Votes      int32              `db:"votes" json:"votes"`
	Cents      int32              `db:"cents" json:"cents"`
	CreatedAt  pgtype.Timestamptz `db:"created_at" json:"created_at"`
}

func (q *Queries) GetVoteCreditTiersFiltered(ctx context.Context, targetType pgtype.Text) ([]GetVoteCreditTiersFilteredRow, error) {
	rows, err := q.db.Query(ctx, getVoteCreditTiersFiltered, targetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetVoteCreditTiersFilteredRow
	for rows.Next() {
		var i GetVoteCreditTiersFilteredRow
		if err := rows.Scan(
			&i.ID,
			&i.TargetType,
			&i.Position,
			&i.Votes,
			&i.Cents,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getVoteRedeemLogs = `-- name: GetVoteRedeemLogs :many
SELECT target_id, target_type, created_at, redeemed_at, id, redeemed_credits, credits
FROM entity_vote_redeem_logs
WHERE target_id = $1 AND target_type = $2
ORDER BY created_at DESC
`

type GetVoteRedeemLogsParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
}

func (q *Queries) GetVoteRedeemLogs(ctx context.Context, arg GetVoteRedeemLogsParams) ([]EntityVoteRedeemLog, error) {
	rows, err := q.db.Query(ctx, getVoteRedeemLogs, arg.TargetID, arg.TargetType)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []EntityVoteRedeemLog
	for rows.Next() {
		var i EntityVoteRedeemLog
		if err := rows.Scan(
			&i.TargetID,
			&i.TargetType,
			&i.CreatedAt,
			&i.RedeemedAt,
			&i.ID,
			&i.RedeemedCredits,
			&i.Credits,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertAutomatedVoteReset = `-- name: InsertAutomatedVoteReset :exec
INSERT INTO automated_vote_resets (created_at) VALUES (NOW())
`

func (q *Queries) InsertAutomatedVoteReset(ctx context.Context) error {
	_, err := q.db.Exec(ctx, insertAutomatedVoteReset)
	return err
}

const insertEntityVote = `-- name: InsertEntityVote :exec
INSERT INTO entity_votes (author, target_id, target_type, upvote, vote_num) VALUES ($1, $2, $3, $4, $5)
`

type InsertEntityVoteParams struct {
	Author     string `db:"author" json:"author"`
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Upvote     bool   `db:"upvote" json:"upvote"`
	VoteNum    int32  `db:"vote_num" json:"vote_num"`
}

func (q *Queries) InsertEntityVote(ctx context.Context, arg InsertEntityVoteParams) error {
	_, err := q.db.Exec(ctx, insertEntityVote,
		arg.Author,
		arg.TargetID,
		arg.TargetType,
		arg.Upvote,
		arg.VoteNum,
	)
	return err
}

const insertVoteRedeemLog = `-- name: InsertVoteRedeemLog :one
INSERT INTO entity_vote_redeem_logs (target_id, target_type, credits) VALUES ($1, $2, $3) RETURNING id
`

type InsertVoteRedeemLogParams struct {
	TargetID   string `db:"target_id" json:"target_id"`
	TargetType string `db:"target_type" json:"target_type"`
	Credits    int32  `db:"credits" json:"credits"`
}

func (q *Queries) InsertVoteRedeemLog(ctx context.Context, arg InsertVoteRedeemLogParams) (pgtype.UUID, error) {
	row := q.db.QueryRow(ctx, insertVoteRedeemLog, arg.TargetID, arg.TargetType, arg.Credits)
	var id pgtype.UUID
	err := row.Scan(&id)
	return id, err
}

const lockEntityVotesExclusive = `-- name: LockEntityVotesExclusive :exec
LOCK TABLE entity_votes IN EXCLUSIVE MODE
`

func (q *Queries) LockEntityVotesExclusive(ctx context.Context) error {
	_, err := q.db.Exec(ctx, lockEntityVotesExclusive)
	return err
}

const lockVoteCastTarget = `-- name: LockVoteCastTarget :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || ':' || $2::text || ':' || $3::text))
`

type LockVoteCastTargetParams struct {
	UserID     string `db:"user_id" json:"user_id"`
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

// A per-(user, target) advisory lock (auto-released at transaction end),
// held from the start of create_user_entity_vote's transaction, before
// EntityVoteCheck reads the user's existing votes/wait timer for this
// target. Without it, two concurrent vote requests from the same user for
// the same target can both read "not voted yet" / "wait elapsed" before
// either commits its INSERT, both pass the PerUser/VoteTime check, and both
// get counted -- exceeding the entity's configured vote limits. Scoped to
// (user, target) rather than target alone so unrelated users voting for the
// same entity at the same time are never serialized against each other.
func (q *Queries) LockVoteCastTarget(ctx context.Context, arg LockVoteCastTargetParams) error {
	_, err := q.db.Exec(ctx, lockVoteCastTarget, arg.UserID, arg.TargetType, arg.TargetID)
	return err
}

const lockVoteRedeemTarget = `-- name: LockVoteRedeemTarget :exec
SELECT pg_advisory_xact_lock(hashtext($1::text || ':' || $2::text))
`

type LockVoteRedeemTargetParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

// A per-target advisory lock (auto-released at transaction end), NOT the
// table-wide LockEntityVotesExclusive used by the batch vote-reset job --
// that would serialize every redemption sitewide instead of just the ones
// racing for the same target. Held for the duration of
// EntityRedeemVoteCredits, before it reads the redeemable vote count, so
// two concurrent redeem calls for the same target can no longer both read
// "N votes still unclaimed" and both log a fresh N-vote credit grant --
// the second call blocks until the first commits, then correctly sees
// however many votes are actually still unclaimed (possibly zero).
func (q *Queries) LockVoteRedeemTarget(ctx context.Context, arg LockVoteRedeemTargetParams) error {
	_, err := q.db.Exec(ctx, lockVoteRedeemTarget, arg.TargetType, arg.TargetID)
	return err
}

const recomputeBotApproximateVotes = `-- name: RecomputeBotApproximateVotes :exec
UPDATE bots t SET approximate_votes = v.count FROM
    (SELECT target_id, COUNT(*) FILTER (WHERE upvote) - COUNT(*) FILTER (WHERE NOT upvote) AS count
     FROM entity_votes WHERE target_type = $1 AND void = false GROUP BY target_id) v
WHERE t.bot_id = v.target_id
`

func (q *Queries) RecomputeBotApproximateVotes(ctx context.Context, targetType string) error {
	_, err := q.db.Exec(ctx, recomputeBotApproximateVotes, targetType)
	return err
}

const recomputeServerApproximateVotes = `-- name: RecomputeServerApproximateVotes :exec
UPDATE servers t SET approximate_votes = v.count FROM
    (SELECT target_id, COUNT(*) FILTER (WHERE upvote) - COUNT(*) FILTER (WHERE NOT upvote) AS count
     FROM entity_votes WHERE target_type = $1 AND void = false GROUP BY target_id) v
WHERE t.server_id = v.target_id
`

func (q *Queries) RecomputeServerApproximateVotes(ctx context.Context, targetType string) error {
	_, err := q.db.Exec(ctx, recomputeServerApproximateVotes, targetType)
	return err
}

const recomputeTeamApproximateVotes = `-- name: RecomputeTeamApproximateVotes :exec
UPDATE teams t SET approximate_votes = v.count FROM
    (SELECT target_id, COUNT(*) FILTER (WHERE upvote) - COUNT(*) FILTER (WHERE NOT upvote) AS count
     FROM entity_votes WHERE target_type = $1 AND void = false GROUP BY target_id) v
WHERE t.id::text = v.target_id
`

func (q *Queries) RecomputeTeamApproximateVotes(ctx context.Context, targetType string) error {
	_, err := q.db.Exec(ctx, recomputeTeamApproximateVotes, targetType)
	return err
}

const redeemAllVotesForTarget = `-- name: RedeemAllVotesForTarget :exec
UPDATE entity_votes SET credit_redeem = $1, void_reason = 'Vote credits redeemed', voided_at = NOW() WHERE target_id = $2 AND target_type = $3 AND void = false AND credit_redeem IS NULL
`

type RedeemAllVotesForTargetParams struct {
	CreditRedeem pgtype.UUID `db:"credit_redeem" json:"credit_redeem"`
	TargetID     string      `db:"target_id" json:"target_id"`
	TargetType   string      `db:"target_type" json:"target_type"`
}

// See RedeemVotesByItags -- same fix, same reasoning. credit_redeem IS NULL
// in the WHERE clause is required now that redeeming no longer voids a vote:
// without it, a vote already spent by an earlier redemption (void = false,
// credit_redeem set) would still match "void = false" and get claimed again.
func (q *Queries) RedeemAllVotesForTarget(ctx context.Context, arg RedeemAllVotesForTargetParams) error {
	_, err := q.db.Exec(ctx, redeemAllVotesForTarget, arg.CreditRedeem, arg.TargetID, arg.TargetType)
	return err
}

const redeemVotesByItags = `-- name: RedeemVotesByItags :exec
UPDATE entity_votes SET credit_redeem = $1, void_reason = 'Vote credits redeemed', voided_at = NOW() WHERE itag = ANY($2::uuid[]) AND credit_redeem IS NULL
`

type RedeemVotesByItagsParams struct {
	CreditRedeem pgtype.UUID   `db:"credit_redeem" json:"credit_redeem"`
	Itags        []pgtype.UUID `db:"itags" json:"itags"`
}

// Deliberately does NOT set void = true. A vote being spent on credits is
// not the same event as a vote being reset/removed (VoidAllUnvoidedEntityVotes,
// VoidEntityVotesForTarget, VoidAllEntityVotesForType all mean the latter) --
// voiding a redeemed vote used to also drop it from the entity's public vote
// count (every count query filters on void = false), silently deflating a
// bot/server/team's vote total every time its owner cashed in credits.
// credit_redeem (set here) is what actually marks a vote as spent; void_reason/
// voided_at are kept purely as display metadata for the vote history UI, not
// as a gate on anything. credit_redeem IS NULL guards the same re-claim
// risk RedeemAllVotesForTarget's own comment explains -- belt-and-suspenders
// alongside the caller's per-target advisory lock (LockVoteRedeemTarget),
// in case a future caller ever reaches this query without going through it.
func (q *Queries) RedeemVotesByItags(ctx context.Context, arg RedeemVotesByItagsParams) error {
	_, err := q.db.Exec(ctx, redeemVotesByItags, arg.CreditRedeem, arg.Itags)
	return err
}

const updateBotApproximateVotes = `-- name: UpdateBotApproximateVotes :exec
UPDATE bots SET approximate_votes = $1 WHERE bot_id = $2
`

type UpdateBotApproximateVotesParams struct {
	ApproximateVotes int32  `db:"approximate_votes" json:"approximate_votes"`
	BotID            string `db:"bot_id" json:"bot_id"`
}

func (q *Queries) UpdateBotApproximateVotes(ctx context.Context, arg UpdateBotApproximateVotesParams) error {
	_, err := q.db.Exec(ctx, updateBotApproximateVotes, arg.ApproximateVotes, arg.BotID)
	return err
}

const updateServerApproximateVotes = `-- name: UpdateServerApproximateVotes :exec
UPDATE servers SET approximate_votes = $1 WHERE server_id = $2
`

type UpdateServerApproximateVotesParams struct {
	ApproximateVotes int32  `db:"approximate_votes" json:"approximate_votes"`
	ServerID         string `db:"server_id" json:"server_id"`
}

func (q *Queries) UpdateServerApproximateVotes(ctx context.Context, arg UpdateServerApproximateVotesParams) error {
	_, err := q.db.Exec(ctx, updateServerApproximateVotes, arg.ApproximateVotes, arg.ServerID)
	return err
}

const updateTeamApproximateVotes = `-- name: UpdateTeamApproximateVotes :exec
UPDATE teams SET approximate_votes = $1 WHERE id = $2
`

type UpdateTeamApproximateVotesParams struct {
	ApproximateVotes int32  `db:"approximate_votes" json:"approximate_votes"`
	ID               string `db:"id" json:"id"`
}

func (q *Queries) UpdateTeamApproximateVotes(ctx context.Context, arg UpdateTeamApproximateVotesParams) error {
	_, err := q.db.Exec(ctx, updateTeamApproximateVotes, arg.ApproximateVotes, arg.ID)
	return err
}

const voidAllEntityVotesForType = `-- name: VoidAllEntityVotesForType :exec
UPDATE entity_votes SET void = TRUE, void_reason = 'Votes (all entities) reset', voided_at = NOW()
WHERE target_type = $1 AND immutable = false
`

func (q *Queries) VoidAllEntityVotesForType(ctx context.Context, targetType string) error {
	_, err := q.db.Exec(ctx, voidAllEntityVotesForType, targetType)
	return err
}

const voidAllUnvoidedEntityVotes = `-- name: VoidAllUnvoidedEntityVotes :exec
UPDATE entity_votes SET void = TRUE, void_reason = 'Automated votes reset', voided_at = NOW() WHERE void = false AND immutable = false
`

func (q *Queries) VoidAllUnvoidedEntityVotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, voidAllUnvoidedEntityVotes)
	return err
}

const voidEntityVotesForTarget = `-- name: VoidEntityVotesForTarget :exec
UPDATE entity_votes SET void = TRUE, void_reason = 'Votes (single entity) reset', voided_at = NOW()
WHERE target_type = $1 AND target_id = $2 AND void = FALSE
`

type VoidEntityVotesForTargetParams struct {
	TargetType string `db:"target_type" json:"target_type"`
	TargetID   string `db:"target_id" json:"target_id"`
}

func (q *Queries) VoidEntityVotesForTarget(ctx context.Context, arg VoidEntityVotesForTargetParams) error {
	_, err := q.db.Exec(ctx, voidEntityVotesForTarget, arg.TargetType, arg.TargetID)
	return err
}

const zeroBotApproximateVotes = `-- name: ZeroBotApproximateVotes :exec
UPDATE bots SET approximate_votes = 0
`

func (q *Queries) ZeroBotApproximateVotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, zeroBotApproximateVotes)
	return err
}

const zeroServerApproximateVotes = `-- name: ZeroServerApproximateVotes :exec
UPDATE servers SET approximate_votes = 0
`

func (q *Queries) ZeroServerApproximateVotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, zeroServerApproximateVotes)
	return err
}

const zeroTeamApproximateVotes = `-- name: ZeroTeamApproximateVotes :exec
UPDATE teams SET approximate_votes = 0
`

func (q *Queries) ZeroTeamApproximateVotes(ctx context.Context) error {
	_, err := q.db.Exec(ctx, zeroTeamApproximateVotes)
	return err
}
